### ISSUE TITLE
ARM support for CBC solver

### ISSUE THREAD

**Issue by KarolTx** [coin-or/pulp#102]
Hi,

I am using pulp for small on-the-fly optimizations on an ARM board. The included solver is compiled for win & linux on x86 machines -> it does not work on the ARM machine.

The error message:

```
Python 3.4.2 (default, Oct  8 2014, 14:38:51) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulp
>>> pulp.pulpTestAll()
         Testing zero subtraction
         Testing inconsistant lp solution
[Errno 8] Exec format error
* Solver <class 'pulp.solvers.PULP_CBC_CMD'> failed.
Solver <class 'pulp.solvers.CPLEX_DLL'> unavailable
Solver <class 'pulp.solvers.CPLEX_CMD'> unavailable
Solver <class 'pulp.solvers.CPLEX_PY'> unavailable
Solver <class 'pulp.solvers.COIN_CMD'> unavailable
Solver <class 'pulp.solvers.COINMP_DLL'> unavailable
Solver <class 'pulp.solvers.GLPK_CMD'> unavailable
Solver <class 'pulp.solvers.XPRESS'> unavailable
Solver <class 'pulp.solvers.GUROBI'> unavailable
Solver <class 'pulp.solvers.GUROBI_CMD'> unavailable
Solver <class 'pulp.solvers.PYGLPK'> unavailable
Solver <class 'pulp.solvers.YAPOSIB'> unavailable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/archive/.local/lib/python3.4/site-packages/pulp/pulp.py", line 2283, in pulpTestAll
    raise PulpError("Tests Failed")
pulp.constants.PulpError: Tests Failed
```

Can pulp's CBC solver be shipped as source to be compiled on install? Or at least write a warning on different architectures than anticipated?

Detection of 64b in pulp/solvers.py:111

```
is_64bits = sys.maxsize > 2**32
```

-> it's automatically assumed x86 is running pulp.

I will now try to use COIN_CMD..

Cheers,
Karol

**Comment by davidusb-geek** [comment]
Hi! So this was solved using COIN_CMD? I'm having the exact same issue.

**Comment by tkralphs** [comment]
I'm not sure why the original issue was closed without a response, but [Cbc](https://github.com/coin-or/Cbc) is itself a COIN-OR project, so the source is readily available. There are no issues with building it for ARM architectures and you'll probably find some , but if you have any more questions, it's best to ask them in the Cbc project.

**Comment by davidusb-geek** [comment]
Ok thank you for your reply. I'll go go directly there. If I ever find a solution I'll post it here.

**Comment by davidusb-geek** [comment]
Hi the solution in my case was to install an additional solver. I installed the glpk solver using:
```
sudo apt-get install glpk-utils
```
This is well documented in the Pulp installation instructions.
Then in the code I have changed to:
```
opt_model.solve(GLPK_CMD(msg=0))
```
Now my LP optimization is working just fine on an arm64 architecture.

**Comment by tkralphs** [comment]
What Linux distro are you on? Cbc (Clp for linear programs) is likely also installable with `apt`. 

https://doc.sagemath.org/html/en/reference/spkg/cbc.html#equivalent-system-packages

You will probably see better performance with Cbc than with Glpk in general if that matters to you.

**Comment by davidusb-geek** [comment]
Oh yes it matters. Thank you for this clarification. I will be adding `coinor-libcbc-dev` and `coinor-cbc` using `apt-get`. I'm using CBC as the default solver and falling back to glpk in the case of the solver not found error.
