### ISSUE TITLE
LpProblem.valid() doesn't work properly when objective is zero

### ISSUE THREAD

**Issue by kotaishr** [coin-or/pulp#104]
``` python
import pulp

mip1 = pulp.LpProblem('****** MIP1 ******')
x = pulp.LpVariable('x')
mip1 += (0 * x)
mip1 += (x >= 1)

mip1.solve() # This problem is obviously feasible
print mip1
print 'x', x.value()  # x = 1.0 is a feasible solution of the LP problem,
print mip1.valid()  # but valid() returns false.
print

mip2 = pulp.LpProblem('****** MIP2 ******')
y = pulp.LpVariable('y')
mip2 += (1 * y)   # If the objective is not zero, the problem above doesn't occur.
mip2 += (y >= 1)

mip2.solve() 
print mip2
print 'y', y.value()
print mip2.valid()
```

This problem is caused by the dummy variable introduced to `mip1`  when it is solved.
The default value of it is `None`, not `0`.  This causes the method valid() to return false:

``` python
#line 1205, pulp.py
    def valid(self, eps = 0):  
        for v in self.variables():  
            if not v.valid(eps): return False  # if dummy==None, this line returns false
```

I think there're two ways to fix this problem:
1. Making the default value of dummy variables to zero.
2. Skipping dummy variables in checking validity.

However, I'm not sure either of the suggestions is consistent with other methods.

**Comment by rimaddo** [comment]
Hey, happy to help on this if no-one is looking at it. Do you have a preferred option? For me 1 makes more sense, and for example I know if you don't set the objective with gurobi it defaults to 0?

**Comment by pchtsp** [comment]
fixed in https://github.com/coin-or/pulp/pull/399 thanks again!
