### ISSUE TITLE
TypeError: unorderable types: LpAffineExpression() < int() with prob += x1+x2 < 1

### ISSUE THREAD

**Issue by flydm** [coin-or/pulp#108]
In python 3.4.3, when set the constrain as "prob += x1+x2 < 1" the error as the title will occur,
However," prob += x1+x2 <= 1" will be ok, the "=" should be add. 
In python 2.x, the problem is not exist.
What is this problem?

**Comment by CJMenart** [comment]
Hey,

I just so happened to stumble upon your ask here while I was working on the same bug. Probably not relevant to you anymore, but for anyone else who comes along--the error is that you can't do Integer Linear Programming with strict inequalities. The solver can only accept constraints with inclusive bounds, i.e. of the <=, >= variety. That is a feature, not a bug.
