### ISSUE TITLE
Add examples for new features

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#11]
```
The new features.
Module poytope
Combination functions
lexicographic solve

Need some examples and documentation


```

Original issue reported on code.google.com by `stuvagas@gmail.com` on 20 Nov 2008 at 6:56

**Comment by pchtsp** [comment]
I'm not sure if these functionalities exists and, if they do, if they are needed in the documentation. @stumitchell I guess you know a little more about it ?
