### ISSUE TITLE
Can't add time limit to GLPK: "Invalid option '--tmlim 120'; try glpsol --help"

### ISSUE THREAD

**Issue by turion** [coin-or/pulp#111]
I'm creating an lp solver like this:

```
pulp.GLPK(options=["--tmlim 120"])
```

But when I run it, I get the error message "Invalid option '--tmlim 120'; try glpsol --help".

**Comment by turion** [comment]
After looking at the code once again, it seems like this comes from the way `subprocess.call` treats arguments that have spaces inside (it adds quotation marks around the string). It works if I do this:

    pulp.GLPK(options=["--tmlim", "120"])

**Comment by pchtsp** [comment]
ok thanks! we should document this. I will create a new ticket.
