### ISSUE TITLE
Permission denied with cbc solver

### ISSUE THREAD

**Issue by mkdatak** [coin-or/pulp#118]
Hello, 

I'm trying to test test1.py in examples with cbc solver.

I've touched 

``` python
coin = COIN("/home/me/dev/Tools/Optim/SYMPHONY-5.6.14/lib")
prob.solve(coin)
```
I'm getting : 

``` 
Traceback (most recent call last):
  File "test1.py", line 32, in <module>
    prob.solve(coin)
  File "/opt/anaconda/lib/python2.7/site-packages/pulp/pulp.py", line 1643, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/opt/anaconda/lib/python2.7/site-packages/pulp/solvers.py", line 1303, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/opt/anaconda/lib/python2.7/site-packages/pulp/solvers.py", line 1361, in solve_CBC
    stderr = pipe)
  File "/opt/anaconda/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/opt/anaconda/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by sschnug** [comment]
I would be surprised to see that this has something to do with pulp.

Check the permission-rights of that folder/files.
Or for fun / to debug: call the python script as root.

**Comment by tkralphs** [comment]
I'm not sure why you're passing in a path to a SYMPHONY installation. Are you trying to use PuLP with SYMPHONY? This is possible, but only using [yaposib](https://github.com/coin-or/yaposib).

In any case, the argument you passed to `COIN` is incorrect. It should be the path to the `cbc` executable on your system. The error you're getting is one of the errors that can arise if you pass an incorrect argument to the constructor of `COIN`. As long as `cbc` is in your executable path (type `which cbc` to find out if it is), then
```
coin = COIN()
```
should suffice and this is the easiest way. If you want to get PuLP working with SYMPHONY, it's a bit of work installing `yaposib`, but I can try to help.

**Comment by stumitchell** [comment]
closing this unless you are still having problems

**Comment by mkdatak** [comment]
You can close it

Thank you for  your help
Le 6 févr. 2017 10:44, "Stuart Mitchell" <notifications@github.com> a
écrit :
