### ISSUE TITLE
How to use external data in the objective function?

### ISSUE THREAD

**Issue by naught101** [coin-or/pulp#120]
I want to select a square subset of a square matrix, such that the sum of the subset matrix is minimised. Some code:

```{python}
import nump as np
import pulp

def subset_matrix(data, inds):
    return data[np.ix_(inds, inds)]

A = np.random.random((10, 10))  # replace with covariance matrix

indices = list(range(len(A)))

prob = pulp.LpProblem("Minimum subset", pulp.LpMaximize)

x = pulp.LpVariable.dicts('elem', indices, lowBound=0, upBound=1, cat=pulp.LpInteger)

prob += pulp.lpSum(subset_matrix(A, [x[i] for i in indices]))

prob.solve()
```

This fails because numpy indexing doesn't like the `inds` being a list of `LpVariables`. Is there a way around this?

**Comment by sschnug** [comment]
There is no modelling-language which supports these kind of constraints (that i know) because it's very very hard to implement (and would need to use many assumptions).

You will have to formulate this yourself using binary/integer-variables which describe your selection of the matrix-subset!

*Again just to make it clear: This is not an issue with pulp. It's not a feature supported (and it's not supported in any of the common commercial-libs as well like gurobi and cplex)*

**Comment by naught101** [comment]
Does it make a difference that that sum line is the objective function, not a constraint? Perhaps I am doing something wrong there too.. 

The constraint should only be that the matrix subset is of a fixed size, I guess something like `prob += 5<= sum(x) <= 5` or something? I'm not entirely entirely sure of when to use sum vs. LpSum..

**Comment by sschnug** [comment]
I don't understand your question and your code is incomplete and therefore it's hard to reason about. (example: ```subset_cov``` is not defined).

This is much more suited for the pulp-or mailing-list [here](https://groups.google.com/forum/#!forum/pulp-or-discuss)

**Comment by naught101** [comment]
Sorry, `subset_cov` should be `subset_matrix` - the function at the top (fixed in OP, also clarified the inds usage). I think the incompleteness is because I'm not familiar with the syntax.

Basically, I want to loop over subsets of k (< 10) indices, and use those indices to calculate the sum of the matrix subset defined by those indices, and use that sum as the objective function.

**Comment by SashaZd** [comment]
This is not really an issue for the repository. I suggest asking on Stackoverflow instead.
