### ISSUE TITLE
error in tests for CPLEX_PY solver on unbounded problems?

### ISSUE THREAD

**Issue by patrikhaslum** [coin-or/pulp#121]
Tests pulpTest012 and pulpTest123 expect the CPLEX_PY solver to return LpStatusInfeasible on unbounded problems, but it returns LpStatusUnbounded. Is this an error in the tests?
Changing
`pulpTestCheck(prob, solver, [LpStatusInfeasible])`
to
`pulpTestCheck(prob, solver, [LpStatusInfeasible, LpStatusUnbounded])`
on line 143 in tests.py, and removing CPLEX_PY from the list of solvers in line 586 in tests.py makes this solver pass all tests (when running pulpTestAll). This was tested with CPLEX 12.5.1, after installing the CPLEX python module.

**Comment by samvy** [comment]
I suggest this modification :

diff --git a/src/pulp/tests.py b/src/pulp/tests.py
index ddd9374..67ad420 100644
--- a/src/pulp/tests.py
+++ b/src/pulp/tests.py
@@ -139,8 +139,8 @@ def pulpTest012(solver):
     prob += -y+z == 7, "c3"
     prob += w >= 0, "c4"
     print("\t Testing unbounded continuous LP solution")
-    if solver.__class__ in [GUROBI, CPLEX_CMD, YAPOSIB, CPLEX_PY]:
-        # These solvers report infeasible or unbounded
+    if solver.__class__ in [GUROBI, YAPOSIB]:
+        # These solvers report infeasible
         pulpTestCheck(prob, solver, [LpStatusInfeasible])
     elif solver.__class__ in [COINMP_DLL,]:
         # COINMP_DLL is just plain wrong
@@ -153,7 +153,7 @@ def pulpTest012(solver):
         # CPLEX_DLL Does not report unbounded problems, correctly
         # GUROBI_CMD has a very simple interface
          pulpTestCheck(prob, solver, [LpStatusNotSolved])
-    else:
+    else: #including CPLEX_CMD and CPLEX_PY
         pulpTestCheck(prob, solver, [LpStatusUnbounded])
 
 def pulpTest013(solver):
@@ -585,7 +585,7 @@ def pulpTest123(solver):
     prob += -y+z == 7, "c3"
     prob.extend((w >= -1).makeElasticSubProblem(penalty = 0.9))
     print("\t Testing elastic constraints (penalty unbounded)")
-    if solver.__class__ in [COINMP_DLL, GUROBI, CPLEX_CMD, CPLEX_PY, YAPOSIB]:
+    if solver.__class__ in [COINMP_DLL, GUROBI, YAPOSIB]:
         # COINMP_DLL Does not report unbounded problems, correctly
          pulpTestCheck(prob, solver, [LpStatusInfeasible])
     elif solver.__class__ is GLPK_CMD:
@@ -594,7 +594,7 @@ def pulpTest123(solver):
     elif solver.__class__ in [CPLEX_DLL, GUROBI_CMD]:
         # GLPK_CMD Does not report unbounded problems, correctly
          pulpTestCheck(prob, solver, [LpStatusNotSolved])
-    else:
+    else: # including CPLEX_CMD, CPLEX_PY
         pulpTestCheck(prob, solver, [LpStatusUnbounded])

Regards

**Comment by pchtsp** [comment]
`CPLEX_CMD` is still giving the wrong status. I took out `CPLEX_PY` from tests in https://github.com/coin-or/pulp/pull/274
