### ISSUE TITLE
Contributing Document needed

### ISSUE THREAD

**Issue by SashaZd** [coin-or/pulp#122]
I have a few fixes and enhancements that I wanted to make with PuLP. I was about to start when I noticed you don't have a CONTRIBUTING document. I suggest creating one to make it easier for people to jump right in. 

Here's an example of a [CONTRIBUTING](https://github.com/django/django/blob/master/CONTRIBUTING.rst) document and link to their [site/contributing page](https://docs.djangoproject.com/en/dev/internals/contributing/) that was very helpful in the Django Python Git. 

I can see that Stu tried to post guidelines at one point of time on this Issue #5.

**Comment by tkralphs** [comment]
Hi @SashaZd, thanks for pointing that out. All [COIN-OR](https://www.coin-or.org/) projects should be following the general guidelines of COIN-OR with respect to contributions. The current general guidelines are [here]( 
https://www.coin-or.org/contributing/code/). Of course, the specific mechanism for submission is up to the individual PM. 

These guidelines were developed before the availability of tools like git and github, which make it easier to for others to make contributions and for project managers to track those contributions. I think we probably need to revisit and also develop a standard CONTRIBUTING file that can be used across all projects. But for now, this are the guidelines in place.

**Comment by pchtsp** [comment]
The contributing document is now included here: https://github.com/coin-or/pulp/blob/master/.github/CONTRIBUTING.md with some instructions and reference to the COIN-OR guidelines.
