### ISSUE TITLE
Current Pulp version on PyPI not installable

### ISSUE THREAD

**Issue by llnz** [coin-or/pulp#123]
The current stable version of pulp on PyPI depends on an old version of pyparsing (for py2.x). A newer version of pyparsing is also used by setuptools, which is used to install the older version pyparsing when installed pulp. The old version of pyparsing doesn't work with new versions of setuptools, and fails to install the older pyparsing for pulp. 

Therefore pulp is not installable on python 2.7 with up-to-date setuptools.

I believe a new version of pulp needs to be released. This issue has been fixed in #107 so only a release needs to be created.

**Comment by gricey432** [comment]
A workaround for now seems to be to install pulp without dependencies
`pip install pulp --no-deps`
So far that seems to work fine for me

But this really needs to be fixed

**Comment by TRManderson** [comment]
I just emailed Stuart Mitchell, who seems to be the core maintainer on PuLP, regarding this. Hopefully we'll see a fix soon.

**Comment by stumitchell** [comment]
Wow, sorry I wonder why I don't get notifications for this project from github anymore

should be fixed in 1.6.2 now on pypi
