### ISSUE TITLE
Cant read GLPSOL output file correctly in solvers.py

### ISSUE THREAD

**Issue by nyacom** [coin-or/pulp#128]
Hi there.
I'm using GLPK (v4.55) solver via PuLP (1.6.0). I encountered a problem that all values from via GLPK interface are zeros even if the solution found. I think this problem is occurred by incorrect reading result column value from GLPSOL output file in solvers.py line 425. I guess there should use line[2] (Column of Activity), instead of line[3] (Column of Lower bound). (But, I'm not familiar with GLPSOL file format...)
I appreciate any comment of this is wrong or not. Thanks.

**Comment by pchtsp** [comment]
Sorry for answering this late, do you have any model example for this?

**Comment by pchtsp** [comment]
same as https://github.com/coin-or/pulp/issues/287 I'm closing.
