### ISSUE TITLE
Pulp and Cplex

### ISSUE THREAD

**Issue by samvy** [coin-or/pulp#129]
Hi, I try to use pulp with cplex but I have a problem when the package is imported :

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pulp import *
  File "/usr/lib/python2.7/dist-packages/pulp/__init__.py", line 34, in <module>
    from .pulp import *
  File "/usr/lib/python2.7/dist-packages/pulp/pulp.py", line 102, in <module>
    from .solvers import *
  File "/usr/lib/python2.7/dist-packages/pulp/solvers.py", line 1001, in <module>
    class CPLEX_PY(LpSolver):
  File "/usr/lib/python2.7/dist-packages/pulp/solvers.py", line 1010, in CPLEX_PY
    CplexLpStatus = {cplex.Cplex.solution.status.MIP_optimal: LpStatusOptimal,
AttributeError: type object 'Cplex' has no attribute 'solution'

Cplex Version = 12.7.1.0
PuLP Version: 1.6.5

Regards

**Comment by timeregained** [comment]
I have met the same issue and the following might be a work around.

From the last minor update from 12.7.0.0 to 12.7.1.0, IBM has delete some contents of __init__.py in cplex package folder.

"
variables             = _internal._subinterfaces.VariablesInterface()
    """See `_internal._subinterfaces.VariablesInterface()` """
    linear_constraints    = _internal._subinterfaces.LinearConstraintInterface()
    """See `_internal._subinterfaces.LinearConstraintInterface()` """
    quadratic_constraints = _internal._subinterfaces.QuadraticConstraintInterface()
    """See `_internal._subinterfaces.QuadraticConstraintInterface()` """
    indicator_constraints = _internal._subinterfaces.IndicatorConstraintInterface()
    """See `_internal._subinterfaces.IndicatorConstraintInterface()` """
    SOS                   = _internal._subinterfaces.SOSInterface()
    """See `_internal._subinterfaces.SOSInterface()` """
    objective             = _internal._subinterfaces.ObjectiveInterface()
    """See `_internal._subinterfaces.ObjectiveInterface()` """
    MIP_starts            = _internal._subinterfaces.MIPStartsInterface()
    """See `_internal._subinterfaces.MIPStartsInterface()` """
    solution              = _internal._subinterfaces.SolutionInterface()
    """See `_internal._subinterfaces.SolutionInterface()` """
    presolve              = _internal._subinterfaces.PresolveInterface()
    """See `_internal._subinterfaces.PresolveInterface()` """
    order                 = _internal._subinterfaces.OrderInterface()
    """See `_internal._subinterfaces.OrderInterface()` """
    conflict              = _internal._subinterfaces.ConflictInterface()
    """See `_internal._subinterfaces.ConflictInterface()` """
    advanced              = _internal._subinterfaces.AdvancedCplexInterface()
    """See `_internal._subinterfaces.AdvancedCplexInterface()` """
    start                 = _internal._subinterfaces.InitialInterface()
    """See `_internal._subinterfaces.InitialInterface()` """
    feasopt               = _internal._subinterfaces.FeasoptInterface()
    """See `_internal._subinterfaces.FeasoptInterface()` """
    parameters            = _internal._parameter_classes.RootParameterGroup(None, None)
    """See `_internal._parameter_classes.RootParameterGroup` """
    long_annotations = _internal._anno.LongAnnotationInterface()
    """See `_internal._anno.LongAnnotationInterface()`"""
    double_annotations = _internal._anno.DoubleAnnotationInterface()
    """See `_internal._anno.DoubleAnnotationInterface()`"""
    pwl_constraints = _internal._pwl.PWLConstraintInterface()
    """See `_internal._pwl.PWLConstraintInterface()`"""
"
has been deleted from line 
"    
problem_type = _internal.ProblemType()
    """See `_internal.ProblemType()` """
" 
to  line 
"
def __init__(self, *args):
"
You can just paste those contents back and the CPLEX solver could be used again.

**Comment by stumitchell** [comment]
Wow that is a really annoying thing to do in a point release :-(

**Comment by rkersh** [comment]
A possible fix is in pull request #134 (see the comments there for the details).

**Comment by Esmeriz** [comment]
@rkersh Could you explain what exactly you mean with changing "the definition of CplexLpStatus into findSolutionValues"?

**Comment by rkersh** [comment]
@Esmeriz: Previously, CplexLpStatus was a class variable. Now, it is a
variable that can only be accessed in the findSolutionValues method. This
seems to be the way it done elsewhere with other Solver adapters.

**Comment by Esmeriz** [comment]
I checked it, thank you very much, now pulp does not crash when importing. However, I cannot pass through the pulp.pulpTestAll(). my CPLYEX_PY keeps failing and when I managed to pass the DLL path, I get "OSError: exception: access violation reading 0x000000002F60A878" at the CPLEX_DLL.CPX_PARAM_MEMORYEMPHASIS. If I comment this line, I get several "access violation errors".
I am using python 3.5.0 64x, pulp 1.6.5 and CPLEX 12.7.1 on Windows 10.

Is there any new version of pulp that adapts to these situations or did I install something wrong concerning cplex?

**Comment by rkersh** [comment]
I'm not an official pulp contributor, so I'm probably not the best person
to answer, but I don't believe the error from CPLEX_DLL has anything to do
with my pull request or this particular issue. It's definitely worth
creating a new issue for this, though, if there isn't one already.

**Comment by stumitchell** [comment]
let me know if this isn't fixed in 1.6.6
