### ISSUE TITLE
PuLP raising IndexError while parsing result when using glpsol with no feasible solution

### ISSUE THREAD

**Issue by kmonson** [coin-or/pulp#132]
I'm getting an error when I run GLPK against a problem with no solution.

Attached is the lp file produced by pulp

[TEST.txt](https://github.com/coin-or/pulp/files/963184/TEST.txt)

Here is the output generated when I run solve(pulp.solvers.GLPK_CMD())
```
GLPSOL: GLPK LP/MIP Solver, v4.61
Parameter(s) specified in the command line:
 --cpxlp C:/Users/kyle/AppData/Local/Temp\7800-pulp.lp -o C:/Users/kyle/AppData/Local/Temp\7800-pulp.sol
Reading problem data from 'C:/Users/kyle/AppData/Local/Temp\7800-pulp.lp'...
816 rows, 768 columns, 2184 non-zeros
168 integer variables, all of which are binary
1669 lines were read
GLPK Integer Optimizer, v4.61
816 rows, 768 columns, 2184 non-zeros
168 integer variables, all of which are binary
Preprocessing...
PROBLEM HAS NO PRIMAL FEASIBLE SOLUTION
Time used:   0.0 secs
Memory used: 0.6 Mb (662068 bytes)
Writing MIP solution to 'C:/Users/kyle/AppData/Local/Temp\7800-pulp.sol'...
Traceback (most recent call last):
  File "main.py", line 115, in <module>
    main(args.config)
 **Non relevant stuff snipped**
  File "C:\econ-dispatch\econ_dispatch\optimizer\use_case_1.py", line 357, in optimize
    prob.solve(pulp.solvers.GLPK_CMD())
  File "c:\econ-dispatch\env\lib\site-packages\pulp\pulp.py", line 1651, in
solve
    status = solver.actualSolve(self, **kwargs)
  File "c:\econ-dispatch\env\lib\site-packages\pulp\solvers.py", line 397, in actualSolve
    lp.status, values = self.readsol(tmpSol)
  File "c:\econ-dispatch\env\lib\site-packages\pulp\solvers.py", line 444, in readsol
    value = float(line[3])
IndexError: list index out of range
```

**Comment by TheoChristiaanse** [comment]
I've had the same error, I used a big M model:
https://math.stackexchange.com/questions/2500415/how-to-write-if-else-statement-in-linear-programming/2501007

Basically, we use a binary variable to make sure we move between a if type statement:


I found that when big M is too small it will give me this error. 
https://orinanobworld.blogspot.com/2018/09/choosing-big-m-values.html

Moving to a larger M I found that this error disappeared.

**Comment by pchtsp** [comment]
Hello, is it the same error?

I see the phrase
PROBLEM HAS NO PRIMAL FEASIBLE SOLUTION

In the log. Which implies there was no solution. We still need to check the problem parsing the file nevertheless. But if this is the case, your problem is infeasible when you change the M size.

**Comment by TheoChristiaanse** [comment]
> Hello, is it the same error?
> 
> I see the phrase
> PROBLEM HAS NO PRIMAL FEASIBLE SOLUTION
> 
> In the log. Which implies there was no solution. We still need to check the problem parsing the file nevertheless. But if this is the case, your problem is infeasible when you change the M size.

You are correct. Maybe the error handling can be improved to not raise the index error, but to make the modeller aware that the problem has not feasible solution more clearly. It seems now that it is buried in the error prompt, and the index error is the main issue?

**Comment by pchtsp** [comment]
Do you have a small reproducible pulp-code example we could run?

That way we can add it to the tests. And also be sure it will be solved.

F.

**Comment by pchtsp** [comment]
I suspect this issue is fixed when we fixed this one https://github.com/coin-or/pulp/issues/287. If not, open another one, please.
