### ISSUE TITLE
Issue while using pulp with gevent

### ISSUE THREAD

**Issue by amit5148** [coin-or/pulp#133]
I am using pulp within a process using gevent.
Intermittently, I am receiving the error from [line 1425 in solvers.py](https://github.com/coin-or/pulp/blob/master/src/pulp/solvers.py#L1425.)
I am assuming that it is caused due to multiple greenlets running concurrently with the same value of tmpSol variable and the greenlet removes the solution file after reading it and causing the error for other greenlets.
I think generating a unique value for tmpSol for individual greenlets should fix the situation.

Am I going the wrong way?
If not, what change would you recommend to fix it?

**Comment by stumitchell** [comment]
let me know if this isn't fixed
