### ISSUE TITLE
Reporting all solutions with Pulp - default CBC solver

### ISSUE THREAD

**Issue by C-Laborde** [coin-or/pulp#135]
Hi,

I am using pulp with the default CBC solver. The program works well meaning that it finds an optimal solution. However, I would like to know if there are other possible solutions and what would be the variables values in that case. Is it possible to do that?

Thanks,

Cecilia

**Comment by stumitchell** [comment]
The answer is both yes and no as it depends on your problem, and what you need those solutions for.

CBC does not provide these solutions like gurobi and cplex can so you will have to generate them yourself.

http://yetanothermathprogrammingconsultant.blogspot.co.nz/2016/01/finding-all-optimal-lp-solutions.html

is a start

**Comment by C-Laborde** [comment]
Hi,

Thanks for your fast reaction. I've been looking for a post like this but didn't run into this one. The reason why I need those solutions for is because I now want to minime (for the same problem and constraints) another objective function f2 together with the previous one f1. This would fall under multiobjective programmimng. However, I am very new to LP and implementing a multiobjetive programming algorithm is impossible for me since I'm running against time. I was thinking that as a shortcut I could choose from all the solutions that minimize f1, the one that minimizes better f2. Is far from perfect, just a zero order approximation...

**Comment by stumitchell** [comment]
hi the best way to do this is

step 1.

min f1

then get the objective z1

then add

f1 <= z1 *1.05 (or whatever you would like)

then 

min f2

This may help you

Stu
