### ISSUE TITLE
CPLEX_DLL access violation

### ISSUE THREAD

**Issue by ramboia** [coin-or/pulp#136]
I recently acquired CPLEX 12.7.1 academic license and was trying to use it on pulp.
Specifications:
- Windows 10
- Python 3.5.0 64bits
- pulp 1.6.5

I executed pulp.pulpTestAll() and achieved the following message:

```
pulp.pulpTestAll()
         Testing zero subtraction
         Testing inconsistant lp solution
         Testing continuous LP solution
         Testing maximize continuous LP solution
         Testing unbounded continuous LP solution
         Testing Long Names
         Testing repeated Names
         Testing zero constraint
         Testing zero objective
         Testing LpVariable (not LpAffineExpression) objective
         Testing Long lines in LP
         Testing LpAffineExpression divide
         Testing MIP solution
         Testing MIP solution with floats in objective
         Testing MIP relaxation
         Testing feasibility problem (no objective)
         Testing an infeasible problem
         Testing an integer infeasible problem
         Testing column based modelling
         Testing dual variables and slacks reporting
         Testing fractional constraints
         Testing elastic constraints (no change)
         Testing elastic constraints (freebound)
         Testing elastic constraints (penalty unchanged)
         Testing elastic constraints (penalty unbounded)
* Solver <class 'pulp.solvers.PULP_CBC_CMD'> passed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python35\lib\site-packages\pulp\pulp.py", line 2280, in pulpTestAll
    if s().available():
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python35\lib\site-packages\pulp\solvers.py", line 617, in __init__
    self.setMemoryEmphasis(emphasizeMemory)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python35\lib\site-packages\pulp\solvers.py", line 665, in setMemoryEmphasis
    CPLEX_DLL.CPX_PARAM_MEMORYEMPHASIS,yesOrNo)
OSError: exception: access violation reading 0xFFFFFFFFAF15BB78
```
What does that error mean and how can I pass through it?

**Comment by pchtsp** [comment]
Hello. I know this is very late but I felt like trying to make CPLEX_DLL work in my pc.
Already configuring CPLEX_DLL in my environment was a bit of hell when trying to tell pulp where the `.so` file was.

When I managed to configure it correctly and pulp found the library correctly, I tried to run the pulp tests. They fail silently with a `SIGSEGV`. Debugging it is another hell on itself: for example, I learned that the CPLEX_DLL object does not like to be called like so `s().available()` but it works with 
```
solver=s()
solver.available()
```
Also, if I run the code it does not work but if I debug it, it does... which is particularly tedious haha.

@stumitchell are we sure we want to maintain CPLEX_DLL given CPLEX_PY and CPLEX_CMD work fine?

Or do you know who could help us make this api work? maybe the original developer? was it you?

**Comment by pchtsp** [comment]
I'm closing this issue for the other one https://github.com/coin-or/pulp/issues/314
