### ISSUE TITLE
[QUESTION] - Incorporating the restricted basis entry rule

### ISSUE THREAD

**Issue by praneethw** [coin-or/pulp#144]
Could you please let me know how to incorporate the restricted basis entry rule (in separable programming) into the simplex method in pulp? That is, we need to make a slight change into the step which selects the basis entries.

More particularly, we need to avoid some of our decision variables coming to the basis.

Thank you.

**Comment by tkralphs** [comment]
This can be done easily in [CyLP](https://github.com/coin-or/cylp), but the way PuLP interfaces with solvers would make it impossible in PuLP, to my knowledge.

**Comment by pchtsp** [comment]
yeah, not possible right now and not in the plans AFAIK.
