### ISSUE TITLE
SafeConfigParser deprecated in favor of ConfigParser

### ISSUE THREAD

**Issue by wkschwartz** [coin-or/pulp#145]
I get the following deprecation warning when I load PuLP.

```
(venv) ~ $ python -Wd
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin...
>>> import pulp
/.../venv/lib/python3.6/site-packages/pulp/solvers.py:71: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  'os':operating_system, 'arch':arch})
```

Maybe related to #124, but probably not.

## Proposed fix

Replace `configparser.SafeConfigParser` in [solvers.py](https://github.com/coin-or/pulp/blob/master/src/pulp/solvers.py#L70) with `configparser.ConfigParser`. My understanding is that the API is the same.

**Comment by Djailla** [comment]
+1 !

**Comment by Djailla** [comment]
Hello @stumitchell, any ETA for a release with this fix ?

Thanks !
