### ISSUE TITLE
Dynamic amount of variables

### ISSUE THREAD

**Issue by nkovalenko-sc** [coin-or/pulp#146]
Do I have possibility to create variables and constraints dynamically? I have a microservice that solves equations, but request data always has different amount of records. How can I create variables and restrictions dynamically?

**Comment by s-c-e** [comment]
Hi - have you checked out this example using `pulp` here?
https://pythonhosted.org/PuLP/CaseStudies/a_blending_problem.html

Taking that example a step further, you could use if-statements or loops to create constraints dynamically, or the number of decision variables could change.

As long as the problem structure/formulation is the same, with a few control statements the problem could expand or contract based on your request data size.

**Comment by pchtsp** [comment]
as @s-c-e said, this is already possible in pulp. Check the provided examples.
