### ISSUE TITLE
CPLEX 12.7.1 - Test fails with _dummy

### ISSUE THREAD

**Issue by bbalegere** [coin-or/pulp#149]
I get this error while running the tests

         Testing zero subtraction
         Testing inconsistant lp solution
         Testing continuous LP solution
         Testing maximize continuous LP solution
         Testing unbounded continuous LP solution
         Testing Long Names
         Testing repeated Names
         Testing zero constraint
'_dummy'
('* Solver', <class pulp.solvers.CPLEX_CMD at 0x000000000281D168>, 'failed.')

I am using Python 2.7.14 x64 with CPELX 12.7.1 x64

**Comment by jeffginger** [comment]
I also have this issue. I am running on a linux machine with python 3.6.5 and cplex 12.8.0.0

**Comment by pchtsp** [comment]
have you tried with recent versions?
Sorry for answering so late.

**Comment by pchtsp** [comment]
I've been testing with CPLEX_CMD at 12.8 and this error does not happen. If you see it again, do open an issue.
