### ISSUE TITLE
Tests for SCIP 

### ISSUE THREAD

**Issue by bbalegere** [coin-or/pulp#150]
Currently, tests for SCIP are not present. I added SCIP_CMD to pulpTestAll, but the test failed with the below error. Does this mean that Pulp does not fully support SCIP ? Is there new buildout required ?

Solver pulp.solvers.YAPOSIB unavailable
         Testing zero subtraction
         Testing inconsistant lp solution
Can't read SCIP solver output: 'no solution available\n'
('* Solver', <class pulp.solvers.SCIP_CMD at 0x0000000002E928E8>, 'failed.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Python27\lib\site-packages\pulp\pulp.py", line 2311, in pulpTestAll
    raise PulpError("Tests Failed")

**Comment by pchtsp** [comment]
We need someone that has SCIP installed to test it and correct it.

**Comment by pchtsp** [comment]
closed by https://github.com/coin-or/pulp/pull/332
