### ISSUE TITLE
Fix failing tests for CPLEX_PY

### ISSUE THREAD

**Issue by bbalegere** [coin-or/pulp#151]
In pulpTest012 and pulpTest123
CPLEX_PY has to be removed from the if condition as it correctly returns as LpStatusUnbounded

This will fix the test failures in CPLEX_PY

**Comment by pchtsp** [comment]
we've done this change already  in the master branch. You can try it if you want by doing:

```
pip install -U git+https://github.com/coin-or/pulp
```
