### ISSUE TITLE
Pulp ignores constraints if infeasible

### ISSUE THREAD

**Issue by zwimer** [coin-or/pulp#157]
### Issue

Pulp will ignore certain constraints if a problem is deemed infeasible without notifying the user.

### Examples

For example, to ignore LpInteger, consider solving:
```
4x + 2y = 3
2x + 4y = 3
```
If this is entered into pulp (code attached) where each variable is constructed via `LpVariable('x',0,1,LpInteger)` , pulp spits back that `x` and `y` are both `0.5`, despite being explicitly told to solve only for integers.

Another example is ignoring upper and lower bounds
```
4x + 2y = 30
2x + 4y = 30
```
Here pulp returns `x` and `y` equal `5.0`. Again, variables are constructed via `LpVariable('x',0,1,LpInteger)`, yet the upper bound of 1 is ignored.

### Code

[break_pulp.py.zip](https://github.com/coin-or/pulp/files/1473304/break_pulp.py.zip)

**Comment by stumitchell** [comment]
Hi your MIP is infeasible I have altered your program so you can see more information

```from pulp import *


# Run a simple pulp program to solve:
#   2x + 4y = 3*factor
#   4x + 2y = 3*factor
def code(factor):

    # Create the problem
    prob = LpProblem("Digital Tomography", LpMinimize)

    # Define variables
    x = LpVariable('x1',0,1,LpInteger);
    y = LpVariable('x2',0,1,LpInteger);

    # Define the constraints
    prob += (   2*x + 4*y == 3*factor   );
    prob += (   4*x + 2*y == 3*factor   );

    # Solve it
    prob.solve(PULP_CBC_CMD(msg=1))
    print LpStatus[prob.status]

    # Extract results
    # Still not sure why, but pulp puts in a dummy variable
    [ dummy, i, k] = prob.variables()

    # Print results and bounds
    print 'Output: <lower bound>,  <  <var value>,  <  <upper bound>'
    print i.lowBound, ' < ', i.varValue, ' < ', i.upBound
    print k.lowBound, ' < ', k.varValue, ' < ', k.upBound
    print

# Ignore integer constraints example
def ignore_integer_constraint():
    print 'Pulp will ignore integer constraints here'
    code(1)

# Ignore bound constraints example
def ignore_bound_constraint():
    print 'Pulp will ignore bound constraints here'
    code(10)

# Don't run on imports
if __name__ == '__main__':
    ignore_integer_constraint()
    ignore_bound_constraint()```

**Comment by zwimer** [comment]
I understand that the problem is infeasible, should pulp not fail at this though? Or print a warning?

**Comment by jacobweiss2305** [comment]
prob = LpProblem('Portfolio optimization', LpMaximize)
prob.solve()

Using prob.solve() it will return 1,0,-1,-3,-3. Where 1 is optimal and -1 is infeasible. Here is the documentation on the flags https://pythonhosted.org/PuLP/constants.html
