### ISSUE TITLE
Difference between adding a named constraint and a general constraint

### ISSUE THREAD

**Issue by SanPen** [coin-or/pulp#159]
Hi, 

I'm in pulp 1.6.8. (The latest at the time of writing this)

I have observed the following:

When I add a restriction like:

`prob += 1*A + 3*B <= 10`

All solves ok.

But when I add

`prob += LpConstraint(1*A + 3*B, rhs=10 , name='ct_1')`

It fails to solve.

Printing the LP filesI have found that the first way of specifying the problem translates properly to the .lp file, but the second one converts the <= restriction to = which is wrong.

**Comment by stumitchell** [comment]
Hi the default arguement for LpConstraint generates an equality constraint

`class LpConstraint(LpAffineExpression):
    """An LP constraint"""
    def __init__(self, e = None, sense = LpConstraintEQ,
                  name = None, rhs = None)`

so

`prob += LpConstraint(1*A + 3*B, sense=LpConstraintLE, rhs=10 , name='ct_1')`

Will do what you want.

**Comment by DZusername** [comment]
What if the constraint were == or >= ?
