### ISSUE TITLE
Enumerate all (multiple) optimal solutions

### ISSUE THREAD

**Issue by bertrand-caron** [coin-or/pulp#161]
Hi,

First of all thanks a lot for Pulp, I am amazed at how powerful and well written its is.

I am working on a Integer Linear Program involving molecular graphs, which is now working. I am now interested in enumerating all optimal solutions of my ILP. I can guarantee that there will be less than a few hundreds so I am not worried about the size of the enumeration. I am using the CBC solver and found some reference to a way to enumerate Multiple Optimal Solutions [1].

Would anyone be kind enough to look into how this could be implemented, or direct me to the relevant section of the code so that I could have a go at it?

Thanks a lot, Bertrand

[1]: https://list.coin-or.org/pipermail/cbc/2012-February/000766.html

**Comment by sergiolucero** [comment]
Give us some code to work with! Your soultion's .__dict__ might be just
what you need to explore.

**Comment by stumitchell** [comment]
This problem is actually more difficult then you think have a look at this blog post for a good explanation

http://yetanothermathprogrammingconsultant.blogspot.co.nz/2016/01/finding-all-optimal-lp-solutions.html

I suggest you use a loop in Pulp to find these solutions.

**Comment by FCYtheFreeman** [comment]
Hi，I ran into this problem recently，is there any way to solve this？ thx
