### ISSUE TITLE
misleading solving status returned in COIN_CMD, GUROBI_CMD and CPLEX_CMD

### ISSUE THREAD

**Issue by pchtsp** [coin-or/pulp#164]
Following [this](https://groups.google.com/forum/#!topic/pulp-or-discuss/hP0eqjyYEDM) google group's entry, I'm creating an issue to remind me to do something about it.

I describe the problem here:

In the case of GUROBI and CPLEX solvers (at least in the `CMD` interface), pulp returns 1 ('optimal') when an integer solution has been found in the time limit.

This is not the behavior I get from the CBC solver, which returns 0.

Since having found an integer solution when the time stops is neither "optimal" nor "not solved", both are at the same time misleading and inconsistent.

One possibility is to at least make all solvers return the same status when finishing in the same status. This would make CBC return 1 instead of 0 when at least one integer solution was found. This is easy to change.

The second, more ambitious possibility, would be to create a new "Integer solution" status in pulp that differentiates from "optimal" and "no solution". This would then be used in the solver interfaces as an additional status to return.

I'll check how the second one could be done.

In case it's hard to implement, would the first one be an acceptable change?

regards,

Franco

**Comment by PabloLeCrapaud** [comment]
I would need a similar implementation. Could you advance on it?
regards
Pablo

**Comment by pchtsp** [comment]
yes, you could just use my fork: https://github.com/pchtsp/pulp-or

There's a pull request pending in the pulp repository but I'm not sure it will be taken into account. It´s been several months since I created it.

cheers,

Franco

**Comment by PabloLeCrapaud** [comment]
Thanks!
But I don't know how to use your fork! :0) 
I mean, i could use it myself, but I don't know how to integrate it in my application which now uses an import of pulp... I'll learn to do so.
Thank you again

**Comment by pchtsp** [comment]
If you're using `pip` to install packages, you can install a package directly from github;

* https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch
* https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

If installed correctly, it should replace the previously pulp installation.

Sometimes you need to force the installation when you already have the library installed (as is your case since you already have pulp). You'd have to use: 

	pip install --upgrade

Like, for example in your case you'd have to do something like the following: 

	pip install --upgrade git+https://github.com/pchtsp/pulp-or.git

Rmember that if you want to go back to the unmodified pulp library you'd have to do:

	pip install --upgrade pulp

**Comment by PabloLeCrapaud** [comment]
Thanks a lot!!

2018-07-08 17:58 GMT+02:00 pchtsp <notifications@github.com>:
