### ISSUE TITLE
GLPK interior point solver

### ISSUE THREAD

**Issue by wangzhixuan** [coin-or/pulp#165]
To whom it may concern, 

For some reason, I have to use the interior point solver(or some one call it barrier method). I know GLPK has one (`glp_interior`). But, I could not find any documentation/example how to specify this method in `PuLP`. 

Is it supported here?
If this particular one is not supported, do we have other interfaces in `PuLP` that can use a non-commercial interior point solver?

Thanks,
Zhixuan

**Comment by stumitchell** [comment]
Hmm I'm not sure if GLPK or CBC solvers support it.

I know the gurobi and CPLEX solvers do.
