### ISSUE TITLE
how to use piecewise linear constraint in pulp?

### ISSUE THREAD

**Issue by pancerZH** [coin-or/pulp#173]
For example, I have one constraints goes:
x + y >=2 or x + y ==2
there are many such constraints in my model, so how to express the **or** in pulp?

**Comment by naveenashwa77** [comment]
import pulp

#define whether you gonna minimize or maximize ur objective 
lp_solve = pulp.LpProblem("My LP Problem", pulp.LpMaximize or pulp.LpMinimize)

#define your variables
x = pulp.LpVariable('x', lowBound=0, cat='Continuous')
y = pulp.LpVariable('y', lowBound=2, cat='Continuous')

# define Objective function
lp_solve += <objective function>

# set your Constraints
lp_solve += (x+y) == 25 - x
lp_solve += (x + y) >= 2

#call solver
lp_solve.solve()
for variable in lp_solve.variables():
    print "{} = {}".format(variable.name, variable.varValue)
    print pulp.value(my_lp_problem.objective)

**Comment by stumitchell** [comment]
your example seems to be strange as x+y >=2 includes x+y == 2 so you only
need the first.

however in general you will need to at binary integer decision variables to
your model to use 'or' constraints

Stu

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by pancerZH** [comment]
Thank you for help but so sorry to find I made a mistake, the constraints should be:
x + y >= 2  or  x + y == 0
I have tried to write them like this:
lp_solve += (x+y)>=2
lp_solve += (x+y)==0
It just did not work(obviously) and no result returned.
And I can't use constraint as lp_solve += (x+y)>=0, because I don't want the (0, 2) part.
Then how to deal with it?

**Comment by stumitchell** [comment]
have a look at this video

https://www.youtube.com/watch?v=-3my1TkyFiM

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by pancerZH** [comment]
Thank you for help! Finally I solved it with nonlinear programming : )
