### ISSUE TITLE
When the variable is more than 10, the solution is wrong.

### ISSUE THREAD

**Issue by FCYtheFreeman** [coin-or/pulp#176]
When the variable is more than 10, the variables in constraints is no longer in order. 
e.g.
5*X11 + 4*X12 + 3*X13 + 2*X14 + 1*X2 + 3*X5 + 2*X6 + 1*X7 + 1*X8 + -5 = 0
I guess this lead to the wrong solution.
I wonder why does this happened，and is there anything I can do to get the right solution？Thank you.

**Comment by s-c-e** [comment]
Hi @FCYtheFreeman - in the example you sent, this should be okay. Since the terms are added together, it shouldn't affect the final solution if things get rearranged. Did you get an unexpected solution?

**Comment by dzhuang** [comment]
Actually, I think the reason is the `prob.variables()` method return the variables in the order by the `str` of the variable name, which lead to `X11` is placed before `X2` in the returned result.
