### ISSUE TITLE
pulp.solvers.PulpSolverError: Pulp: Error while trying to execute /apps/anaconda/envs/py3/lib/python3.6/site-packages/pulp/solverdir/cbc/linux/64/cbc

### ISSUE THREAD

**Issue by jGaboardi** [coin-or/pulp#182]
*content*: Situation, Traceback/output, Math Formulation, Descriptive Formulation, Code, Software

----------------------

**Situation**
- I am building and solving large optimal facility location models with restricted-use census microdata as part of my dissertation.  The biggest troublemaker model is the p-center problem (a.k.a. minimax location-allocation; a mixed integer programming model for location-allocation) – [formulation, description, and code sample below].  I am working in a [restricted data center environment](https://www.census.gov/fsrdc) on a large cluster where memory is not an issue (100s of GB of RAM are readily available).
- The error message is general and does not provide information on what actually broke.  My first thought was that the problem is too large/difficult to solve (which I hope I am wrong…).  I have not been able to reproduce the error, and even getting the traceback approved for disclosure took some finagling
-  Problem size
    - (10,000-row; 15-column) cost matrix
    - 170,001 constraints
    - 150,016 variables
 - unclear error message
    - P=1 (choose 1 candidate facility to minimize the maximum cost) solves in roughly 45 minutes with a minimal memory footprint
    - P=2 (choose 2 candidate facilities) errors out
    - Still trying to work down from p=15
 - Will be trying to solve a much larger problem…
    - (~95,000-row; 15-column) cost matrix
    - 1,615,001 constraints
    - 1,425,016 variables
 - This model is known for being difficult to solve and unpredictable, but generally is more difficult to solve as p decreases from the maximum possible value, but is not 1.

--------------------------

**Traceback/output**
```
****************************************************************************************
=========================================================
			 matrix dims: (10000, 15)
=========================================================
	
	Obj. value:             0.99979419 worst case distance with 1 selected facilities
	build_time (minutes):   0.12501789728800455
        solve_time:             43.2781
	total_time (minutes):   43.40350598891576
	facilities:             ['y0']
	matrix_size (GB):       0.0

----------------------------------------
Traceback (most recent call last):
  File "./p-center_test.py", line 169, in <module>
    pcp = FacilityLocationModel('pcp', cij=cost_matrix, p=p)
  File "./p-center_test.py", line 21, in __init__
    self.solve_time = self.optimize(write_lp=write_lp)
  File "./p-center_test.py", line 33, in timer
    timed_function(*args, **kwargs)
  File "./p-center_test.py", line 103, in optimize
    self.problem.solve(pulp.PULP_CBC_CMD(fracGap=0))
  File "/apps/anaconda/envs/py3/lib/python3.6/site-packages/pulp/pulp.py", line 1664, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/apps/anaconda/envs/py3/lib/python3.6/site-packages/pulp/solvers.py", line 1362, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/apps/anaconda/envs/py3/lib/python3.6/site-packages/pulp/solvers.py", line 1423, in solve_CBC
    self.path)
pulp.solvers.PulpSolverError: Pulp: Error while trying to execute /apps/anaconda/envs/py3/lib/python3.6/site-packages/pulp/solverdir/cbc/linux/64/cbc

----------------------------------------
```

--------------------------

**Mathematical Formulation**

<img width="295" alt="pcenter_formulation" src="https://user-images.githubusercontent.com/8590583/47173533-4827b500-d2dc-11e8-8869-330128cb6aae.png">

**Descriptive Formulation**

<img width="302" alt="pcenter_description" src="https://user-images.githubusercontent.com/8590583/47173550-54137700-d2dc-11e8-82f8-471303b37283.png">

--------------------------

**Code (boiled-down sample in a class)**
```python
import pulp
import numpy as np

class FacilityLocationModel:
    """Solve a facility locatiom optimization model
    
    Parameters 
    ----------
    name : str
        Problem model name; must also be defined as a class method.
    cij : numpy.ndarray
        cost matrix from origins (index of i) to destination (index of j).
        Default is None.
    p : int
        Density of facilities to site. Default is None.
    
    Methods
    -------
    build_pcp : build p-center problem
    problem_instance : create a problem instance
    add_vars : add variables to a model
    add_constrs : add contraints to a model
    add_obj : add an objective function to a model
    optimize : solve a model
    
    Attributes
    ----------
    problem : pulp.pulp.LpProblem
        problem/model instance
    n_cli : int
        total client sites
    r_cli : range
        iterable of client sites
    n_fac : int
        total candidate facility sites
    r_fac : range
        iterable of candidate facility sites
    cli_decisions : list, np.array
        client-to-service decision variable matrix used in pmp and pcp.
    fac_vars : dict
        facility decision variables
    cli_vars : dict
        client decision variables
    W : pulp.pulp.LpVariable
        minimized maximum variable in the p-center problem formulation
    """
    
    
    def __init__(self, name, cij=None, p=None, cli_dvs=None, fac_dvs=None):
        # Set model information
        self.name = name
        
        # Set parameters and indices
        # facility parameter
        self.p = p
        
        # client count and range
        self.cij = cij
        self.n_cli = cij.shape[0]
        self.r_cli = range(self.n_cli)
        
        # facility count and range
        self.n_fac = self.cij.shape[1]
        self.r_fac = range(self.n_fac)
        
        # if client and service decision variable names are passed in the
        # class, set them as attributes here.
        if fac_dvs is not None:
            self.fac_dvs = list(fac_dvs)
        if cli_dvs is not None:
            self.cli_dvs = list(cli_dvs)
        
        # Set decision variables, constraints, and objective function
        try:
            getattr(self, 'build_'+self.name)()
        except:
            raise AttributeError(self.name,
                                 'not a defined location model.')
        # solve
        self.optimize()
    
    
    def build_pcp(self):
        """Integer programming formulation of the p-center Problem.
        
        Originally Published:
            S. L. Hakimi. 1964. Optimum Locations of Switching Centers and
            the Absolute Centers and Medians of a Graph. Operations Research.
            12 (3):450-459.
        
        Adapted from:
            Daskin, M. (1995). Network and discrete location: Models,
            algorithms, and applications. New York: John Wiley and Sons, Inc.
        """
        # Problem Instance
        self.problem_instance()
        # Decision Variables
        self.add_vars()
        # Constraints
        self.add_constrs(constr=2) # assignment constraints
        self.add_constrs(constr=3) # facility constraint
        self.add_constrs(constr=4) # opening constraints
        self.add_constrs(constr=5) # minimized maximum constraints
        # Objective Function
        self.add_obj()
    
    
    def problem_instance(self):
        """Create a problem instance and set objective sense.
        """
        # set sense
        sense = pulp.LpMinimize
        # create problem instance
        self.problem = pulp.LpProblem(self.name, sense)
    
    
    def add_vars(self):
        """Add variables to a model.
        """
        # facility decision variables
        # variable names
        if not hasattr(self, 'fac_dvs'):
            self.fac_dvs = ['y%i' % j for j in self.r_fac]
        # pulp.LpVariable objects
        self.fac_vars = [pulp.LpVariable(var_name, cat='Binary')\
                                            for var_name in self.fac_dvs]
        # add variables
        self.problem.addVariables(v for v in self.fac_vars)
        
        # client decision variables
        # variable names
        if not hasattr(self, 'cli_dvs'):
            self.cli_dvs = ['x%i' % i for i in self.r_cli]
        self.cli_decisions = [['x%i_%i' % (i,j) for j in self.r_fac]\
                                                for i in self.r_cli]\
        # pulp.LpVariable objects
        self.cli_vars = [[pulp.LpVariable(var_name, cat='Binary')\
                                         for var_name in var_row]\
                                         for var_row in self.cli_decisions]
        # add variables
        self.problem.addVariables(var for var_row in self.cli_vars\
                                      for var in var_row)
        
        # minimized maximum variable
        self.W = pulp.LpVariable('W', cat='Continuous')
        self.problem.addVariable(self.W)
    
    
    def add_constrs(self, constr=None):
        """ Add constraints to a model.
        
        (2) assignment constraints
                x1_1 + x1_2 + x1_3 = 1
        (3) facility constraints
                y1 + y2 + y3 = p
        (4) opening constraints
                - x1_1 + y1 >= 0
                - x2_1 + y1 >= 0
                - x3_1 + y1 >= 0
        (5) minimax constraints
                cost1_1*x1_1 + cost1_2*x1_2 + cost1_3*x1_3 - W <= 0
        
        Parameters
        ----------
        constr : int {1, 2, 3, 4, 5, 6}
            Contraint type to add to model. See above for explanation.
            Default is None.
        """
        
        # 2 - assignment constraints
        if constr == 2:
            constrs = [pulp.lpSum(self.cli_vars[i][j]
                                  for j in self.r_fac) == 1\
                                  for i in self.r_cli]
        
        # 3 - facility constraint
        elif constr == 3:
            constrs = [pulp.lpSum(self.fac_vars[j]\
                                  for j in self.r_fac) == self.p]
        
        # 4 - opening constraints
        elif constr == 4:
            constrs = [self.fac_vars[j] >= self.cli_vars[i][j]\
                       for i in self.r_cli for j in self.r_fac]
        
        # 5 - minimax constraints
        elif constr == 5:
            constrs = [pulp.lpSum(self.cij[i,j]\
                                  * self.cli_vars[i][j]
                                  for j in self.r_fac) <= self.W\
                                  for i in self.r_cli]
        
        # Add constraints
        [self.problem.addConstraint(c) for c in constrs]
    
    
    def add_obj(self):
        """ Add an objective function to a model.
        """
        self.problem.setObjective(self.W)
    
    
    def optimize(self, write_lp=None):
        """ Solve the model.
        """
        self.problem.solve(pulp.PULP_CBC_CMD(fracGap=0))


if __name__ == '__main__':
    np.random.seed(0)
    clients, facilities = 5, 3
    p = 2
    # 5 by 3 matrix of small integers
    cost_matrix = np.random.randint(1,5, size=(clients,facilities))
    
    pcp = FacilityLocationModel('pcp', cij=cost_matrix, p=p)
    obj = pcp.problem.objective.value()
    
    print('Worst-case travel cost while siting %s facilities: %s' % (p, obj))
```
```
Worst-case travel cost while siting 2 facilities: 3.0
```
--------------------------

**Software**
- Python 3.6.3
- Pulp 1.6.8
- Numpy 1.15.1
- Red Hat Enterprise Linux 6.10 on PBS Pro cluster

**Comment by stumitchell** [comment]
Thanks for the report,
Can you check if the bundled verision of cbc works with redhat, I can't remember from memory I do know it works on debian based systems,
To fix this I would install cbc from redhat packages and use the COINCMD() solver

**Comment by Iamyang** [comment]
Hi Gaboardi, I met the same problem when using pulp to solve a large optimization problem  with around 6,000 variables.  I am working in a large server where 100s of GB of RAM are readily available. So I consider the memory is not an issue. I googled and found you met the same problem. Have you solved the memory problem with pulp? Thanks.

**Comment by Iamyang** [comment]
@jGaboardi Hi Gaboardi, I met the same problem when using pulp to solve a large optimization problem with around 6,000 variables. I am working in a large server where 100s of GB of RAM are readily available. So I consider the memory is not an issue. I googled and found you met the same problem. Have you solved the memory problem with pulp? Thanks.

**Comment by pchtsp** [comment]
@Iamyang thanks for feedback.

Some options to help diagnose the problem:

1. the could you provide the `.mps` file? it can be generated by pulp using the `writeMPS` method from the problem object.
2. Could you share it here? also try it giving it directly to the cbc solver as input? maybe you get a better error message this way.
3. Alternatively, can you try a newer version of cbc? you can find it in the cbc page (https://github.com/coin-or/cbc).

**Comment by Iamyang** [comment]
@pchtsp  Thanks for the quick response!  I have been struggling with this problem all the day. You made my day! 

- Actually, I am using pulp version 1.6.8  in python 3.7. I guess this is a much new version? When I googled the pulp problem and found there is an open issue here, I just commented without opening another issue related to my specific version. 

- I uploaded the mps file here (https://github.com/Iamyang/transport_upload/blob/master/error_case.mps) just now. Would be appreciated if you could help.

- You mentioned I could try to give the mps file to cbc directly. I am using the default pulp solver and the default solver is cbc, right? Below is my codes.

``` python
def flatten(x):
    return [y for l in x for y in flatten(l)] if type(x) is list else [x]
def flow_assign(costs,link,sta_flow,grid_flow):
    '''
    Parameters
    ----------
    costs: matrix,row:len(sta_flow),col:len(grid_flow)
    link: binary matrix, 1 if sta_flow[i] can be assigned to grid_flow[j] else 0
    sta_flow: station flows, supply side 
    grid_flow: demand side
    '''
    n_grids=len(grid_flow)
    n_stas=len(sta_flow)
    prob = pulp.LpProblem('Assign Problem', sense=pulp.LpMinimize)
    var = [[pulp.LpVariable(f'x{i}{j}', lowBound=0, cat=pulp.LpInteger)  for j in range(n_grids) ] for i in range(n_stas)]
#     objective
    prob += pulp.lpDot(flatten(var), costs)
#     constraints
    for i in range(n_stas):
        prob += (pulp.lpDot(var[i],link[i,:]) == sta_flow[i])
    for j in range(n_grids):
        prob += (pulp.lpSum([var[i][j] for i in range(n_stas) if link[i,j]==1 ]) <= grid_flow[j])
    for i in range(n_stas):
        for j in range(n_grids):
            if link[i,j]==0:
                prob+=(var[i][j]==0)
    try:      
        prob.solve()
    except:
        prob.writeMPS('mps/error_case.mps')
        return None
    return {'objective':pulp.value(prob.objective), 
            'var': [[pulp.value(var[i][j])  for j in range(n_grids)] for i in range(n_stas)]}

```

**Comment by pchtsp** [comment]
Hello again,

Regarding third point, you're right. It's cbc the default solver. By giving it directly I mean running cbc as a command line with the `mps` file as an argument. As an example, assuming a python virtual environment or installation in windows:

    PATH_TO_PYTHON/Lib/site-packages/pulp/solverdir/cbc/win/64/cbc.exe PATH_TO_MPS_FILE/error_case.mps

I tried it with your file and I got the following output from CBC:

    C:\Users\pchtsp\Documents\projects\optima\python\venv\Lib\site-packages\pulp\solverdir\cbc\win\64>cbc "C:\Users\pchtsp\Downloads\error_case.mps"
    Welcome to the CBC MILP Solver
    Version: 2.9.0
    Build Date: Feb 12 2015

    command line - cbc C:\Users\pchtsp\Downloads\error_case.mps (default strategy 1)
    At line 2 NAME          Assign Problem
    At line 3 ROWS
    At line 6210 COLUMNS
    Duplicate row _C945 at line 9521 <     x110      _C945      1.000000000000e+00 >
    Duplicate row _C5711 at line 9522 <     x110      _C5711     1.000000000000e+00 >
    Duplicate row _C946 at line 9560 <     x111      _C946      1.000000000000e+00 >
    Duplicate row _C5712 at line 9561 <     x111      _C5712     1.000000000000e+00 >
    Duplicate row _C1043 at line 9568 <     x1110     _C1043     1.000000000000e+00 >
    Duplicate row _C5721 at line 9569 <     x1110     _C5721     1.000000000000e+00 >
    Duplicate row _C1044 at line 9607 <     x1111     _C1044     1.000000000000e+00 >
    Duplicate row _C5722 at line 9608 <     x1111     _C5722     1.000000000000e+00 >
    Duplicate row _C1045 at line 9645 <     x1112     _C1045     1.000000000000e+00 >
    Duplicate row _C5723 at line 9646 <     x1112     _C5723     1.000000000000e+00 >
    Duplicate row _C1046 at line 9684 <     x1113     _C1046     1.000000000000e+00 >
    Duplicate row _C5724 at line 9685 <     x1113     _C5724     1.000000000000e+00 >
    Duplicate row _C1047 at line 9723 <     x1114     _C1047     1.000000000000e+00 >
    Duplicate row _C5725 at line 9724 <     x1114     _C5725     1.000000000000e+00 >
    Duplicate row _C1048 at line 9762 <     x1115     _C1048     1.000000000000e+00 >
    Duplicate row _C5726 at line 9763 <     x1115     _C5726     1.000000000000e+00 >
    Duplicate row _C1049 at line 9800 <     x1116     _C1049     1.000000000000e+00 >
    Duplicate row _C5727 at line 9801 <     x1116     _C5727     1.000000000000e+00 >
    Duplicate row _C1050 at line 9838 <     x1117     _C1050     1.000000000000e+00 >
    Duplicate row _C5728 at line 9839 <     x1117     _C5728     1.000000000000e+00 >
    Duplicate row _C1051 at line 9876 <     x1118     _C1051     1.000000000000e+00 >
    Duplicate row _C5729 at line 9877 <     x1118     _C5729     1.000000000000e+00 >
    Duplicate row _C1052 at line 9916 <     x1119     _C1052     1.000000000000e+00 >
    Duplicate row _C5730 at line 9917 <     x1119     _C5730     1.000000000000e+00 >
    Duplicate row _C947 at line 9955 <     x112      _C947      1.000000000000e+00 >
    Duplicate row _C5713 at line 9956 <     x112      _C5713     1.000000000000e+00 >
    Duplicate row _C1053 at line 9963 <     x1120     _C1053     1.000000000000e+00 >
    Duplicate row _C5731 at line 9964 <     x1120     _C5731     1.000000000000e+00 >
    Duplicate row _C1054 at line 10001 <     x1121     _C1054     1.000000000000e+00 >
    Duplicate row _C5732 at line 10002 <     x1121     _C5732     1.000000000000e+00 >
    Duplicate row _C1055 at line 10039 <     x1122     _C1055     1.000000000000e+00 >
    Duplicate row _C5733 at line 10040 <     x1122     _C5733     1.000000000000e+00 >
    Duplicate row _C1056 at line 10077 <     x1123     _C1056     1.000000000000e+00 >
    Duplicate row _C5734 at line 10078 <     x1123     _C5734     1.000000000000e+00 >
    Duplicate row _C1057 at line 10115 <     x1124     _C1057     1.000000000000e+00 >
    Duplicate row _C5735 at line 10116 <     x1124     _C5735     1.000000000000e+00 >
    Duplicate row _C1058 at line 10153 <     x1125     _C1058     1.000000000000e+00 >
    Duplicate row _C5736 at line 10154 <     x1125     _C5736     1.000000000000e+00 >
    Duplicate row _C1059 at line 10191 <     x1126     _C1059     1.000000000000e+00 >
    Duplicate row _C5737 at line 10192 <     x1126     _C5737     1.000000000000e+00 >
    Duplicate row _C1060 at line 10229 <     x1127     _C1060     1.000000000000e+00 >
    Duplicate row _C5738 at line 10230 <     x1127     _C5738     1.000000000000e+00 >
    Duplicate row _C1061 at line 10267 <     x1128     _C1061     1.000000000000e+00 >
    Duplicate row _C5739 at line 10268 <     x1128     _C5739     1.000000000000e+00 >
    Duplicate row _C1062 at line 10305 <     x1129     _C1062     1.000000000000e+00 >
    Duplicate row _C5740 at line 10306 <     x1129     _C5740     1.000000000000e+00 >
    Duplicate row _C948 at line 10343 <     x113      _C948      1.000000000000e+00 >
    Duplicate row _C5714 at line 10344 <     x113      _C5714     1.000000000000e+00 >
    Duplicate row _C2 at line 10352 <     x1130     _C2        1.000000000000e+00 >
    Duplicate row _C143 at line 10353 <     x1130     _C143      1.000000000000e+00 >
    Duplicate row _C5741 at line 10354 <     x1130     _C5741     1.000000000000e+00 >
    Duplicate row _C1063 at line 10391 <     x1131     _C1063     1.000000000000e+00 >
    Duplicate row _C5742 at line 10392 <     x1131     _C5742     1.000000000000e+00 >
    Duplicate row _C1064 at line 10429 <     x1132     _C1064     1.000000000000e+00 >
    Duplicate row _C5743 at line 10430 <     x1132     _C5743     1.000000000000e+00 >
    Duplicate row _C1065 at line 10467 <     x1133     _C1065     1.000000000000e+00 >
    Duplicate row _C5744 at line 10468 <     x1133     _C5744     1.000000000000e+00 >
    Duplicate row _C1066 at line 10507 <     x1134     _C1066     1.000000000000e+00 >
    Duplicate row _C5745 at line 10508 <     x1134     _C5745     1.000000000000e+00 >
    Duplicate row _C1067 at line 10545 <     x1135     _C1067     1.000000000000e+00 >
    Duplicate row _C5746 at line 10546 <     x1135     _C5746     1.000000000000e+00 >
    Duplicate row _C1068 at line 10585 <     x1136     _C1068     1.000000000000e+00 >
    Duplicate row _C5747 at line 10586 <     x1136     _C5747     1.000000000000e+00 >
    Duplicate row _C1069 at line 10625 <     x1137     _C1069     1.000000000000e+00 >
    Duplicate row _C5748 at line 10626 <     x1137     _C5748     1.000000000000e+00 >
    Duplicate row _C1070 at line 10665 <     x1138     _C1070     1.000000000000e+00 >
    Duplicate row _C5749 at line 10666 <     x1138     _C5749     1.000000000000e+00 >
    Duplicate row _C1071 at line 10705 <     x1139     _C1071     1.000000000000e+00 >
    Duplicate row _C5750 at line 10706 <     x1139     _C5750     1.000000000000e+00 >
    Duplicate row _C949 at line 10747 <     x114      _C949      1.000000000000e+00 >
    Duplicate row _C5715 at line 10748 <     x114      _C5715     1.000000000000e+00 >
    Duplicate row _C1072 at line 10755 <     x1140     _C1072     1.000000000000e+00 >
    Duplicate row _C5751 at line 10756 <     x1140     _C5751     1.000000000000e+00 >
    Duplicate row _C1073 at line 10794 <     x1141     _C1073     1.000000000000e+00 >
    Duplicate row _C5752 at line 10795 <     x1141     _C5752     1.000000000000e+00 >
    Duplicate row _C1074 at line 10833 <     x1142     _C1074     1.000000000000e+00 >
    Duplicate row _C5753 at line 10834 <     x1142     _C5753     1.000000000000e+00 >
    Duplicate row _C1075 at line 10871 <     x1143     _C1075     1.000000000000e+00 >
    Duplicate row _C5754 at line 10872 <     x1143     _C5754     1.000000000000e+00 >
    Duplicate row _C1076 at line 10910 <     x1144     _C1076     1.000000000000e+00 >
    Duplicate row _C5755 at line 10911 <     x1144     _C5755     1.000000000000e+00 >
    Duplicate row _C1077 at line 10948 <     x1145     _C1077     1.000000000000e+00 >
    Duplicate row _C5756 at line 10949 <     x1145     _C5756     1.000000000000e+00 >
    Duplicate row _C1078 at line 10986 <     x1146     _C1078     1.000000000000e+00 >
    Duplicate row _C5757 at line 10987 <     x1146     _C5757     1.000000000000e+00 >
    Duplicate row _C1079 at line 11024 <     x1147     _C1079     1.000000000000e+00 >
    Duplicate row _C5758 at line 11025 <     x1147     _C5758     1.000000000000e+00 >
    Duplicate row _C1080 at line 11062 <     x1148     _C1080     1.000000000000e+00 >
    Duplicate row _C5759 at line 11063 <     x1148     _C5759     1.000000000000e+00 >
    Duplicate row _C1081 at line 11100 <     x1149     _C1081     1.000000000000e+00 >
    Duplicate row _C5760 at line 11101 <     x1149     _C5760     1.000000000000e+00 >
    Duplicate row _C950 at line 11138 <     x115      _C950      1.000000000000e+00 >
    Duplicate row _C5716 at line 11139 <     x115      _C5716     1.000000000000e+00 >
    Duplicate row _C1082 at line 11146 <     x1150     _C1082     1.000000000000e+00 >
    Duplicate row _C5761 at line 11147 <     x1150     _C5761     1.000000000000e+00 >
    Duplicate row _C1083 at line 11184 <     x1151     _C1083     1.000000000000e+00 >
    Duplicate row _C5762 at line 11185 <     x1151     _C5762     1.000000000000e+00 >
    Duplicate row _C1084 at line 11222 <     x1152     _C1084     1.000000000000e+00 >
    Duplicate row _C5763 at line 11223 <     x1152     _C5763     1.000000000000e+00 >
    At line 25763 RHS
    At line 31969 BOUNDS
    At line 38222 ENDATA
    Problem Assign has 6205 rows, 6152 columns and 6832 elements
    Coin0008I Assign read with 304 errors
    There were 304 errors on input
    Total time (CPU seconds):       0.12   (Wallclock seconds):       0.12

You have constraints that have exactly the same coefficients for every variable, which is apparently problematic for CBC (and in any case, could imply an error in the formulation: you could just take all but one out, for each repetition as they are redundant). As a summary: you need to correct these errors before resending it to cbc again. The variables are defined in the `mps` file (although I would assume it's not obvious what do they mean).

I'm not sure if it would be easy for pulp to detect these errors before giving it to cbc. At least for now, we do not do these checks. Maybe we should save what cbc says in an error file and point the user to the file. Another addition could be to let the user the freedom to write the names equivalences in a file to better understand the variables / constraints that went wrong.

**Comment by Iamyang** [comment]
@pchtsp  Thanks for the detailed instruction. I will correct the errors in my code and test it again.

**Comment by Iamyang** [comment]
@pchtsp  I corrected my codes and all worked well! Thanks a million!

**Comment by MounirBetter** [comment]
l

> @pchtsp I had the same problem, could you tell me how did you fixe it plz ?

**Comment by Iamyang** [comment]
> l
> 
> > @pchtsp I had the same problem, could you tell me how did you fixe it plz ?

I read the mps file by gurobi and find where the error is.

**Comment by totlot-dev-badger** [comment]
Hi, I don't know if I ought to open a new thread but I am facing the same issue.
I get this error in the VS code console: `pulp.solvers.PulpSolverError: Pulp: Error while trying to execute C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pulp\solverdir\cbc\win\32\cbc.exe`


However when I do what @pchtsp says: PATH_TO_PYTHON/Lib/site-packages/pulp/solverdir/cbc/win/64/cbc.exe PATH_TO_MPS_FILE/error_case.mps
it seems to work, no errors come out.

`Welcome to the CBC MILP Solver
Version: 2.9.0
Build Date: Feb 12 2015

command line - cbc.exe C:\Users\User\Opti_ballast.mps (default strategy 1)
At line 2 NAME          Ballast_to_Laden_Optimization
At line 3 ROWS
At line 9038 COLUMNS
At line 9434856 RHS
At line 9443890 BOUNDS
At line 11330861 ENDATA
Problem Ballast_to_Laden_Optimization has 9033 rows, 1886970 columns and 3764907 elements
Coin0008I Ballast_to_Laden_Optimization read with 0 errors
Continuous objective value is 1.99588e+007 - 155.96 seconds`

Thanks if by any chance you can help

**Comment by pchtsp** [comment]
Yes, please. Do open a new issue. Preferably with: a reproducible example in python code or, if impossible, the `mps` file of your problem.
