### ISSUE TITLE
Project not maintained well, looking for co-maintainer

### ISSUE THREAD

**Issue by miek770** [coin-or/pulp#183]
The project doesn't appear to be maintained anymore, based on:

- No commit in the past 11 months;
- PR not being processed, even if they're straightforward;
- Issues not being addressed by the devs.

So, is there and *official* fork of this repo somewhere which is actively maintained and people could contribute to?

Thanks.

**Comment by thomasnield** [comment]
PyOmo still looks to be active
https://github.com/Pyomo/pyomo

Some alternatives and comparisons
https://pyomocontrib-simplemodel.readthedocs.io/en/latest/knapsack.html

**Comment by miek770** [comment]
Thanks for the suggestion, I'll consider it.

**Comment by stumitchell** [comment]
Hi i am still here, just I have less time to work on this now.

I would be happy to accept some help and give access to github and pypi (after a short probation)

Maintainer should only need to spend one day every 3 months to do a much better job than I am currently doing.

The New maintainer will have to fufill the coin-or contributing agreement https://www.coin-or.org/contributing/code/

I'm doing a new release now with the most straight forward pr's added.

In future I will try to deal with Pr's more quickly

**Comment by miek770** [comment]
Great thanks!

**Comment by miek770** [comment]
Sorry, didn't notice you renamed the issue. I'm reopening it to make "looking for co-maintainer" visible for others.

**Comment by tian2992** [comment]
@stumitchell what would you consider valuable work to get started with? Highest priority?

**Comment by stumitchell** [comment]
https://github.com/coin-or/pulp/issues/180

would be a good start

1) only install binaries for the system installed system
2) add an option not to install binaries
3) update the binaries

Stu

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com
