### ISSUE TITLE
log parsing for cplex and gurobi (maybe cbc one day)

### ISSUE THREAD

**Issue by pchtsp** [coin-or/pulp#184]
I'm not aware of any tool for parsing gurobi and cplex logs. I've already some work done in a regex-based parsing object that takes as input a log file and interprets the solution status, solution progress (as a table), the gap, objective function, best bound, solution time, among other things in a way that tries to be solver agnostic in the utilization. 

Not sure if this is something that could be interesting to add to pulp, but in case it's useful, I could try to clean it and include it inside pulp's source via a PR. If not, maybe I could try setting a different package for that.

cheers,

Franco

**Comment by tkralphs** [comment]
You might check out [iPet](https://github.com/GregorCH/ipet), which is a project specifically intended for parsing raw solver log files.

**Comment by pchtsp** [comment]
Thanks! I didn't search enough I see! Definitely will take a look.

We can close this ticket I think. It could be interesting though to name
the project somewhere in pulp's documentation so as to be aware of its
existence.

**Comment by pchtsp** [comment]
After checking it out and trying to use it for some logs... I find it unnecessary complicated and relying on having added annotations inside the logs, which kind of defeats the purpose of having a third-party parser I think. I'm sure it's really complete and well tested, but I prefer a simple library with a simple api. 
Also, it's really strict on file extensions, and I could not get out all of the information from the logs.

I think I'll just finish my own simple, probably worse library and publish as its own repo when I'm done.
