### ISSUE TITLE
More output options

### ISSUE THREAD

**Issue by hsharrison** [coin-or/pulp#188]
I would like to be able to redirect the output or log it. The `msg` param does not allow for this and even temporarily redefining `sys.stdout` does not do anything. Ideally, it would be possible to pass a file descriptor or other writable.

**Comment by s-c-e** [comment]
Hi @hsharrison, how about trying something like the following to redirect the stdout of the solving process? The first snippet should redirect, and the second snippet shows how it would be called "around" the solving process as pulp does its magic :)
```python
import pulp
import os
import sys
from contextlib import contextmanager
```
```python
@contextmanager
def stdout_redirected(to=os.devnull, stdout=None):
    if stdout is None:
        stdout = sys.stdout
    stdout_fd = fileno(stdout)
    with os.fdopen(os.dup(stdout_fd), 'wb') as copied:
        stdout.flush()
        try:
            os.dup2(fileno(to), stdout_fd)
        except ValueError:
            with open(to, 'wb') as to_file:
                os.dup2(to_file.fileno(), stdout_fd)
        try:
            yield stdout
        finally:
            stdout.flush()
            os.dup2(copied.fileno(), stdout_fd)
```
```python
# call solver and capture stdout
with open('thisfile.txt', 'ab') as f, util.stdout_redirected(f):
    prob.solve(pulp.PULP_CBC_CMD(msg=True))
```

**Comment by hsharrison** [comment]
Thanks. Unfortunately I could not get this to work in Jupyter (specifically qtconsole but I imagine the notebook would be weird too). They replace `sys.stdout` with a stream type that doesn't have a file descriptor. So I tried setting `stdout_fd` to 1 in response to an `UnsupportedOperator` error. Then I had a similar problem trying to use a `io.BytesIO` to capture the output, which doesn't have a file descriptor either. I could probably write to a file, then read it back in, but I'm not sure it's worth it.

Instead I just did `GLPK(msg=log.getLevel() == logging.DEBUG)` which doesn't let the output get captured but at least lets me see them or hide them based on my application's verbosity settings.

**Comment by pchtsp** [comment]
I've followed the solution in [SO](https://stackoverflow.com/a/28466329/6508131) and implemented the possibility to give a `logPath` argument in CBC. This redirects the output to the file instead of the screen and should solve this issue. Not in pip yet but can be tested using the master:

```
pip install -U git+https://github.com/coin-or/pulp
```
