### ISSUE TITLE
ImportError: cannot import name sparse

### ISSUE THREAD

**Issue by chrisyoungr** [coin-or/pulp#190]
I saw there was a legacy issue receiving the same error, but it said it was fixed and yet I'm getting it when trying to use PuLP and do a build through cx_Freeze which I've used plenty of times.

Does anyone have ideas as to why I might be facing issues?  I'm still fairly new so troubleshooting something like this has proven quite difficult.

**Comment by pchtsp** [comment]
Can you try with the dev version?

```
pip install -U git+https://github.com/coin-or/pulp
```

**Comment by pchtsp** [comment]
closing because old and no response.
