### ISSUE TITLE
Deprecation warnings in version 1.6.9, will stop working with Python 3.8

### ISSUE THREAD

**Issue by larsblumberg** [coin-or/pulp#192]
Using the current version 1.6.9., py.test spits out the following warning which indicates that PuLP will stop working with the upcoming Python version 3.8:

```
venv/lib/python3.7/site-packages/pulp/pulp.py:1672: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
    self.solutionTime += clock()
```

**Comment by tirkarthi** [comment]
`time.clock` is now removed in 3.8 : https://github.com/python/cpython/pull/13270/
