### ISSUE TITLE
showing results in exact form

### ISSUE THREAD

**Issue by CodLiver** [coin-or/pulp#194]
Hello, 

I try to show my PULP results in Exactform such as 10/3 instead of 3.333333.  is there a way to specify this in pulp's solver?

I use Fraction() of python, but obviously not correct.

thanks

**Comment by stumitchell** [comment]
Sorry no, the underlying solvers in pulp do not support this either,

Stu

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by CodLiver** [comment]
Its okay,  thanks for the fast reply. I just wondered if there was such feature. 

Great library tho. :)
