### ISSUE TITLE
New cbc binaries (2.10)

### ISSUE THREAD

**Issue by fgenoese** [coin-or/pulp#196]
Cbc version 2.10 has been released and it would be great to include the new binaries here. The current version distributed with pulp is roughly 4 years old according to https://github.com/coin-or/pulp/tree/master/src/pulp/solverdir. It is probably version 2.9.

@stumitchell 
Did you build the previous binaries yourself or download from the COIN-OR site?

**Comment by fgenoese** [comment]
@stumitchell
Happy to prepare a commit with the new binaries if you roughly explain how you built them.

Thanks,
Fabio

**Comment by stumitchell** [comment]
Ok great, I got the statically linked binaries from the ampl site, but I think maybe coinor does them now, make sure they are statically linked so there is only one file.

**Comment by tkralphs** [comment]
There are automatically built static binaries for Windows here: https://bintray.com/coin-or/download/Cbc/. I just noticed, though, that there are no binaries for 2.10.1, not sure exactly why. Are you providing binaries for Linux and/or OS X? I guess those are not currently statically linked, although this could be done and perhaps it's better. Please let me know what would be helpful and if anything is breaking, etc.

**Comment by fgenoese** [comment]
The latest stable release is 2.10, so it's OK not to include 2.10.1.

Bintray has no static binaries for OSX/Linux and AMPL has not built them
either. Will contact them.

Il Lun 8 Apr 2019, 19:08 Ted Ralphs <notifications@github.com> ha scritto:

**Comment by stumitchell** [comment]
@tkralphs I have been including statically build binaries for Linux and Mac, Through perhaps it is frowned upon by packaging experts it does make an easy install.

Stu

**Comment by tkralphs** [comment]
For Linux, there are packages for Cbc on both Fedora and Debian. It would also be very easy to make your setup.py go off and download the source and build. On OS X, we have a homebrew recipe. Actually, what would make the most sense is to make a Conda recipe for Cbc. I have that on my TODO list.

For now, if you really want statically linked binaries for Linux and OSX, I can change the automatic builds to make that happen and have them deployed to Bintray. It might take a little work. It would be great if you were getting the binaries from us rather than AMPL.

**Comment by tkralphs** [comment]
Hmm, I have tried a couple of different ways of getting completely static binaries on Linux (all the ways you can easily find by Googling) and have failed. I remember having this problem before, but don't remember any solution. @fgenoese if you know a way to do this within COIN-OR's autoconf setup, that would be helpful.

**Comment by fgenoese** [comment]
I wouldn’t know but we could ask the AMPL guys?

**Comment by stumitchell** [comment]
Yeah sorry Ted I did it once before, but now have forgotten, I'm 80% sure
it was an option to `./configure ` though

Stu

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by tkralphs** [comment]
The AMPL guys use CMake, which seems to have some specific functionality for this. I'm not sure why the recipes that I'm finding don't work, seems like they should from what I'm reading. Will keep probing it.

**Comment by tkralphs** [comment]
Figuring this out is going to take some time. I guess it boils down to figuring out how to either make sure that static versions of all auxiliary libraries are available at compile-time or making sure those libraries are not linked (libz, for example). Someone has recently contributed a full CMake harness for the Cbc stack so one option is to try to replicate what AMPL is doing with CMake. Given that Cbc is available on Debian and Fedora as a standard install, though, is it worth it? I thought I could make this happen easily, but it's requiring a little more time than I have right now.

**Comment by fgenoese** [comment]
Maybe not a priority but more a nice-to-have.

**Comment by rwitzel** [comment]
The Google OR developers support convenient installation of the latest CBC version
* https://github.com/google/or-tools/pull/697 
* https://github.com/google/or-tools/releases

Could one use this approach somehow? Or doing `pip install ortools` and then use their bundled CBC version?

**Comment by fgenoese** [comment]
The guys from AMPL have released the 2.10 binaries (static!) at the usual place:
https://ampl.com/dl/open/cbc/

See here as well:
https://github.com/ampl/coin/issues/13

**Comment by pchtsp** [comment]
@stumitchell at the end were we able to get the statically linked binaries for CBC? Are we going to distribute them outside pulp? I've detected some issues with mip_start in CBC that apparently are already solved in the current version so it would be nice to do the change soon.

**Comment by fgenoese** [comment]
@pchtsp
Current statically linked binaries are from the ampl site. (see earlier comment by @stumitchell )

AMPL site also offers newer version, statically linked (see my previous comment). 

We only would have to include them in the pulp repository.

**Comment by tkralphs** [comment]
I did finally figure out how to get statically linked binaries. It is relatively easy with our new build harness and there are now static binaries for master in [bintray](https://bintray.com/coin-or/download/Cbc/master), so if you want to test with the bleeding edge, you can. Getting static binaries with our old build harness (which is still used by the latest release version) is a bit more involved (see coin-or/Cbc#256 for details). It is my intention to build static binaries in the stable branch as well, but that hasn't happened yet.

**Comment by pchtsp** [comment]
We just updated the cbc binaries in https://github.com/coin-or/pulp/pull/426
