### ISSUE TITLE
Possible bug in pulp/solvers.py

### ISSUE THREAD

**Issue by bernardnguyen** [coin-or/pulp#197]
In the LpSolver_CMD class, executable function (line 338):

```
def executable(command):
        """Checks that the solver command is executable,
        And returns the actual path to it."""

        if os.path.isabs(command):
            if os.path.exists(command) and os.access(command, os.X_OK):
                return command
        for path in os.environ.get("PATH", []).split(os.pathsep):
            new_path = os.path.join(path, command)
            if os.path.exists(new_path) and os.access(new_path, os.X_OK):
                return os.path.join(path, command)
        return False
```

I believe the function should either change the value of self.path, or all future references to executable should assign the variable to its return value. Currently, if the executable exists under a different path in os.environ["PATH"], executable(self.path) returns the new path, but GLPK_CMD does not adjust accordingly.

**Comment by pchtsp** [comment]
Could you provide a specific example where you show what is happening and what you expect / would like to be happening? What is the specific problem or error you're seeing?

This function is shared by all command line solvers so we should be careful in doing any changes.
