### ISSUE TITLE
Assertion error with CBC when run through pulp

### ISSUE THREAD

**Issue by multipitch** [coin-or/pulp#198]
I'm getting the following error when I use my system CBC (coin-or-cbc 2.10.1-1 on Arch Linux x86-64) via PuLP on a particular problem:
``cbc: CglProbing.cpp:614: int CglProbing::tighten(double*, double*, const int*, const double*, const CoinBigIndex*, const CoinBigIndex*, const int*, double*, double*, int, int, char*, int, double): Assertion `colUpper[j]==colLower[j]' failed.``
The problem solves fine using the version of CBC bundled with PuLP (i.e. `pulp.solvers.PULP_CBC_CMD`) but it also solves fine if I output an .lp file using `writeLP` and run the following from the command line:
`cbc myproblem.lp` 
I initially thought it was a bug in CGL (coin-or-cgl 0.60.1-1 on Arch Linux x86-64) or CBC, but since CBC can solve the problem from the command line, I think it might be an issue with PuLP.
The assertion test that's failing was added in a (relatively) recent commit to CGL; [cce4bed](https://github.com/coin-or/Cgl/commit/cce4bed8efa3ab5d2bc2999208bea145f909c75d).

The .lp file is attached below (github is forcing me to rename it *.txt) and it should solve relatively quickly (about 30 seconds on my laptop (Xeon E-2186M, 32GB RAM)).
[myproblem.lp.txt](https://github.com/coin-or/pulp/files/2996803/myproblem.lp.txt)

**Comment by snow-abstraction** [comment]
I am just randomingly looking at pulp issues. My interpretation of the assert is that some variable's upper and lower bound should be exactly the same and this happens in some "tightening" method so bounds might be not be the original ones. 

Does loading the saved file back in pulp also produces the error?

**Comment by pchtsp** [comment]
Can you reproduce the problem if you generate the `mps` file with `writeMPS` from pulp and give it to CBC? I think `pulp` uses that format by default to communicate with CBC.

**Comment by multipitch** [comment]
Unfortunately I haven't kept a record of what code/data I used to create the original problem! Been using pulp plenty since and haven't recently come across the same issue.
