### ISSUE TITLE
Feature request - handling multidimensional decision variables

### ISSUE THREAD

**Issue by multipitch** [coin-or/pulp#199]
I was looking for a scaleable way to handle multidimensional decision variables and came up with the following.
Would something like this be suitable for inclusion to PuLP?
It does require numpy (but any large multidimensional array problem in python is probably using numpy already). Perhaps it's possible to specify numpy as an optional dependency?
I'm very much an amateur, hence this not being a proper pull request!

```
import numpy
import pulp


class LpVariableArray:
    """Multidimensional decision variable array."""

    def __init__(
        self, name, dimensions, low_bound=None, up_bound=None, cat=None, e=None
    ):
        self.name = name
        try:
            iter(dimensions)
            self.dimensions = dimensions
        except TypeError:
            self.dimensions = (dimensions,)
        self.low_bound = low_bound
        self.up_bound = up_bound
        self.cat = cat
        self.e = e
        self.variables = self._build_variables_array()
        self.values = None

    def __getitem__(self, index):
        return self.variables[index]

    def _define_variable(self, *index):
        """Defines an individual decision variable."""
        name = "_".join(map(str, (self.name, *index)))
        return pulp.LpVariable(
            name, self.low_bound, self.up_bound, self.cat, self.e
        )

    def _build_variables_array(self):
        """Builds a multidimensional array of decision variables."""
        vfunc = numpy.vectorize(self._define_variable)
        return numpy.fromfunction(vfunc, self.dimensions, dtype="int")

    def evaluate(self):
        """Evaluates decision variable values."""
        vfunc = numpy.vectorize(lambda i: pulp.value(i))
        self.values = vfunc(self.variables)
```

Variables can be defined as e.g.
```
x = LpVariableArray("x", (1,2,3), 4.56, 7.89, "Continuous")
y = LpVariableArray("y", 100, 1, 10, "Integer") 
z = LpVariableArray("z", (10,10), "Binary") 
```
Multidimensional constraints can be defined e.g.:
```
for n in range(N):
            problem += sum([x[n, p] for p in range(P)]) == 1
```
Once a problem has been solved, values can be calculated as follows:
```
x.evaluate()
```
...and returned as
```
x.values
```
or, e.g.:
```
x.values[1,1,1]
```

**Comment by amarvin** [comment]
How is this different than the current multidimensional decision variables?

**Comment by multipitch** [comment]
I wasn't aware this was currently possible.
Can you give an example how you would initialize e.g. a 3-dimensional variable matrix with dimensions (3, 4, 5), and how you would refer to a specific variable in that matrix when using it in an expression?

**Comment by amarvin** [comment]
The Sudoku model in the documentation has 3-dimensional binary decision variables. https://pythonhosted.org/PuLP/CaseStudies/a_sudoku_problem.html

**Comment by multipitch** [comment]
Apologies - I didn't realise the LpVariable.dicts class method could be used to create multidimensional variables.

**Comment by amarvin** [comment]
No worries! Thanks for getting involved in the repo, and happy optimizing 😄

**Comment by vignesh99** [comment]
Is there a way to use the variable defined using LpVariable.dicts similar to a numpy array? Currently only 1-D vectors/arrays/variables can be defined using this. However, it would be very convenient if the optimization variables were allowed to be multi-dimensional. This would enable the usage of numpy-like operations and write code which is vectorized.

@amarvin @pchtsp if there is a way please let me know.

**Comment by amarvin** [comment]
> Is there a way to use the variable defined using LpVariable.dicts similar to a numpy array? Currently only 1-D vectors/arrays/variables can be defined using this. However, it would be very convenient if the optimization variables were allowed to be multi-dimensional. This would enable the usage of numpy-like operations and write code which is vectorized.
> 
> @amarvin @pchtsp if there is a way please let me know.

Sure, my link from earlier is broken. Here's the updated link with the Sudoku example in `pulp` that has multi-dimensional decision variables defined with `pulp.LpVariable.dicts`:https://coin-or.github.io/pulp/CaseStudies/a_sudoku_problem.html#solution.

Calling individual decision variables is more like a Python dict than `numpy.array`, to enable sparse multi-dimensional decision variables and having the keys of be other data types (e.g. `my_var['set_1_value']['set_2_value']` is more convenient than `my_var[<set_1_index>][<set_2_index>]`.
