### ISSUE TITLE
Can I use python3.6 to work with libCoinMP.so

### ISSUE THREAD

**Issue by TheRoadToSuccess** [coin-or/pulp#204]
I just want to use libCoinMP.so to do LP jobs.  My Python version is 3.6.
but when i run  pulp.pulpTestAll(), there has a error occured.
Error: one character bytes, bytearray or integer expected
Src: 
  File "/usr/lib/python3.6/site-packages/PuLP-1.6.11-py3.6.egg/pulp/solvers.py", line 269, in getCplexStyleArrays
    rowType[i] = senseDict[lp.constraints[c].sense]

cofigure:
1 compile CoinMP
2 modife pulp.cfg.linux

Dose pulp support python3.6? which is the correct python version.

**Comment by pchtsp** [comment]
pulp currently supports python 3.7 -> 3.12
