### ISSUE TITLE
Include pulp as part of another software

### ISSUE THREAD

**Issue by SanPen** [coin-or/pulp#205]
Hi, 

I develop an electrical [calculation program](https://github.com/SanPen/GridCal) that uses pulp.
This is a program that I distribute via pip.

I have done a number of extensions and I'd like to run pulp processes in a much more integrated manner with the software I have. For that I'd modify some of the internals of pulp.

My question is, is it ok to ship a folder with pulp's code as part of the source of my program?

**Comment by stumitchell** [comment]
That is ok just please include the licence files for pulp in that directory

**Comment by SanPen** [comment]
Will do, thanks!
