### ISSUE TITLE
No infeasibility or error with 'False' constraint

### ISSUE THREAD

**Issue by lou-morriet** [coin-or/pulp#207]
Hello,

### **Here is my problem:**
If I add a 'false' constraint (with values and not LpVariables) to my LpProblem, it does not raise any error or consider the problem as infeasible (see the code below).

### **Here is a proposition:**
In the pulp.LpProblem() class,
In the methods __iadd__(self, other), the constraint is considered as "False".
It is neither a LpConstraintVar, a LpConstraint nor a LpAffineExpression BUT it is an INT (as a boolean), which means that the TypeError is not raised. And it changes the objective of the LpProblem.

I would suggest to modify the code in the __iadd__(self, other) methode:
**`elif isinstance(other, LpVariable) or isinstance(other, (int, float)) :`**
to 
**`elif isinstance(other, LpVariable) or (isinstance(other, (int, float)) and not isinstance(other, bool)):`**

Then it raises the TypeError if the constraint is false.

I use Pulp for more complex problems so I can have this kind of 'false' constraint in my problem and whould be happy that it raises an error.

### **Here is my code to test:**
`from pulp import LpProblem, LpMinimize, LpVariable, LpStatus

prob = LpProblem("myProblem", LpMinimize)
prob += 0 - 3 == 0
status = prob.solve()
print(LpStatus[status])`

Output : Optimal

Thank you in advance,
Best regards,
Lou

**Comment by pchtsp** [comment]
Could you make a PR to see how it would look like?

**Comment by pchtsp** [comment]
There's already an 
```
        if other is True:
            return self
```
in line https://github.com/coin-or/pulp/blob/9d3267970f96965247ab0326b632898a7a2355d0/pulp/pulp.py#L1658
that checks for a "True constraint"
we could potentially add an:

```
        if other is False:
            return raise TypeError("A constraint returns a false value")
```
just below that.

**Comment by pchtsp** [comment]
fixed it in https://github.com/coin-or/pulp/commit/d24e3bfb633336c1a3635ce38178eea40a4b8b49
