### ISSUE TITLE
use TMP file in COIN_CMD

### ISSUE THREAD

**Issue by pchtsp** [coin-or/pulp#215]
Hello Stu,

I just came across the fact that the CBC solver does not use the TMP file because of this comment. https://github.com/coin-or/pulp/blob/183dbdff3f6a4e559af8d503752c27c95b0c2a00/src/pulp/solvers.py#L1368

I did the following:

1. Deleted the following two lines.
2. Tested solving using CBC (in windows).
3. Checked that it correctly uses the tmpdir.

What I used for the test:

1. Windows 10.
1. pulp's CBC (it says version 2.9.0).
2. python 3.6.

Should we just take out this three lines? Or is there some other test I should be doing?

**Comment by stumitchell** [comment]
great if that works go ahead.

I hope when github introduces its ci builds we will be able to test on windows and mac.

Have you signed a contribution agreement?
https://www.coin-or.org/contributing/code/

**Comment by tkralphs** [comment]
We are in the beta for Github Actions if you want to give it a go. But you can already currently build on Mac in Travis and on Windows in Appveyor. We are doing this for all projects in the Optimization Suite.

**Comment by stumitchell** [comment]
@tkralphs can you enable this for us?
I would like to start using github actions as my day job is eyeing this up.
would make my job releasing and updating alot easier.

**Comment by tkralphs** [comment]
Just look above next to Pull Requests and it should already be there. It is for me, but maybe I need to enable something if you can't see it.

**Comment by stumitchell** [comment]
@tkralphs I see it great, btw would coin-or be interested in using https://www.clahub.com/ to simplify the signing orf the contribution agreement?

**Comment by tkralphs** [comment]
Actually, clahub looks great. I was already thinking of some kind of template for pull requests that would require agreement before submitting the request, but maybe clahub is easier. Will take a look.
