### ISSUE TITLE
clock() is deprecated

### ISSUE THREAD

**Issue by militsasotirova** [coin-or/pulp#232]
In pulp/pulp.py on lines 1680, 1682, 1712, and 1724 a call to clock() is made. 
time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8

**Comment by Jacob-harris-94** [comment]
Can `time.process_time()` be substituted instead?

**Comment by Jacob-harris-94** [comment]
Addressed (adequately?) in #237

**Comment by militsasotirova** [comment]
Looks good - thanks for your work on this!

**Comment by Jacob-harris-94** [comment]
> 
> 
> Looks good - thanks for your work on this!

haha, wasn't much work, you already identified exactly what the problem was... do you think the conditional import is an issue?

**Comment by militsasotirova** [comment]
Yeah I think it should be fine - the code should be able to run regardless of the version of python being used and I think this is a good way around that.

**Comment by pchtsp** [comment]
I think this is already fixed. Look at: https://github.com/coin-or/pulp/blob/5b80f9dc7f11376d317469d1a6ea31c83b2c9631/pulp/apis/core.py#L35
