### ISSUE TITLE
Hanging on simple infeasible integer problem

### ISSUE THREAD

**Issue by jjstockton** [coin-or/pulp#236]
This code hangs on `solve()`:
```
from pulp import *

a = LpVariable('a', cat=LpInteger)
b = LpVariable('b', cat=LpInteger)

prob = LpProblem()
prob += 2*a + 2*b == 1

prob.solve(solver=PULP_CBC_CMD())
print(prob.status)
```

I'd expect it to print `-1` (i.e. infeasible). As far as I can tell, this is not an issue with CBC, since it runs fine there.

**Comment by MirkoCovizzi** [comment]
If you add a lower bound to both it will give a solution.

**Comment by pchtsp** [comment]
This is related to the solver, not pulp. I'm closing it.
