### ISSUE TITLE
Unexpected wrong solution on very simple problem

### ISSUE THREAD

**Issue by MirkoCovizzi** [coin-or/pulp#238]
Currently on the latest version installable from pip, using default solver.
With this simple problem, I'm getting an infeasible solution that for some reason is still considered optimal by the solver.

```
from pulp import LpProblem, LpMaximize, LpVariable, LpInteger, solvers, value
import math

prob = LpProblem("Pattern", LpMaximize)
max_l1 = math.floor(6000 / 392)
max_l2 = math.floor(6000 / 1347)
x1 = LpVariable("x1", 1, int(max_l1), LpInteger)
x2 = LpVariable("x2", 1, int(max_l2), LpInteger)
prob += 392 * x1 + 1347 * x2 <= 6000
prob += 392 * x1 + 1347 * x2
status = prob.solve()
diff = 6000 - (392 * value(x1) + 1347 * value(x2))
print(value(x1), value(x2), diff)
```

OUTPUT: 5.0 3.0 -1.0

The objective function results in the value 6001 even though the constraint specifies it has to be less than or equal to 6000.
This is the only weird result, after processing about 30000 similar problems.

As far as I can see, it looks like a sort of rounding error on the x1 variable, but I'm not expecting something like that in a problem so simple.

**EDIT:
Updating cbc.exe to latest version solved the issue. 
It would be nice if the latest version of the solver were added to the next release. I see many issues on here that are probably connected to that.**

**Comment by pchtsp** [comment]
Hello,
Yes, indeed. It seems to be a CBC problem. For example if you change the
solver, you get the correct values:

# in case you have any of these available:
mysolver = solvers.PULP_CHOCO_CMD()
mysolver = solvers.GLPK_CMD()
mysolver = solvers.CPLEX_CMD()

status = prob.solve(mysolver)

Then you’ll get the correct answer (a different one, at the very least).
Consider generating an LP file and sending it to the solver github
https://github.com/coin-or/Cbc

**Comment by MirkoCovizzi** [comment]
As I wrote in the edit 4 days ago, the latest CBC solver doesn't have the same rounding error. This led me to research what version of CBC is being shipped with PuLP and with surprise I discovered a 4-5 years old version is being shipped. Why the latest CBC release is not included in each stable PuLP release?

**Comment by pchtsp** [comment]
The thing is, we're aiming on separating the solvers from the modeler into two projects to give more flexibility during deployment. So we don't want to update solvers before that.

**Comment by pchtsp** [comment]
since it's cbc. I'm closing the issue.
