### ISSUE TITLE
How can I write an IF condition for my decision variable for Mixed Integer Linear Programming (MILP) using PuLP GLPK on Python?

### ISSUE THREAD

**Issue by Alizak97** [coin-or/pulp#242]
I am trying to solve an optimization problem using mixed integer linear programming on PuLP with GLPK solver on Python. So far I have been successful solving basic optimization problems with constraints, such as:

`prob = LpProblem("MILP", LpMinimize)`
`x1 = LpVariable("x1",lowBound=0, cat = 'Binary')`
`x2 = LpVariable("x2", cat = 'Continuous')`
`prob += 4*x1 + x2, "Objective Function"`
`prob += x2 - 4*x1 <= 0`
`prob += x2 - 2*x1 >= 0`
`status = prob.solve()`
`LpStatus[status]`
`value(x1), value(x2), value(prob.objective)`

This gives an optimum result where **x1 = 1.0, x2 = 3.0** and **Objective Function = 7.0**

What I'm trying to figure out is how can I solve an optimization problem with an if condition in, for example, the following constraint:
`x1 > 0 IF x2 > 2`

or something like:
`x1 > 0 IF x2 == 3`

Bascially, how can I integrate an if conditional statement into the MILP constraints.

**Comment by pchtsp** [comment]
Hello!

There are many online resources on how to translate logical constraints into linear ones. A couple examples:

* [MIT OCW](https://ocw.mit.edu/courses/sloan-school-of-management/15-053-optimization-methods-in-management-science-spring-2013/lecture-notes/MIT15_053S13_lec11.pdf) 
* [IntegerProgrammingTricks](https://download.aimms.com/aimms/download/manuals/AIMMS3OM_IntegerProgrammingTricks.pdf)

For more help on how to use pulp, please use the [google group](https://groups.google.com/forum/#!forum/pulp-or-discuss) as is more suited for that than the girhub issues page. There, you can also find previous answers to similar questions as it is asked from time to time.

take care!

Franco

**Comment by naveenfaclon** [comment]
how to add 'and' 'or' condition for this

`prob += production_quantity[i, j, t] >= grinding_unit_lower_capacity
            prob += production_quantity[i, j, t] <= grinding_unit_higher_capacity
            prob += (production_quantity[i, j, t] >= grinding_unit_lower_capacity)`
            
            i want to add "and" condition for this
            
            prob += production_quantity[i, j, t] <= grinding_unit_higher_capacity
            prob += (production_quantity[i, j, t] >= grinding_unit_lower_capacity)`
            
            and or condition for 
            prob += (production_quantity[i, j, t]  == 0
            
            but this is not working please help
