### ISSUE TITLE
Python 3.8 ImportError: cannot import name 'clock' from 'time'

### ISSUE THREAD

**Issue by peterberetich** [coin-or/pulp#244]
It seems that time.clock is now deprecated but pulp has not been updated to reflect this change in python 3.8.

Error message:
```
Traceback (most recent call last):
  File "file.py", line 1, in <module>
    import pulp
  File "...\lib\site-packages\pulp\__init__.py", line 34, in <module>
    from .pulp import *
  File "...\lib\site-packages\pulp\pulp.py", line 102, in <module>
    from .solvers import *
  File "...\lib\site-packages\pulp\solvers.py", line 35, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

**Comment by multipitch** [comment]
+1 on this issue - should be re-opened.
Taking the approach used already in `solvers.py` with e.g. `configparser` vs. `ConfigParser`, it would be sufficient to replace:
`from time import clock`
with:
```
try:
    from time import perf_counter as clock
except ImportError:
    from time import clock
```

**Comment by Ye2018** [comment]
instead of importing clock, you should import time. It should be like "from time import time". Then instead of using clock(), you should use time()
