### ISSUE TITLE
Split out Amply into separate repository/Python package

### ISSUE THREAD

**Issue by willu47** [coin-or/pulp#246]
The functionality provided by Amply seems to be orthogonal to that of the PuLP. As far as I can tell, the Amply module is not directly called by any other part of the PuLP code base.

I therefore propose that Amply is split into a separate repository and becomes an independent Python package which can then be imported by PuLP (if it is required). 

Amply does have use - in fact I am making use of it in [otoole](http://github.com/OSeMOSYS/otoole) to read GLPK files (which are written in AMPL dialect).

Splitting out Amply into its own package would enable the further development of Amply to continue in parallel to that of PuLP, and allow more rapid deployment to PyPI etc.

**Comment by pchtsp** [comment]
Would you want to maintain it? If so, you could create a new repo in github and a pypi account. That way, we could reference it from pulp and we just take it out from the codebase.

**Comment by willu47** [comment]
Yes, I could maintain it. Would it need to live in the coin-or organisation, or should I create a new repo under my user?  I will use `git filter-branch` to retain the entire version history relating to the amply file.

**Comment by tkralphs** [comment]
We would welcome this as a separate COIN-OR project and I would hope you would find that beneficial, but it would be up to you. I guess we would need to go through the submission process to get everything set up properly. You could initially move it to your own user and then we could transfer it to coin-or from there.

**Comment by willu47** [comment]
Hi @tkralphs - yes it would be great to become involved in COIN-OR.  I will start working on repository structure under my user and then I can transfer it to COIN-OR once the necessary formalities are completed.

**Comment by willu47** [comment]
I have set up a temporary new repository for amply over on https://github.com/willu47/amply

Lots of work to do still, but will keep it simple (docs in readme); tests + deploy to Pypi using pytest on TravisCI

One important questions - which license should I use? The PULP license appears to be a non-OSI certified license. Should I use the recommended EPL1.0?

**Comment by stumitchell** [comment]
Yeah Pulp had an existing licence from its previous maintainer.

Feel free to transition amply

Stu
Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by pchtsp** [comment]
hey @willu47, did you manage to put amply in pypi so that we can add it as a dependency to pulp and close this issue? thanks!

**Comment by willu47** [comment]
Hi, amply is now available on pypi [here](https://pypi.org/project/amply/): https://pypi.org/project/amply/

**Comment by tkralphs** [comment]
Any interest in having this as a COIN-OR project, as we discussed?

**Comment by willu47** [comment]
Hi @tkralphs - yes. I've been trying to contact the historical developers of Amply to get their assent for change of license to EPL1.0 and contributions forms.  I'll then submit these to COIN-OR for approval.

**Comment by stumitchell** [comment]
did you see my reply

```
Sure,
Also Christophe has passed away (and didn't contribute to this)
and Qlim was my old student at auckland uni and did this work under my
direction

Stu
```

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by willu47** [comment]
Yes, thanks @stumitchell - and I just realised Franco is @pchtsp, so I'll fill in the form and make the submission shortly.

**Comment by tkralphs** [comment]
OK, sounds good, keep me posted.
