### ISSUE TITLE
initial variable value

### ISSUE THREAD

**Issue by teastares** [coin-or/pulp#248]
Is there any approach to set the initial values of variables?

I found two part of codes about initial value.

1. `setInitialValue ` in `LpVariable`, but this method is not implemented.
```
    def setInitialValue(self,val):
        """sets the initial value of the Variable to val
        may of may not be supported by the solver
        """
        raise NotImplementedError
```

2. `setInitial` in `LpProblem`, but I didn't find any other places where self.initialValues are used.
```
    def setInitial(self,values):
        self.initialValues = values
```

**Comment by pchtsp** [comment]
Good day.

In the development version we have mip start working. See this discussion for more information:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pulp-or-discuss/nkEZHLmSt-s/sLRokpBgAQAJ

**Comment by pchtsp** [comment]
I'm closing this since the current version has this already.
More details on how to use it:

http://coin-or.github.io/pulp/guides/how_to_mip_start.html
