### ISSUE TITLE
Optimization method and solver by default Pulp

### ISSUE THREAD

**Issue by pcuevas-ch** [coin-or/pulp#250]
Hi to everyone!

I would like to know which method/solver use Pulp by default to solve linear programming problems.

Thanks in advance.

**Comment by pchtsp** [comment]
Hello, 

pulp comes with two solvers by default: CBC (linear and integer programming) and CHOCO (constraint programming). It connects to many others (GUROBI, CPLEX, SCIP, MIPCL, XPRESS, GLPK) if you have them installed.
