### ISSUE TITLE
Inconsistent solver arguments across solver types, quality of life suggestion

### ISSUE THREAD

**Issue by seangrogan** [coin-or/pulp#260]
Hello,

So I am running my code across computers that may or may not have certain solvers installed.  I created a function to get "best available solver", i.e. this:

    def _get_best_solver():
        solvers = [
        pulp.GUROBI,
        pulp.GUROBI_CMD,
        #etc 
        # solvers in the order of preference
        ]
        for solver in solvers:
            if solver().available():
                print(f"Solver {solver} is available")
                return solver
        assert False, "No solver found"`

    def solve_mip():
        #build model
        solver = _get_best_solver()
        model.solve(solver(msg=True, timelimit=300))

I want to pass a time limit of (say) 300 seconds.  The problem is that the solver class initializers seem to have different methods of assigning a time limit.  E.g. `CPLEX_CMD` has `timelimit`, `GUROBI,` `CPLEX_DLL`,  and `CPLEX_PY` has `timeLimit` (capital L), `XPRESS`, `COIN` has `maxSeconds`.  

I'm not familiar with how to do pull requests, but I'd be willing to help make the changes

**Comment by stumitchell** [comment]
Yes this is annoying, I would love a pull request,

Please make the old arguments still work however maybe with a deprecation
warning.

Stu
Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by pchtsp** [comment]
Maybe it is too ambitious but if you want to make a proposal of a solver
factory, that would be great too.

I attach an example of doing this (making arguments more standard and also
calling a solver with a string) that I use in some projects of mine.

**Comment by tkralphs** [comment]
Attachments get scrubbed when you respond by e-mail. Responding on the issue page itself by clicking on the link in e-mail provides a much better experience and you can attach files easily.

**Comment by pchtsp** [comment]
Thanks @tkralphs I add the files via the web: 
Ok, apparently I cannot attach a file with python extension so here it is in pastebin: https://pastebin.com/783i3Yvm

**Comment by seangrogan** [comment]
Hello!

I made a pull request in line with @stumitchell 's comments

https://github.com/coin-or/pulp/pull/261

**Comment by pchtsp** [comment]
I'm going to close this issue since the changes have been mostly done: timeLimit, gapRel, gapAbs, logPath, warmStart and some more arguments are shared across solvers now. They are all stored in the `LpSolver` under a combination of explicit arguments and keyword arguments that are stored in `self.optionsDict`.
