### ISSUE TITLE
Do you want anything from TRAC/SVN migrated?

### ISSUE THREAD

**Issue by tkralphs** [coin-or/pulp#265]
We are in the tail end of the process of moving all projects that were previously hosted on TRAC and SVN over to github. I suspect there is nothing on the old site that you still want or that should be migrated, but just wanted to check. Is there anything in SVN that is not in the current git repo? Or can we just blow everything away. I guess this is mainly for @stumitchell, but anyone else can chime in.

**Comment by stumitchell** [comment]
Fine for me to blow it away, I don't believe I ever actually used it, maybe
I duplicated from github there but not useful at all now


Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by svigerske** [comment]
I've forbidden creating issues on trac now.\

The /html subdirectory in the svn is uses to host the PuLP documentation at https://www.coin-or.org/PuLP/. So should this documentation actually be removed?

**Comment by pchtsp** [comment]
Hello there,

We are hosting the documentation in github now:
http://coin-or.github.io/pulp/
It’s generated via the gh_pages branch on this repo.

Could it be possible to mirror it to the coin-or site?

Franco

**Comment by svigerske** [comment]
Probably it's possible, but nothing that would need to run on the coin-or webserver will happen quickly.

I've added a redirect to https://coin-or.github.io/pulp/ in https://www.coin-or.org/PuLP/index.html for now.

**Comment by pchtsp** [comment]
Cool thanks. I will close this then.
