### ISSUE TITLE
Solver do not finish - for specific combination of input/numbers

### ISSUE THREAD

**Issue by Prakash19921206** [coin-or/pulp#267]
Details for the issue
--------------------

#### What did you do?
Modified Existing example ([SpongeRollProblem3.py](https://projects.coin-or.org/PuLP/browser/examples/SpongeRollProblem3.py?rev=1)) more info on the same example can be found [here](https://projects.coin-or.org/PuLP/browser/wiki/ACuttingStockProblem.wiki)

#### What did you expect to see?
output from solver

#### What did you see instead?
No error or output  (code keeps running forever with about 50% cpu usage all the time)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 64bit)

#### I'm using python version:
- [x] 3.6

#### I installed PuLP via:
- [x] pypi (pip install pulp)

Useful extra information
-------------------------
Since the standard spongeRollProblem/cuttingStockProblem example comes with single Roll length (inventory/stock)
i modified the example to have multiple Roll lengths.
below is full code
<details> 
  <summary> Click to expand/collapse code </summary>

```
"""
The Full Sponge Roll Problem for the PuLP Modeller

Authors: Antony Phillips, Dr Stuart Mitchell    2007
"""

def calculatePatterns(totalRollLength,lenOpts,head):
    """
     Recursively calculates the list of options lists for a cutting stock problem. The input
     'tlist' is a pointer, and will be the output of the function call.

     The inputs are:
     totalRollLength - the length of the roll
     lenOpts - a list of the sizes of remaining cutting options
     head - the current list that has been passed down though the recusion

     Returns the list of patterns

     Authors: Bojan Blazevic, Dr Stuart Mitchell    2007
    """
    if lenOpts:
        patterns =[]
        #take the first option off lenOpts
        opt = lenOpts[0]
        for rep in range(int(totalRollLength/opt)+1):
            #reduce the length
            l = totalRollLength - rep*opt
            h = head[:]
            h.append(rep)

            patterns.extend(calculatePatterns(l, lenOpts[1:], h))
    else:
        #end of the recursion
        patterns = [head]
    return patterns

def makePatterns(total_patterns,lenOpts):
    """
     Makes the different cutting patterns for a cutting stock problem.

     The inputs are:
     totalRollLength : the length of the roll
     lenOpts: a list of the sizes of cutting options as strings

     Authors: Antony Phillips, Dr Stuart Mitchell    2007
    """

    # calculatePatterns is called to create a list of the feasible cutting options in 'tlist'
    patterns = total_patterns

    # The list 'PatternNames' is created
    PatternNames = []
    for i in range(len(patterns)+len(PatternNames)):
        PatternNames += ["P"+str(i)]

    # The different cutting lengths are printed, and the number of each roll of that length in each
    # pattern is printed below. This is so the user can see what each pattern contains.
    print("Lens: %s" %lenOpts)
    # for name,pattern in zip(PatternNames,patterns):
    #     print(name + "  = %s"%pattern)

    return (PatternNames,patterns)

# Import PuLP modeler functions
from pulp import *

# all different inventory total Roll length is entered
totalRollLength = [7000,6500,6300,5800,5600,5000,4000]

# individual cost respective to above inventory roll length
cost = [4.75,4.625,4.575,4.45,4.4,4.25, 4]


# A list of all the demand roll lengths is created
LenOpts = ["1470","1480","1490", "1500","1510","1520","1530"]

rollDemand = {#Length: Demand 
              "1470":   [45],
              "1480":   [225],
              "1490":   [444],
              "1500":   [136],
              "1510":   [222],
              "1520":   [140],
              "1530":   [46]
}

# The pattern names and the patterns are created as lists, and the associated trim with each pattern
# is created as a dictionary. The inputs are the total roll length and the list (as integers) of
# cutting options.
lenOpts = [int(l) for l in LenOpts]
total_Patterns = []
pattern_and_inventory_len = {}  # dictionary to keep store inventory Roll length and its respective cutting patterns

count = 0
for i in range(len(totalRollLength)):
    total_Patterns += calculatePatterns(totalRollLength[i], lenOpts, [])
    temp_pnames = []
    for j in range(count,len(total_Patterns)):
        temp_pnames += ["P" + str(j)]
    pattern_and_inventory_len[totalRollLength[i]] = temp_pnames
    count += len(pattern_and_inventory_len[totalRollLength[i]])


(PatternNames,patterns) = makePatterns(total_Patterns,lenOpts)

# The pattern data  is made into a dictionary so it can be called by patterns["7"]["P3"] for example.
# This will return the number of rolls of length "7" in pattern "P3"
patterns = makeDict([PatternNames,LenOpts],patterns,0)

# The variable 'prob' is created
prob = LpProblem("Cutting_Stock_Problem",LpMinimize)

# The problem variables of the number of each pattern to make are created
pattVars = LpVariable.dicts("Patt",PatternNames,0,None,LpInteger)


# The objective function is entered: (the total number of large rolls used * the cost of each)
# Note: since we have different inventory Roll lengths, we are multiplying its respective cost to patterns
multi_cost_variable = []
for i in PatternNames:
    for j in range(len(totalRollLength)):
        if i in pattern_and_inventory_len[totalRollLength[j]]:
            multi_cost_variable.append(pattVars[i]*cost[j])

prob += lpSum(multi_cost_variable),"Net_Production_Cost"


# The demand minimum constraint is entered
for j in LenOpts:
    prob += lpSum([pattVars[i] * patterns[i][j] for i in PatternNames]) >= rollDemand[j], "Ensuring_enough_%s_cm_rolls" % j


# The problem data is written to an .lp file
prob.writeLP("SpongeRollProblem.lp")

print("Solving ...")
# The problem is solved using PuLP's choice of Solver
# prob.solve(CHOCO_CMD(keepFiles=1,path="C:\\Python36\\Lib\\site-packages\\pulp\\solverdir\\choco\\choco-parsers-with-dependencies.jar"))
# prob.solve(MIPCL_CMD(path="C:/Practice/Python/pulp_Optimizer/MICPL/mip/bin/mps_mipcl.exe",keepFiles=1))
# prob.solve(PULP_CBC_CMD(keepFiles=1))
prob.solve()
print("Done Solving")

# The status of the solution is printed to the screen
print("Status:", LpStatus[prob.status])

solution_pattern = {}
solution_surplus = {}

# Each of the variables is printed with it's resolved optimum value
for v in prob.variables():
    if v.varValue != 0.0:
        if "Surp" not in v.name:
            temp_name = v.name[6:]
            solution_pattern[temp_name] = v.varValue
            print(v.name, "=", v.varValue)
        elif "Surp" in v.name:
            solution_surplus[v.name] = v.varValue

# The optimised objective function value is printed to the screen
print("Production Costs = ", value(prob.objective))


for key in solution_pattern.keys():
        print("p"+key + "  = %s"%total_Patterns[int(key)])


print("pattern to inventory mapping:\n")
for key in pattern_and_inventory_len.keys():
    print(key,pattern_and_inventory_len[key])
```

</details> 

Note :
------

1. Upon running above code, i don't see any output/error (it keeps running forever)
i tried with `MIPCL_CMD `Solver, its keeps printing some messages for about 8mins before it crashes/stops. its messages are [here](https://pastebin.com/7LgYDEYU)
also tried `CHOCO_CMD `and `PULP_CBC_CMD `solvers, no output from them either. it doesn't crash but i see descent CPU as long as i let it run (checked for about 4 hours)

2. above code works well for most of the demand values (keeping inventory/stock roll length and its cost same).  
some of the value where it work well are:

- >LenOpts = [ "1790", "1880", "1920", "3710", "3800", "3840", "1900", "3520"]<Br> rollDemand = { # Length : Demand <Br> "1790":   [3], "1880":   [1],  "1920":   [38],  "3710":   [3],  "3800":   [1],   "3840":   [17], "1900":   [1],  "3520":   [1] }

- >LenOpts = [ 1900","3520"]<Br> rollDemand = { # Length : Demand <Br>  "1900":   [223],
              "3520":   [223] }

- >LenOpts = [ "2110","2130","3230","3670","3690"]<Br> rollDemand = { # Length : Demand <Br> "2110":   [22],"2130":   [26], "3230":   [27], "3670":   [23], "3690":   [26] }

- >LenOpts = [ "1590", "1600", "1610", "1620", "1630" ]<Br> rollDemand = { # Length : Demand <Br> "1590":   [36],  "1600":   [127],  "1610":   [594],  "1620":   [198], "1630":   [36] }

- >LenOpts = [ "2180","2190","2200","2210","2220","2230" ]<Br> rollDemand = { # Length : Demand <Br> "2180":   [16], "2190":   [58],  "2200":   [8], "2210":   [18],  "2220":   [8], "2230": [2] }

Solver Gets stuck for below value [lp and mps file for this input is attached [here](https://github.com/coin-or/pulp/files/4261387/pulp_Optimizer.zip)]
- >LenOpts = ["1470","1480","1490", "1500","1510","1520","1530"]<Br> rollDemand = { # Length : Demand <Br>   "1470":   [45], "1480":   [225], "1490":   [444], "1500":   [136], "1510":   [222],              "1520":   [140], "1530":   [46] }

seems like solver do not work for combination of specific numbers. because its working for below input (modified above input)
- >LenOpts = ["1470","1480","1490", "1500","1510","1520","1530"]<Br> rollDemand = { # Length : Demand <Br>   "1470":   [45], "1480":   [225], "1490":   [10], "1500":   [136], "1510":   [222],              "1520":   [140], "1530":   [46] }

and does not work for below input (despite below input is lower than above input)
- >LenOpts = ["1470","1480","1490", "1500","1510","1520","1530"]<Br> rollDemand = { # Length : Demand <Br>   "1470":   [45], "1480":   [225], "1490":   [9], "1500":   [136], "1510":   [222],              "1520":   [140], "1530":   [46] }

Thanks & Regards
Prakash

**Comment by pchtsp** [comment]
I have solved the mps file (c0be437d1fd3404498447223ddcdcdf8-pulp.mps) with CPLEX. It loads the problem and solves it, although i had to stop if because it did not find an optimal solution. The fact of it "running forever" is always a possibility.
You should consider using a time limit to the solving phase to stop the solving at a maximum time and get the last current solution if there is one.

**Comment by Prakash19921206** [comment]
@pchtsp, Thanks for your reply.
As posted [here ](https://groups.google.com/forum/#!topic/pulp-or-discuss/W1x0SFbksb0)

i had to pass maxseconds parameter as timeout
`prob.solve(PULP_CBC_CMD(maxSeconds=1000, msg=1, fracGap=0))`

can we set time limit for `MIPCL_CMD `or `CHOCO_CMD `solvers?

**Comment by pchtsp** [comment]
Yes, you can set tmelimit in the solvers but not yet in the standard pulp way. I'll add a PR soon to fix that. In the meantime, you would have to fill the `options` argument for those solvers like this: `[('-tl', timeLimit * 1000)]` for CHOCO_CMD and `['-time ' + str(timeLimit)]` for MIPCL_CMD.

**Comment by Prakash19921206** [comment]
i found couple of other possible bugs which is linked to this issue.
@pchtsp can you please reopen this issue?

i'm using code as mentioned in issue above, below is my input

> LenOpts = ["730", "1160", "710", "770", "1200", "136", "1330", "1350", "1520", "1550", "1570", "1580", "1590", "1600", "1650", "1690"]

> rollDemand = {  # Length Demand
>     "730": [1],  "1160": [24],  "710": [2],  "770": [2],  "1200": [48],  "136": [1],  "1330": [1],  "1350": [1],  "1520": [1],  "1550": [1],  "1570": [2],  "1580": [7],  "1590": [3],  "1600": [7],  "1650": [1],  "1690": [1]
> }

1)  For above input, mps file generated is 127mb
`prob.solve(PULP_CBC_CMD(maxSeconds=1, msg=1, fracGap=0))`
when _maxSeconds=1 then solver status is _Not Solved_  
_maxSeconds=1_ do not work as expected, if mps file size is big
mps file attached can be found [here](https://github.com/coin-or/pulp/files/4607423/big_MPS.zip)
even though it was on ssd drive, i think in 1 second, cbc.exe didn't had enough time to load mps file and solve
if i change maxSeconds to 5, then solver status is Optimal.

2) this issue is linked to first issue, once we set _maxSeconds=5_, cbc.exe had enough time to load and solve (solver status was _Optimal_) but after verifying i noticed that the demand was not equally met, there were some additional demand quantities(surplus) from solver.
In cost function i have not included to have any surplus, so i was expecting the output from solver to be exactly equal to input demand.
I increased maxSeconds to 18000(5 hours), now the output from solver is matching the demand exactly (no surplus was produced) and solver status is _Optimal_.<Br> [Here ](https://pastebin.com/5HQW2Gen)is the entire output from solver running for 5 hours.<Br>I didn't notice any change in solver output after 1 hour <br>
so i changed maxSeconds to 4000 (1.1 hour), now the output from solver matching the demand exactly (no surplus was produced) and solver status is _Optimal_<BR> [Here ](https://pastebin.com/ssixPnPh)is the output from the solver when running for 1.1hour
(I tried with cbc.exe version 2.10.4 yet same results)<Br>
what i noticed is that we need to provide enough maxSecond for cbc.exe to load mps file and return solver status as _Optimal_but how much maxSecond do we need to give so that solver output matches input demand exactly?

Thanks & Regards
Prakash

**Comment by pchtsp** [comment]
Hey Prakash, I appreciate the study you did. For these kinds of questions (this is not a bug) I recommend you go to the mailing list and write it there: https://groups.google.com/forum/#!forum/pulp-or-discuss

Although I also recommend you to investigate a little more on how discrete combinatorial problems work. For most problems there are no time guarantees on optimality.

**Comment by Prakash19921206** [comment]
Ok
Thank you
