### ISSUE TITLE
PULP_CHOCO_CMD() Does not work with Java installed

### ISSUE THREAD

**Issue by julianmukaj** [coin-or/pulp#268]
When we use PULP_CHOCO_CMD() in Windows 10 with latest version of java and JAVA_HOME variables set and the Java.exe added to file path we still get this error:

PuLP: java needs to be installed and accesible in order to use CHOCO_CMD

**Comment by pchtsp** [comment]
if you execute "java.exe" in your command line, does it execute java ?

**Comment by julianmukaj** [comment]
Yes it does.

**Comment by pchtsp** [comment]
Unfortunately, I'm not sure how to debug your issue. For some reason `pulp` is not able to execute `java`. The code to test if we can execute `java` is the following:

```python
    import os
    def executable(command):
        """Checks that the solver command is executable,
        And returns the actual path to it."""

        if os.path.isabs(command):
            if os.path.exists(command) and os.access(command, os.X_OK):
                return command
        for path in os.environ.get("PATH", []).split(os.pathsep):
            new_path = os.path.join(path, command)
            if os.path.exists(new_path) and os.access(new_path, os.X_OK):
                return os.path.join(path, command)
        return False
    command = "java.exe"
    executable(command)
```

If you execute that code from the environment you're running `pulp`, do you get in return the path to java? or you get "False"?

**Comment by pchtsp** [comment]
Hello again, did you fix this? dd you try the code I gave?

**Comment by julianmukaj** [comment]
Hi, I fixed this by modifying executableExtension in core.py, was an issue with my environment I think because only 'java.exe' worked rather than just 'java' even though variables looked good and it worked via cmd (strange?). Choco ended up giving some very bad results however so scrapped this.
