### ISSUE TITLE
Problem when use to mip_start 

### ISSUE THREAD

**Issue by juanpineros** [coin-or/pulp#270]
Community,
I´m doing a Fix and Optimize heuristic and I need to use the initial solution of last solution and fix some variables, my code have something found here how:

for k, v in varsdict.items():
      k.setInitialValue(v) 
      k.fixValue()

In this test I prove that fix all the last solution in each interaction.
               time_limit = 300
                options2 = options=['set mip tolerances mipgap 0.001']
                solver = pulp.CPLEX_CMD(msg=1, timelimit = time_limit, options = options2,mip_start=1)
                prob.solve(solver)

But when the algorithm start this part said mistake:

  File "C:/Users/Admin/Desktop/UFSCAR/PESQUISA/TRABALHO/Modelo Int. propio/PYTHON/H3B-FXOV2ver3.py", line 976, in letura
    prob.solve(solver)

  File "C:\Users\Admin\Anaconda3\lib\site-packages\pulp\pulp.py", line 1713, in solve
    status = solver.actualSolve(self, **kwargs)

  File "C:\Users\Admin\Anaconda3\lib\site-packages\pulp\solvers.py", line 526, in actualSolve
    status, values, reducedCosts, shadowPrices, slacks = self.readsol(tmpSol)

  File "C:\Users\Admin\Anaconda3\lib\site-packages\pulp\solvers.py", line 556, in readsol
    raise PulpSolverError("Unknown status returned by CPLEX: "+statusString)

PulpSolverError: Unknown status returned by CPLEX: time limit exceeded

Thanks for your help.

**Comment by pchtsp** [comment]
I think this just says we are not getting the correct CPLEX status. I don't think this has anything to do with mip_start. What version of CPLEX are you using? Does this happen without mip_start or it runs without problem? Which version of pulp are you using? Is the message inmediate or after the timelimit has passed?

**Comment by juanpineros** [comment]
Thanks Franco for your help,
First, I'm going to answer your questions :
version of CPLEX: 12.8
Does this happen without mip_start or it runs without problem: Only when use mip_start
Which version of pulp are you using: 2.0
Is the message immediate or after the timelimit has passed? After the timelimit

As good news,  I already solved that problem, I will tell you what happened to me:
The problem was in my processor (CPU), since it wasn´t so fast and had a timelimit of 300 for my problem that has more than 60.000 variables and 800.000 restrictions, it couldn´t start in those 300 seconds of time and I had to modify the timelimit for 500 .

Now I am having trouble getting some values ​​from the model solution because CPLEX_CMD creates the log  (cplex.log) and I need  to write some results in Excel.

 I used these lines with CPLEX_PY, after use  solve()
                a = prob.solverModel
                GAP = a.solution.MIP.get_mip_relative_gap ()
                VARIABLE = a.variables.get_num_integer ()
                BestBound = a.solution.MIP.get_best_objective ()

How can I get this information from CPLEX_CMD ?

Thanks, a lot

**Comment by pchtsp** [comment]
Hey, since this is another issue, it's better if you create a new issue. Even better: write to the pulp google group and check for previously answered questions there:

https://groups.google.com/forum/#!forum/pulp-or-discuss

I don't think you have the same fonctionality to get the gap that easily. 

But you can get it from the log the CPLEX generates. In this note, you can check the `orloge` package I did that reads the CPLEX log file and returns many information, including the gap.

https://github.com/pchtsp/orloge
