### ISSUE TITLE
How to change Solver Write Dir: PermissionError: [Errno 13] Permission denied: 'bdbfe1d22131408183e34cda0e68fcf5-pulp.mps'

### ISSUE THREAD

**Issue by cmp1** [coin-or/pulp#272]
Details for the issue
--------------------

#### What did you do?
Attempted to run pulp.solve() in my python jupyter notebook. 

#### What did you expect to see?
Model status 

#### What did you see instead?
Received write directory error 
PermissionError: [Errno 13] Permission denied: '6d66cde97edb4000b7d1463dc7c9faaf-pulp.mps'

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?
Windows 10

#### I'm using python version:

3.7

#### I installed PuLP via:

- [ X] pypi (pip install pulp)

**Comment by pchtsp** [comment]
Weird, that should not happen. Are there any particular configuration you have done?

By default, pulp tries to write in a temp folder in windows by default, maybe you're lacking permissions. 

Try doing the following:

```python
pulp.solve(pulp.PULP_CBC_CMD(keepFiles=True))
```

It will generate the temp files in the directory next to your python files. It may work.

**Comment by cmp1** [comment]
I suspect that is the case - I am receiving below error after running that
particular line>


PermissionError: [Errno 13] Permission denied:
'optimove_washplant_model-pulp.mps'

Is it possible to change the solvers default write path?

**Comment by pchtsp** [comment]
By default, pulp looks for the TEMP, TMP and TMPDIR environment variables (see [here](https://github.com/coin-or/pulp/blob/5b80f9dc7f11376d317469d1a6ea31c83b2c9631/pulp/apis/core.py#L331) for the order) to write the file. If you change any of these before solving, you should be able to choose.

Alternatively, after initiating the solver but before solving you can change the value of `self.tmpDir` to whatever you want:

```
solver = pulp.PULP_CBC_CMD()
solver.tmpDir = 'PUT_SOME_PATH_HERE'
pulp.solve(solver)

```

If you put KeepFiles=True the path is your current path.

Anyway, I think you're issue is with permissions and your jupyter server, not with pulp. The user that runs the notebook has no permissions on the filesystem...

**Comment by cmp1** [comment]
Thank you for your help Franco.

I am now receiving the following error after executing using a local write
path:

Pulp: Error while executing
C:\Users\CPrice2\AppData\Local\Anaconda\anaconda3\lib\site-packages\pulp\solverdir\cbc\win\64\cbc.exe

**Comment by cmp1** [comment]
Code below:


# Instantiate Model
model = LpProblem('plant_model', LpMaximize)

# Solver config
solver = PULP_CBC_CMD()
solver.tmpDir = '/Users/CPrice2/Work/Desktop/pulp/plant_opts/'

# Objective Func
model += lpSum(
    [production[m,w,g] * df.loc[(m,w,g), 'binary_decision_var'
] * df.loc[(m,w,g), 'yield_primary_tonnes'] * fcst_diffs.loc[(m, g), 'price'
] for m, w, g in df.index]
    + [df.loc[m,w,g] * df.loc[(m,w,g), 'binary_decision_var'
] * df.loc[(m,w,g), 'yield_secondary_tonnes'] * fcst_diffs_secondary.loc[m,
'price'] for m, w, g in df.index]
    + [prod_costs[m,w] * costs_df.loc[(m,w), 'total_prod_costs_usd'] for
 m, w in costs_df.index]
)
# Constrain  production to one choice per month
for m, w, g in df.index:
    model += lpSum([production[m,w,g] * df.loc[(m,w,g),
'binary_decision_var'] for m, w, g in df.index]) == 1
# ommitted other constraints for brevity sake
model.solve(solver)
print("Status:", LpStatus[model.status])

**Comment by cmp1** [comment]
Hi Franco,

Just circling back here - do you know what this error, as mentioned above
pertains to please?:

Pulp: Error while executing
C:\Users\CPrice2\AppData\Local\Anaconda\anaconda3\lib\
site-packages\pulp\solverdir\cbc\win\64\cbc.exe

Best,
Chris

**Comment by pchtsp** [comment]
Hey, I need a reproducible example to be able to help you. Something I could run it on my pc.

Alternatively, you should export your problem as a mps file and try to give it to cbc directly to see the error they give.

`model.writeLP(PATH.mps)`

```
C:\Users\CPrice2\AppData\Local\Anaconda\anaconda3\lib\site-packages\pulp\solverdir\cbc\win\64\cbc.exe PATH.mps
```

Otherwise, it will be impossible too help you.

**Comment by pchtsp** [comment]
Also, feel free to write to the pulp mail list, and look at the already answered questions there: 

https://groups.google.com/forum/#!forum/pulp-or-discuss
