### ISSUE TITLE
Receiving UserWarning: Overwriting previously set objective when Adding Constraints

### ISSUE THREAD

**Issue by mtruong1999** [coin-or/pulp#273]
Details for the issue
--------------------

#### What did you do?
Please refer to my StackOverflow post for specifics on exactly what is happening [here](https://stackoverflow.com/questions/60860984/python-pulp-warning-overwriting-previously-set-objective-when-adding-constrain). 
In my sample code when I add constraints using == or >=, I receive the overwriting previous objective warning even though I am not intentionally overwriting an objective. Furthermore, when I use <= I don't receive the warning, but when I print the model I see that the constraints are not being added properly. However, everything seems to work fine when I remove the second inner loop (' for role in roles' in the stackoverflow post).

#### What did you expect to see?
Constraints being added properly

#### What did you see instead?
Overwriting previous objectives warning and

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

Windows 10

#### I'm using python version:

Python 3.6

#### I installed PuLP via:

 pypi (pip install pulp)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [ X] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
This was solved in the SO post.
