### ISSUE TITLE
Pulp LpDot behaviour on list of list wrong (not similar to @ or np.dot)

### ISSUE THREAD

**Issue by manisharora** [coin-or/pulp#275]
i have two vectors of variables and constants, the length is 2000, I am using lpDot and it is taking a fairly large amount of time 2-3 secs.
I have similar results with np.Dot or @, So the problem is with the pulp variable which is leading such large time. I also tired cvxpy the [cvxpy var...] @ [constants] of same length array takes 100 ms. So why in pulp it takes so large time ? What is solution or tip for speedup

**Comment by pchtsp** [comment]
Hello,

I'm indeed interested in speeding up constraint creation in pulp. Do you have an example we could use for how are you doing it in pulp and an example of how it could be improved?

Without a reproducible example, I do not know if you're doing it correctly and we cannot measure the improvements in diffrerent alternatives in pulp.

**Comment by manisharora** [comment]
import numpy as npimport pulp

model = pulp.LpProblem("option optimizer", pulp.LpMaximize)
var = pulp.LpVariable.dicts("f",np.arange(0,10000,1),upBound=50,lowBound = 0,cat=vartype)


var=list(var.values())

constant = [np.arange(0,10000,1),np.arange(0,10000,1)]

lpDot(var,constant)

**Comment by manisharora** [comment]
import numpy as np
import pulp

model = pulp.LpProblem("option optimizer", pulp.LpMaximize)
var = pulp.LpVariable.dicts("f",np.arange(0,10000,1),upBound=50,lowBound = 0,cat=vartype)


var=list(var.values())
constant = [np.arange(0,10000,1),np.arange(0,10000,1)]

lpDot(var,constant) #This is fast but result is wrong using python for loop would be slow

**Comment by manisharora** [comment]
import numpy as np
import pulp

model = pulp.LpProblem("option optimizer", pulp.LpMaximize)
var = pulp.LpVariable.dicts("f",np.arange(0,10000,1),upBound=50,lowBound = 0,cat=vartype)


var=list(var.values())

constant = [np.arange(0,10000,1),np.arange(0,10000,1)]

lpDot(var,constant)

**Comment by manisharora** [comment]
```python
import numpy as np
import pulp

model = pulp.LpProblem("vartest", pulp.LpMaximize)
var = pulp.LpVariable.dicts("f",np.arange(0,10000,1),upBound=50,lowBound = 0,cat=vartype)


var=list(var.values())
constant=np.arange(0,10000,1)

list_of_constant = [constant,constant]

result_0 = lpDot(var,constant) #fast
result_1 = np.dot(var,constant) #slow


result_1 =lpDot(var,list_of_constant) #Wrong result,want avoid for loops as list will be large
result_2= np.dot(var,constant) #right result but very slow

**Comment by manisharora** [comment]
I take back my words about speed as its fairly fast, but lpDot implementation doesn't works for a list of lists like it works on np.Dot  or @

**Comment by pchtsp** [comment]
I actually get an error when runing the last line in your code.

```
result_4= np.dot(var,list_of_constant) #right result but very slow
```
I get:

```
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-5005c15dadbf>", line 1, in <module>
    result_4= np.dot(var,list_of_constant) #right result but very slow
ValueError: shapes (10000,) and (2,10000) not aligned: 10000 (dim 0) != 2 (dim 0)
```

In either case the behavior is not wrong. It's just not what you expeted, I guess? I have no idea what you did expect, though. Feel free to do a PR if you want.
