### ISSUE TITLE
function resolve pulp, improve the time problem build

### ISSUE THREAD

**Issue by juanpineros** [coin-or/pulp#278]
I have to solve a problem several times, every interaction, I fixValue some specific variables with InitialValue. Others remain "free" to optimize them. My problem has a lot of constraints and variables.

Actually I used to solve fuction, but the time to build the problem is very long.

 How can I improve this, resolve function would help me and how is it used, if I have to retype everything or continue with a for and resolve.

**Comment by pchtsp** [comment]
you first need to do a profile on the code to detect what is that takes time. Please write this question to the google group, there are many already answered questions and you can always ask more people there.

https://groups.google.com/forum/#!forum/pulp-or-discuss
