### ISSUE TITLE
problem.addConstraint does not work

### ISSUE THREAD

**Issue by svflocke** [coin-or/pulp#284]
Details for the issue
--------------------

#### What did you do?
Creating simple minimization problem with three variables, one constraint. Adding the constraint using `problem.addConstraint(...)` adds something, but not the constraint which consists of just adding some variables and constants. Using `problem += ...` works.

#### What did you expect to see?
Same behaviour for both, especially, as `addConstraint` is used in quite a lot of tutorials.

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [x] 3.6
- [ ] Other: ___

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

[pulptest.zip](https://github.com/coin-or/pulp/files/4462749/pulptest.zip)

**Comment by pchtsp** [comment]
hello!

thanks for taking the time to create the issue. As you say, there is already ```problem += ... ``` that works. In fact, `problem.addConstraint` is a function that achieves the same goal, only differently. So, as you may expect, they do not have the same syntax.

All `pulp` docs (available [here](https://coin-or.github.io/pulp/)) do not make reference to `addConstraint` as far as I know. If they did, it would be with the correct input format. In fact, the official documentation does not even make reference to that function.

Please tell me if there is any official tutorial that is incorrect so we can fix it. 

Otherwise, I will close this issue, since the function does work.

**Comment by svflocke** [comment]
Hi,

thanks for the fast feedback. I found the tutorial - it is not an official one, but from OPEX/Llamasoft, therefore my guess was that they know what they are talking about. Maybe they do.

Though I know now that addConstraint is nothing official, I'm fine with closing the issue.

[OPEX tutorial on Medium](https://medium.com/opex-analytics/optimization-modeling-in-python-pulp-gurobi-and-cplex-83a62129807a)

Thanks again!

**Comment by svflocke** [comment]
Another comment after a second thinking. Syntax was not the problem. Adding the same Constraint using both ways leads to different representations in the solver. Only in the official Syntax the right hand side of the expression is evaluated.

Though Opex uses the inofficial Syntax (as I did myself up to yesterday), this seems to work in some/many cases. So maybe you are interested in exactly this case (see zip file in the issue),which shows different behavior.

**Comment by pchtsp** [comment]
I just saw your file. I haven't tested it but I think that the `rhs` argument in the `LpConstraint` declaration should be a parameter (not a pulp expression). That's the issue with builing the constraint manually: you are not filling the arguments as pulp expects.

If you wante to make it work you should do:

```
c = plp.LpConstraint(
    e=y - x1 - x2,
    sense=plp.LpConstraintGE,
    name="c",
    rhs= 1
)
```
But again, you're safer just using the official docs and methods (which are more intuitive).
