### ISSUE TITLE
Fail to read a solution from GLPK where its status is integer empty

### ISSUE THREAD

**Issue by hysok2** [coin-or/pulp#287]
Hello,

I found that pulp fails to read a .sol file from GLPK when the status in the .sol file is INTEGER EMPTY.  Here is the code that reproduces the error. [test.py.txt](https://github.com/coin-or/pulp/files/4569332/test.py.txt)

I think that the problem was that pulp did not treat the .sol file as a solution of MILP while actually it was MILP.  To fix the problem, I believe [isInteger](https://github.com/coin-or/pulp/blob/master/pulp/apis/glpk_api.py#L117) should be true when the status in the .sol file is INTEGER EMPTY.  That is, [the list](https://github.com/coin-or/pulp/blob/master/pulp/apis/glpk_api.py#L117)  should include "INTEGER EMPTY".  

Best,

#### I'm opening this issue because:

- [x] PuLP has a bug
- [ ] PuLP needs a feature
- [ ] PuLP has another problem

#### I'm using PuLP on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: ubuntu 18.04LTS)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [x] 3.6
- [ ] Other: ___

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [ ] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Thanks for the issue.

I'm able to reproduce the issue.

I'm not sure your solution will work, though. Because the solution is indeed infeasible (and `isInteger` means a solution exists).

I'll check it further and add it as a test for the unittests when it's solved

**Comment by pchtsp** [comment]
You were right about adding the element to the list. I did not understand the meaning of `isInteger`. In fact it meant the problem was integer. Thanks again!
