### ISSUE TITLE
Error after reporting objective function

### ISSUE THREAD

**Issue by hadipanahikbslp** [coin-or/pulp#290]
I am using pulp/cbc/ python 3.7 and getting std_alloc error after solver reports an objective function value, I have 32GB RAM, any suggestion is highly appreciated (besides increasing memory or reformulation, lol ). I am not sure why memory usage increases after the optimal solution is found, maybe there is sort of post-processing in pulp or cbc after finding the optimal solution?

l (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6797281 COLUMNS
At line 39147787 RHS
At line 45945064 BOUNDS
At line 47922004 ENDATA
Problem MODEL has 6797276 rows, 1976933 columns and 30374092 elements
Coin0008I MODEL read with 0 errors
Continuous objective value is 0 - 2762.59 seconds
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "newmodelcall.py", line 119, in <module>
    optmodel.model.solve(solver)
  File "/home/ec2-user/anaconda3/envs/py37/lib/python3.7/site-packages/pulp/pulp.py", line 1686, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/ec2-user/anaconda3/envs/py37/lib/python3.7/site-packages/pulp/apis/coin_api.py", line 71, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/home/ec2-user/anaconda3/envs/py37/lib/python3.7/site-packages/pulp/apis/coin_api.py", line 141, in solve_CBC
    self.path)
pulp.apis.core.PulpSolverError: Pulp: Error while trying to execute /home/ec2-user/anaconda3/envs/py37/lib/python3.7/site-packages/pulp/apis/../solverdir/cbc/linux/64/cbc

**Comment by pchtsp** [comment]
I'm guessing the problem is a MIP, not an LP. It appears to be very big
from the cbc log.

Cbc has only found a continuous solution, not a solution to the problem,
assuming it's a MIP and not an LP. It's probably starting the cutting
phase, which probably is where it breaks.

There's nothing weird, you have a big mip problem, it can be impossible for
cbc to handle the cutting or the branching or whatever it's using to find
an integer solution.

**Comment by hadipanahikbslp** [comment]
thanks for your response, I'm new to CBC and interpreting the logs and I was assuming it has already found the answer to the MIP, so that value is really the relaxed root node, thanks, I think this issue can be closed.
