### ISSUE TITLE
Constraint pi attribute not working with Gurobi 9.0.1

### ISSUE THREAD

**Issue by torressa** [coin-or/pulp#296]
Details for the issue
--------------------

#### What did you do?
Was trying to extract the `pi` attribute from constraints while using the gurobi solver and kept getting `None`. I wasn't sure if it was gurobi's fault so I ran your unit tests (`pulp/tests/test_pulp.py`).
After commenting the try-except statement (to see the actual error message)

https://github.com/coin-or/pulp/blob/ca9b3941a82c4433d7e1a17bd785df07d09d8948/pulp/apis/gurobi_api.py#L114-L118

I get the following error message in a number of tests:
```
gurobipy.GurobiError: Unable to retrieve attribute 'Pi'
```

I think it might be related to the `GRB.Attr.{attribute}` syntax not being used. But realised you guys use it in other places.

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( distro: ubuntu )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [X] Other: 3.8

#### I installed PuLP via:

- [ ] pypi (pip install pulp)
- [X] github
- [ ] Other: ___

#### Did you also

- [X] Tried out the latest github version: https://github.com/coin-or/pulp
- [X] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
I think this is related to this PR: https://github.com/coin-or/pulp/pull/202
I never tested and I wanted a test to add to the set that tests this correctly. It would be nice to take all those try/ except clauses from the GUROBI interface. 

Ideally, we would not need them if we just skip that part if there is no solution.
