### ISSUE TITLE
Contribution paperwork

### ISSUE THREAD

**Issue by tkralphs** [coin-or/pulp#297]
@stumitchell @pchtsp We have been lax in enforcing our IP and licensing requirements since moving to Github (which has been many years for PuLP). In SVN, we had pretty tight control over who could commit, but it is now possible to accept PRs from people who don't have write access. Just to remind you, our contribution guidelines are documented [here](https://www.coin-or.org/contributing/code/) and [here](https://projects.coin-or.org/CoinTLC/attachment/wiki/WikiStart/contribproc.pdf?format=raw) (the project management guidelines are a little out of date now, with the move to Github). 

The important part is that any significant/substantial contribution should be accompanied by a signed [Contributor's Statement of Respect for Ownership](https://www.coin-or.org/management/forms/csro.pdf). To make this process completely digital and to ease the burden of requesting contributors to sign such paperwork, we are planning to implement an automated system similar to that used by many bigger open source projects. Basically, anyone submitting a PR will automatically be asked to digitally sign a CSRO (this process will be quick and painless) if they haven't already done so). 

Given that PuLP is so active, I was hoping to use you as a beta test for the new system. The plan at the moment is to use the system developed by SAP and also used by Microsoft itself, as described here:

https://github.com/cla-assistant/cla-assistant 

If you agree, I will activate this for your project and we can see how it works. Ideally, I would also ask that you do your best to get your house in order regarding this paperwork. At the very least, the primary maintainers/developers should all have paperwork on file. Ideally, those who have contributed substantial chunks of code should be asked to sign retroactively (if anyone refuses, we will have to figure out what to do about that). 

Let me know what you think!

**Comment by pchtsp** [comment]
Good day!

Yes, I also do think this is a good idea. Do we have to do anything to
configure it? Or we just need to sign it when you make it available in PuLP
and make previous contributors sign it?

That reminds me we need to add some kind of contributors guidelines for
PuLP. Is there any example in coin-or for contributor's guide for the
python language we could copy / reuse?

thanks!

**Comment by tkralphs** [comment]
OK, I have enabled it now. Take a look at #298 to see what the workflow looks like.

**Comment by tkralphs** [comment]
By the way, it seems to have checked all open PRs and added requests for signing to those.

**Comment by pchtsp** [comment]
haha yes I got many mails from the cla-assistant. I just signed the last PR. It appears to work perfectly! I'm going to close this issue, then. @tkralphs do you want me to accept your test PR?

**Comment by tkralphs** [comment]
My test PR did have some real edits, so I think you can accept it if you agree. Thanks!
