### ISSUE TITLE
Cplex api not revoming tmp files

### ISSUE THREAD

**Issue by gus0k** [coin-or/pulp#302]
Details for the issue
--------------------

#### What did you do?

I solved a linear programming problem using cplex

#### What did you expect to see?

All temporary files deleted after the program closed.

#### What did you see instead?

Files with the extension uuid4()-pulp.lp where not being deleted correctly.

Useful extra information
-------------------------

The problem seems to be in line 79 of: 

`pulp/pulp/apis/cplex_api.py`

tmpMst appares twice.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X ] Linux: (debian 10)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [X] 3.6
- [ ] Other: ___

#### I installed PuLP via:

- [X] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [ ] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
thanks for the issue. I was pretty sure I had solved this some commits ago but apparently not. I found it in another branch, I'll make a PR: https://github.com/coin-or/pulp/pull/303
