### ISSUE TITLE
amply does not support python 3.3

### ISSUE THREAD

**Issue by pchtsp** [coin-or/pulp#304]
Hey @stumitchell how important do you think it is to support python 3.3? it's already deprecated. And the new amply project does not support python 3.3 (see: https://github.com/willu47/amply/issues/3)

It's only being tested in Travis (not in github actions). I think we can take that test out. At some point I guess we will have to drop support for python 2.7 too...

So, do you agree on taking out support for python 3.3?

**Comment by stumitchell** [comment]
Yeah we can get rid of 3.3

We should only drop support for 2.7 when we have a reason to I guess (i.e.
not do it just to clean up code)

Stu

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com
