### ISSUE TITLE
Divisibility Support for Integer Programming 

### ISSUE THREAD

**Issue by foohyfooh** [coin-or/pulp#318]
Describe the new feature
--------------------------
divisibility support for integer programming problems.
Eg.
```python
model += (x % 4 == 0, 'X multiple of 4')
model += (x % 8 != 0, 'X not a multiple of 8')
```

**Comment by stumitchell** [comment]
Best to use

X==4n

Where in is an integer variable.

In general not all constraints can be added as general logic constraints
make the problem non linear.

**Comment by foohyfooh** [comment]
Thanks @stumitchell . I had completely forgotten that I could do that.
Not sure if I should close the issue, because I would still like if the library could handle the divisibility constraints by creating the extra variables for a user.

**Comment by stumitchell** [comment]
hmm, will await your pr.
