### ISSUE TITLE
Fix makeDict incorrectly generating defaultdict

### ISSUE THREAD

**Issue by matheusMoreno** [coin-or/pulp#320]
Hi, everyone. I'm learning optimization with PuLP and was trying to have a better understanding on how `makeDict()` behaves. Looking at the current code on `utilities.py`, I noticed that a defaultdict is generated only if `default is None`, as stated by the line below:

https://github.com/coin-or/pulp/blob/864bd98efdea5cc9bfc8d6b7300e319d2f174400/pulp/utilities.py#L159

I copied the `__makeDict()` and `makeDict()` definitions from the file and tested a little bit, noticing that the results were "switched" when compared with the current implementation (that I installed from conda), such that, when `default=None`, I was recieving a defaultdict, and when `default` was anything else, I was recieving the built-in dict type.

The statement should be `if not default is None`, right? Or am I missing something?

**Comment by pchtsp** [comment]
You're right. I actually do not know /use this part of the codebase but it probably was me how reformatted this function and a previous version had  `if default != None:` and now it has `if default is None:`. Do you have by chance an example I can add to the tests in `tests/test_pulp.py` to be sure this does not happen again ? or even, better, would you like to add one yourself ?

thanks again!

**Comment by matheusMoreno** [comment]
Just created the pull request; please check if everything is ok, and let me know if I can improve something!
