### ISSUE TITLE
Incorrect results using PuLP 2.3

### ISSUE THREAD

**Issue by NMVRodrigues** [coin-or/pulp#327]
Python version 3.7.7

PuLP  2.3 is achieving incorrect results on simple problems.

Here is a link to a problem and its correct simplex solution: http://simplex.tode.cz/en/wql6czm8gz1

Here is the formulation and solution obtained when using PuLP to solve this same problem:

input:
```
prob2 = p.LpProblem('ex_b', p.LpMaximize)

x1 = p.LpVariable("x1", lowBound = 0) 
x2 = p.LpVariable("x2", lowBound = 0) 
x3 = p.LpVariable("x3", lowBound = 0) 

prob2 += 1*x1 - 2*x2 + 1*x3   
  
# Constraints: 
prob2 += 1*x1 + 1*x2 + 1*x3 <= 12
prob2 += 2*x1 + 1*x2 - 1*x3 <= 6
prob2 += -1*x1 + 3*x2  <= 9

status = prob2.solve()
print(p.LpStatus[status])
for var in (x1,x2,x3):
    print('Optimal number of {} to produce is: {:1.0f}'
          .format(var.name, var.value()))
print('Optimal value: ', p.value(prob2.objective))
```

output:
```
Optimal
Optimal number of x1 is: 0
Optimal number of x2 is: 0
Optimal number of x3 is: 12
Optimal value:  12.0
```

**Comment by tkralphs** [comment]
The solution [0, 0, 12] is also optimal, so the result is correct.

**Comment by nicolas15000** [comment]
Hey guys, I wonder if people would like to collab with me on my vue python pulp starter , doing some pulp full stack  apps ? It just started, but my plan is to user drag and drop later ! https://github.com/nicolas15000/vue-python-data-science-starter

**Comment by pchtsp** [comment]
@NMVRodrigues I'm closing because of @tkralphs response. @nicolas15000 please write to the google group: https://groups.google.com/forum/?nomobile=true#!forum/pulp-or-discuss
