### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by MLopez-Ibanez** [coin-or/pulp#328]
Details for the issue
--------------------

#### What did you do?

Search for 'allcombinations' in https://coin-or.github.io/pulp/search.html?q=allcombinations&check_keywords=yes&area=default

#### What did you expect to see?

The first result points to https://coin-or.github.io/pulp/technical/pulpundefined?highlight=allcombinations#pulp.allcombinations

which is 404

#### What did you see instead?

It should point to https://coin-or.github.io/pulp/technical/pulp.html?highlight=allcombinations#pulp.allcombinations

**Comment by pchtsp** [comment]
Well spotted. I have no idea why the docs did not create correctly with Sphinx. If you know why and make a pull request I can check on that.

thanks.

**Comment by pchtsp** [comment]
this is fixed with the new automatic deployment of docs! :  )
