### ISSUE TITLE
Deprecation warning "time.clock has been deprecated in Python 3.7 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead"

### ISSUE THREAD

**Issue by kahemker** [coin-or/pulp#329]
Details for the issue
--------------------

#### What did you do?
When you run the PuLP solver with Python version 3.7, there is a deprecation warning message related to time.clock

#### What did you expect to see?
No warning messages when successfully building a problem and running the solver

#### What did you see instead?
Deprecation warning "time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead"

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ Windows 10 Enterprise )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.7

#### I installed PuLP via:

- [ ] pypi (pip install pulp)
- [ ] github
- [x] Other: conda

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Thanks for the issue.
I think we already cover for that. In apis/core.py we have the following:

```
try:
    from time import process_time as clock
except ImportError:
    from time import clock
```
not sure if we should be doing anything else?
Or maybe the warning comes from somewhere else?  how did you install it on conda?  what version of PuLP are you using ?

```
import pulp
print(pulp.__version__)
# '2.3'
```

**Comment by kahemker** [comment]
Huh, I'm on version 1.6.8.  I guess you guys aren't pushing new version to the Anaconda Cloud.  I updated versions and everything is fine.  Sorry to bother.  Thanks for the help.

**Comment by jGaboardi** [comment]
see also conda-forge/pulp-feedstock#4

**Comment by pchtsp** [comment]
I've created an issue to update the conda forge repository. I'm closing this one.
