### ISSUE TITLE
Printing subprocess output of CBC and GUROBI solvers in IPython cell

### ISSUE THREAD

**Issue by AlfaimaSB** [coin-or/pulp#333]
Details for the issue
--------------------

#### What did you do?

I tried to print the CBC and GUROBI log in IPython cells but it was not possible even with the msg argument turned on in the PULP_CBC_CMD and GUROBI_CMD functions. The output shows in the terminal if I run the script there but not in any IPython environment (Jupyter Notebook or Spyder). I tried all the suggestions in stackoverflow but nothing worked for me. 

BUT I came up with a solution. Please read further. 

I already forked the project, created a new branch and made all the adjustments. These work in my pc, I provided a simple test in the test script. I will submit a pull request that fixes this small and significant issue ✨😊

#### What did you expect to see?

Gurobi or CBC solver log when turning on msg argument 

#### What did you see instead?

No log in IPython cell. this is really important for me because I am a teacher and I need to show my students the logs. 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 Home Single Language)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.7

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ x] github
- [ ] Other: ___

#### Did you also

- [x] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Hello, the changes in the PR are somwehat deep and I'm not 100% sure they will not break something. Those solvers already provide writing to a logfile via the `logPath` argument. Couldn't you just read the file à la `tail -f` from python ?
