### ISSUE TITLE
time.clock deprecated in 3.8

### ISSUE THREAD

**Issue by vsoch** [coin-or/pulp#337]
Details for the issue
--------------------

#### What did you do?

Try to use the library with Python 3.8+

#### What did you expect to see?

Clean import / functionality

#### What did you see instead?

time.clock is deprecated for 3.8+, see error traceback https://github.com/snakemake/snakemake/issues/617 also reported https://github.com/PyTables/PyTables/issues/744

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Ubuntu 18.04)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.8

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by dtrodrigues** [comment]
This isn't an issue in the latest PuLP, the traceback is from software using PuLP 1.6.8

**Comment by vsoch** [comment]
Ah, fantastic! I’ll see if we can update to the latest then. Thanks for the speedy reply!
