### ISSUE TITLE
Raise Error when a variable named 'b' is present for solver GLPK_CMD

### ISSUE THREAD

**Issue by pchtsp** [coin-or/pulp#341]
Details for the issue
--------------------

#### What did you do?
Use a variable with the name 'b' with the solver GLPK_CMD

#### What did you expect to see?
the solution

#### What did you see instead?
a pulp error

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [ ] Other: ___

#### I installed PuLP via:

- [ ] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [ ] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
this is motivated by:

https://github.com/coin-or/pulp/pull/336

which was fixed in the docs but still can be an issue.

```
import pulp as pl
model = pl.LpProblem("Example", pl.LpMinimize)
solver = pl.GLPK_CMD()
_var = pl.LpVariable('a')
_var2 = pl.LpVariable('b')
model += _var + _var2 == 1
result = model.solve(solver)
```

**Comment by MLopez-Ibanez** [comment]
https://github.com/coin-or/pulp/blob/19a310da9ffb15a14e8acdb55462c5562689b325/pulp/mps_lp.py#L361

Adding an empty space before each constraint should fix it, no?
```python
f.write(" %s\n" % v.asCplexLpVariable())
```

So that the LP looks like:

```
\* Example *\
Minimize
OBJ: __dummy
Subject To
_C1: a + b = 1
Bounds
 __dummy = 0
 a free
 b free
End
```

**Comment by MLopez-Ibanez** [comment]
Fails also with 'E', 'G', 'End' so this is a general problem of writeLP. Adding the space fixes it.

**Comment by MLopez-Ibanez** [comment]
And the same should be done for any line that starts with an identifier.
