### ISSUE TITLE
Minor inconsistency in `list_solvers()` arguments in documentation

### ISSUE THREAD

**Issue by thedorathanasiadis** [coin-or/pulp#343]
#### Details for the issue
On the documentation of version 2.3 on section [How to configure a solver in PuLP](https://coin-or.github.io/pulp/guides/how_to_configure_solvers.html#how-to-configure-a-solver-in-pulp) it mentions that to list only the available solvers the `only_available=True` argument must be passed in `list_solvers()`. 

However, in the documentation example below the description the method is called as `list_solvers(available_only=True)`. 
Finally, in the function implementation the expected keyword argument is: `onlyAvailable`.

#### What did you do?
Called `list_solvers(available_only=True)` and since that failed called `list_solvers(only_available=True)`

#### What did you expect to see?
List of all the available solvers.

#### What did you see instead?
TypeError for unexpected keyword argument in `list_solvers()`

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Ubuntu 20.04.1 LTS)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [X] Other: 3.7.6

#### I installed PuLP via:

- [ ] pypi (pip install pulp)
- [ ] github
- [X] Other: conda install

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [X] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

#### Note: If this is indeed an issue, I could pick it up for implementation.

**Comment by pchtsp** [comment]
Thanks for the report. You're right. In fact, now that I think about it, I should normalize the function names to `getSolver`, `listSolvers`, `getSolverFromJson`, etc following the pulp's format. 

Feel free to do the changes to all those function names and the docs in a PR.

**Comment by thedorathanasiadis** [comment]
My pleasure. Sorry I didn't find the time to actually pick this up. 

> Thanks for the report. You're right. In fact, now that I think about it, I should normalize the function names to `getSolver`, `listSolvers`, `getSolverFromJson`, etc following the pulp's format.
> 
> Feel free to do the changes to all those function names and the docs in a PR.
