### ISSUE TITLE
timeLimit not working with SCIP

### ISSUE THREAD

**Issue by Guzzii** [coin-or/pulp#348]
What is your question
-----------------------
SCIP doesn't respect timeLimit. I tried two approaches. Below it is how I used it
```python
import pulp

# problem setup skipped
...

# approach 1 (not working)
prob.sovle(pulp.apis.SCIP_CMD(path='/path/to/scip binary', timeLimit=300))

# approach 2 (not working either)
prob.sovle(pulp.apis.SCIP_CMD(path='/path/to/scip binary', options=['-c', 'set limits time 300']))
```
I was able to get cbc working correctly with approach 1. But neither worked for SCIP. Is this the right way of setting it? Any comments will be appreciated!

**Comment by pchtsp** [comment]
The first approach would be ideal but it's not yet implemented. 

The second approach is probably the right approach but, a guess, it does not work is a result of a bug in the SCIP api in pulp that adds the user options after SCIP has exited. I do not have SCIP installed so I cannot test this. 

I will try to install SCIP this week. If I manage to install it and reproduce this bug I can 1) solve it and 2) implement the first approach now that you mentioned the way to add a timelimit.
