### ISSUE TITLE
diagnostic reporting appears to have made it's way to production

### ISSUE THREAD

**Issue by matecsaj** [coin-or/pulp#351]
Details for the issue
--------------------

An undesired play-by-play of the CBC algorithm prints to the console during the second balance_stoichiometry call in the next section's sample code. Debugging led me to suspect line 137 of **coin_api.py**; it reads as follows:

cmds += "printingOptions all "

#### What did you do?

#!/usr/bin/python3

from chempy import balance_stoichiometry
from pprint import pprint

reactants, products = balance_stoichiometry({'C', 'O2'}, {'CO2', 'CO'})
pprint(dict(reactants))
pprint(dict(products))

print('\n=====VVVVV WHAT IS THIS STUFF IN THE CONSOLE? VVVVVV=====\n')
reactants, products = balance_stoichiometry({'C', 'O2'}, {'CO2', 'CO'}, underdetermined=None)
print('\n=====^^^^ WHAT IS THIS STUFF IN THE CONSOLE? ^^^^=====\n')
pprint(dict(reactants))
pprint(dict(products))

#### What did you expect to see?

/usr/local/bin/python3.8 "/Users/matecsaj/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_3.py"
{'C': x1 + 1, 'O2': x1 + 1/2}
{'CO': 1, 'CO2': x1}

=====VVVVV WHAT IS THIS STUFF IN THE CONSOLE? VVVVVV=====

=====^^^^ WHAT IS THIS STUFF IN THE CONSOLE? ^^^^=====

{'C': 3, 'O2': 2}
{'CO': 2, 'CO2': 1}

Process finished with exit code 0

#### What did you see instead?

/usr/local/bin/python3.8 "/Users/matecsaj/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_3.py"
{'C': x1 + 1, 'O2': x1 + 1/2}
{'CO': 1, 'CO2': x1}

=====VVVVV WHAT IS THIS STUFF IN THE CONSOLE? VVVVVV=====

Welcome to the CBC MILP Solver 
Version: 2.9.0 
Build Date: Feb 12 2015 

command line - /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc /var/folders/n_/s1fp3wyj7w354v5dq_jx6p600000gn/T/bcfa6b10a14346dbbea8070b638fbe33-pulp.mps ratio None allow None threads None presolve on strong None gomory on knapsack on probing on branch printingOptions all solution /var/folders/n_/s1fp3wyj7w354v5dq_jx6p600000gn/T/bcfa6b10a14346dbbea8070b638fbe33-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 26 RHS
At line 29 BOUNDS
At line 34 ENDATA
Problem MODEL has 2 rows, 4 columns and 6 elements
Coin0008I MODEL read with 0 errors
String of None is illegal for double parameter ratioGap value remains 0
String of None is illegal for double parameter allowableGap value remains 0
String of None is illegal for integer parameter threads value remains 0
String of None is illegal for integer parameter strongBranching value remains 5
Option for gomoryCuts changed from ifmove to on
Option for knapsackCuts changed from ifmove to on
Continuous objective value is 5.5 - 0.00 seconds
Cgl0003I 0 fixed, 3 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 1 rows, 3 columns (3 integer (0 of which binary)) and 3 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0012I Integer solution of 8 found by DiveCoefficient after 0 iterations and 0 nodes (0.00 seconds)
Cbc0031I 1 added rows had average density of 1
Cbc0013I At root node, 1 cuts changed objective from 7 to 8 in 3 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 1 column cuts (1 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 1 row cuts average 1.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is 1000
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0001I Search completed - best objective 8, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 7 to 8
Probing was tried 3 times and created 1 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 3 times and created 1 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                8.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.01

=====^^^^ WHAT IS THIS STUFF IN THE CONSOLE? ^^^^=====

{'C': 3, 'O2': 2}
{'CO': 2, 'CO2': 1}

Process finished with exit code 0

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ X] Mac OS: ( _version: 10.15.7 )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [X] Other: ___ 3.8.3

#### I installed PuLP via:

- [ ] pypi (pip install pulp)
- [ ] github
- [X] Other: ___ (pip3 install chempy)(your package is also installed because it is a dependency)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [X] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

Per the following, I'm using version 2.3 of PuLP. 

pip3 list
Package                Version
---------------------- -----------
absl-py                0.9.0
amply                  0.1.4
appnope                0.1.0
argon2-cffi            20.1.0
arrow                  0.16.0
asgiref                3.2.10
astunparse             1.6.3
async-generator        1.10
attrs                  20.2.0
backcall               0.2.0
binaryornot            0.4.4
bleach                 3.2.1
cachetools             4.1.0
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
chempy                 0.7.12
click                  7.1.2
cookiecutter           1.7.2
cycler                 0.10.0
decorator              4.4.2
defusedxml             0.6.0
Django                 3.0.8
docutils               0.16
dot2tex                2.11.3
ebaysdk                2.2.0
entrypoints            0.3
gast                   0.3.3
google-auth            1.16.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.29.0
h5py                   2.10.0
idna                   2.9
ipykernel              5.3.4
ipython                7.18.1
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.17.2
Jinja2                 2.11.2
jinja2-time            0.2.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.6.3
jupyterlab-pygments    0.1.2
Keras-Preprocessing    1.1.2
kiwisolver             1.2.0
lxml                   4.5.1
Markdown               3.2.2
MarkupSafe             1.1.1
matplotlib             3.3.2
mistune                0.8.4
mpmath                 1.1.0
nbclient               0.5.0
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.1
notebook               6.1.4
numpy                  1.18.5
oauthlib               3.1.0
opt-einsum             3.2.1
packaging              20.4
pandocfilters          1.4.2
parso                  0.7.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.0.0
pip                    20.2.3
poyo                   0.5.0
prometheus-client      0.8.0
prompt-toolkit         3.0.8
protobuf               3.12.2
psycopg2-binary        2.8.6
ptyprocess             0.6.0
PuLP                   2.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.7.1
pyneqsys               0.5.6
pyodesys               0.13.1
pyparsing              2.4.7
pyrsistent             0.17.3
python-dateutil        2.8.1
python-slugify         4.0.1
pytz                   2020.1
PyYAML                 5.3.1
pyzmq                  19.0.2
qtconsole              4.7.7
QtPy                   1.9.0
quantities             0.12.4
requests               2.23.0
requests-oauthlib      1.3.0
rsa                    4.0
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             41.2.0
six                    1.15.0
sqlparse               0.3.1
sym                    0.3.4
sympy                  1.6.2
tensorboard            2.2.2
tensorboard-plugin-wit 1.6.0.post3
tensorflow             2.2.0
tensorflow-estimator   2.2.0
termcolor              1.1.0
terminado              0.9.1
testpath               0.4.4
text-unidecode         1.3
tornado                6.0.4
traitlets              5.0.4
urllib3                1.25.9
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.34.2
widgetsnbextension     3.5.1
wrapt                  1.12.1

**Comment by pchtsp** [comment]
as the PuLP documentation shows https://coin-or.github.io/pulp/technical/solvers.html#pulp.apis.COIN_CMD

you need to pass the `msg=False` argument in order to hide the CBC log. In any case, this is not a diagnostic log. It's the progress log for the CBC solver. 

I guess this change has to be done in the `chempy` library.

**Comment by matecsaj** [comment]
Franco, thanks for considering the problem and providing insight.  I am endeavouring to contribute a PR to the chempy project. 

In the following chempy function, when prob.solve() runs, the progress log appears in the console. 

def _solve_balancing_ilp_pulp(A):
    import pulp
    x = [pulp.LpVariable('x%d' % i, lowBound=1, cat='Integer') for i in range(A.shape[1])]
    prob = pulp.LpProblem("chempy_balancing_problem", pulp.LpMinimize)
    prob += reduce(add, x)
    for expr in [pulp.lpSum([x[i]*e for i, e in enumerate(row)]) for row in A.tolist()]:
        prob += expr == 0
    prob.solve()
    return [pulp.value(_) for _ in x]

After reading what appeared to be relevant parts of the docs and googling for examples, I tried progressively desperate things.

prob.solve(msg=False)
prob.solve({msg=False})
prob.solve(COIN_CMD(msg=False))
prob.solve(pulp.LpMinimize(msg=False))
prob.solve(pulp.LpMinimize, msg=False)
prob = pulp.LpProblem("chempy_balancing_problem", pulp.LpMinimize, msg=False)
prob = pulp.LpProblem("chempy_balancing_problem", pulp.LpMinimize(msg=False))
x = [pulp.LpVariable('x%d' % i, lowBound=1, cat='Integer', msg=False) for i in range(A.shape[1])]

And all of them crashed, the result of the first attempt follows.

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/matecsaj/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_3.py", line 9, in <module>
    reactants, products = balance_stoichiometry({'C', 'O2'}, {'CO2', 'CO'}, underdetermined=None)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chempy/chemistry.py", line 1354, in balance_stoichiometry
    sol = Tuple(*[Integer(x) for x in _solve_balancing_ilp_pulp(A)])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chempy/chemistry.py", line 1148, in _solve_balancing_ilp_pulp
    prob.solve(msg=False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pulp/pulp.py", line 1890, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pulp/apis/coin_api.py", line 101, in actualSolve
    return self.solve_CBC(lp, **kwargs)
TypeError: solve_CBC() got an unexpected keyword argument 'msg'

Please excuse my nativity. Where and how should I add msg=False?

**Comment by pchtsp** [comment]
Hello! you were close, though.

you need to do:

```python
prob.solve(pulp.PULP_CBC_CMD(msg=False))
```

**Comment by matecsaj** [comment]
Thanks again, Franco. That worked perfectly so I made a PR https://github.com/bjodah/chempy/pull/183.
