### ISSUE TITLE
A bug for overflow problem, when coefficient is big?

### ISSUE THREAD

**Issue by nwpucong** [coin-or/pulp#354]
Details for the issue
--------------------
import pulp
prob=pulp.LpProblem("Mtest",pulp.LpMinimize)

s1_0_1 = pulp.LpVariable("s1_0_1",1,8,pulp.LpInteger)
s2_0_1 = pulp.LpVariable("s2_0_1",1,8,pulp.LpInteger)

M=100000000.0
#M=1000

epsilon_1_2 = pulp.LpVariable("epsilon_1_2",0,1,pulp.LpInteger)
epsilon_2_1 = pulp.LpVariable("epsilon_2_1",0,1,pulp.LpInteger)

prob += s2_0_1 - s1_0_1 - M * (epsilon_1_2-1)>= 1
prob += s2_0_1 - s1_0_1 - M * epsilon_1_2 <= 0
prob += s1_0_1 - s2_0_1 - M * (epsilon_2_1-1)>= 1
prob += s1_0_1 - s2_0_1 - M * epsilon_2_1 <= 0

K = pulp.LpVariable("K",1,8,pulp.LpInteger)

prob += K >= s1_0_1
prob += K >= s2_0_1
prob += K - 1 

prob += s1_0_1 + 1 <= s2_0_1

prob.solve()

print(pulp.LpStatus[prob.status])
print (pulp.value(s1_0_1),pulp.value(s2_0_1),pulp.value(epsilon_1_2),pulp.value(epsilon_2_1))
print (pulp.value(prob.objective))

#### What did you do?
When set M=1000, we get correct answer, but when set M=100000000.0, the result shows Infeasible. I guess this is overflow problem?

#### What did you expect to see?
Optimal
1.0 2.0 1.0 0.0
1.0
#### What did you see instead?
Infeasible
1.0 2.0 1e-08 0.0
1.0

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version: 7 Sp1 x64 )

#### I'm using python version:

- [ ] Other: 3.7.9

#### I installed PuLP via:

- [ ] pypi (pip install pulp)

#### Did you also

- [ ] I Tried out the latest github version: https://github.com/coin-or/pulp  Pulp 2.3.1,  but still the same results.

**Comment by pchtsp** [comment]
check number two here about precision and numerical issues:

https://coin-or.github.io/pulp/guides/how_to_debug.html#error-while-trying-to-execute-cbc-exe

In any case, that would be an issue to report to: https://github.com/coin-or/Cbc/issues
