### ISSUE TITLE
Repeated Names Error

### ISSUE THREAD

**Issue by apassenger** [coin-or/pulp#361]
Hello,
I am trying to code in the following program
Find y ∈R^m 
minimising y·ve 
subject to M'*y ≥ 1 and y ≥ 0 

And I wrote this code:
# Create a LP Minimization problem 
Lp_prob = pulp.LpProblem('Problem', pulp.LpMinimize)  

x=np.zeros((64,1))
x = np.array(x)
x=x.reshape(64,1)
print(x.shape)

# Create problem Variables  

yy = pulp.LpVariable.matrix("yy",x,lowBound= 0 )

# Objective Function 

obj_func = pulp.lpSum(yy*v0)
Lp_prob += obj_func 
#obj_func = np.matmul(yy,v0) #ve is the matrix
#for i in obj_func:
#    Lp_prob += i  
# Constraints: 
#cs1=np.matmul(M.T,yy)
#for i in cs1:
#    Lp_prob += i
Lp_prob +=pulp.lpSum(M.T*yy)>= 1
Lp_prob += 0<=pulp.lpSum(yy)
#Lp_prob += yy>=np.zeros((64,1))
#for i in yy:
#    Lp_prob += 0<=i
# Display the problem 
print(Lp_prob) 

status = Lp_prob.solve(pulp.GLPK(msg = 0))   # Solver 
print(pulp.LpStatus[status])   # The solution status 
  
# Printing the final solution 
print( pulp.value(Lp_prob.objective)) 

But I am getting the following error:
raise const.PulpError('Repeated variable names:\n' + str(repeated_names))
pulp.constants.PulpError: Repeated variable names:
[('yy__0._', 64)]
How can I fixed this errors?
Many thanks from now..

**Comment by dassouki** [comment]
when I do my variable names I usually do something along the lines of "X_%s_%s_%s" % (r, s, t) so when I read the output it's exactly known which variable is calling what. That being said, I see you're posting a lot on here. I'm assuming you're quite familiar with the examples and you have tried to go through them on your own. I found those are very helpful especially when I first started learning.

**Comment by apassenger** [comment]
Your mean is that yy = pulp.LpVariable.matrix("yy_%s_%s_%s",x,lowBound= 0 ) ??
Yeah I read a lot of things and I applied a lot of things and half of my problems have been solved but other half of is still not solved :(

**Comment by apassenger** [comment]
And when I tried it =, I am getting the following error:
 return [LpVariable(name % tuple(indexStart + [i]),
TypeError: not enough arguments for format string

**Comment by dassouki** [comment]
Didn't  really read your code but here's what I meant:

```
for s in site_classes:
    for a in age_classes:
        prob += (lp.lpSum(x_vars[(s, a, p)] for
                          p in period_classes) <= age_areas[a][s],
                 'A_%s_%s' % (s, a))
```

**Comment by apassenger** [comment]
Ah no it definetalt won't work for me 
You are doing very different things..
When you have time can you have a look my problem. I put mu code and the program which I have to code

**Comment by apassenger** [comment]
Hello,
I did some corrections on the code 
Here is my final codes
# Create a LP Minimization problem 
Lp_prob = pulp.LpProblem('Problem', pulp.LpMinimize)  

x=np.zeros((64,1)) # our dilension is still 0
x = np.array(x)# now we have 64*1
x.reshape(64,1)
# Create problem Variables  
yy=pulp.LpVariable.matrix("yy",x, lowBound = all(np.zeros((64,1))) ) 
#yy=pulp.LpVariable.matrix("yy",x ) 
#yy=pulp.LpVariable.matrix("yy",x, lowBound = np.zeros((64,1)) ) 
# Objective Function 

#obj_func = pulp.lpSum(yy*v0) # I found a dot. function
#print("******",obj_func)
obj_func =pulp.lpSum( np.dot(yy,v0))
#print("heyooo",obj_func)
Lp_prob += obj_func #Lp_prob= Lprob+obj_func

# Constraints: 
cs1=np.matmul(M.T,yy)
Lp_prob += all(cs1)>=1

#cs2=np.zeros((64,1))
cs2_=np.identity(64)
cs2_ = np.matmul(yy,cs2_)

Lp_prob +=  all(cs2_)  >= 0
# Display the problem 
print(Lp_prob) 

status = Lp_prob.solve(pulp.GLPK(msg = 0))   # Solver 
print(pulp.LpStatus[status])   # The solution status 
  
# Printing the final solution 
print( pulp.value(Lp_prob.objective)) 

But I still have the same error
How can I fix it?

**Comment by apassenger** [comment]
it is ok :))
