### ISSUE TITLE
bad performance of + operator

### ISSUE THREAD

**Issue by 0b11001111** [coin-or/pulp#372]
Not really a bug but this seems to be the category my issue fits best in.

In a project I programatically generate a LP and it turned out that the `add` operation performs way worse when applied to `LpVariable`s than `iadd`. The following example illustrates the performance difference which is significant, at least on my setup:

```python
from functools import reduce
from operator import add, iadd
from time import monotonic

from pulp import LpProblem, LpMinimize, LpVariable

n = 50
lp_1 = LpProblem(f'myLp1', LpMinimize)
lp_2 = LpProblem(f'myLp1', LpMinimize)

t_0 = monotonic()
lp_1 += reduce(add, (LpVariable(f'p_{s_j}_{s_j}', 0., 1.) for s_i, s_j in product(range(n), range(n))))
t_1 = monotonic()
lp_2 += reduce(iadd, (LpVariable(f'q_{s_j}_{s_j}', 0., 1.) for s_i, s_j in product(range(n), range(n))))
t_2 = monotonic()

d_1 = t_1 - t_0
d_2 = t_2 - t_1

print(f'use +: {d_1:.3}s (~{d_1 / d_2:.2f}x)')
print(f'use +=: {d_2:.3}s (1x)')
```

which outputs the something like this
```text
use +: 1.21s (~192.34x)
use +=: 0.00629s (1x)
```

I'm using `pulp 2.3.1` on linux.

Thanks for providing such a great tool.
I hope my finding helps to improve it!

**Comment by 0b11001111** [comment]
Well, I think I had a misconception about the implementation internals here. I assume, that wile in my case the semantics are equivalent, internally `+` (`add`) implicitly performs a copy (i.e. memory allocation) while `+=` (`iadd`) happens in place, just like the name says. That makes perfectly sense if you think about it. However, people that are not aware of the concepts of memory management may oversee this.

Is my assumption correct?

**Comment by pchtsp** [comment]
You are right that the `+` does a copy of  both sides.

In the examples you provide:

```python
lp_1 += reduce(add, (LpVariable(f'p_{s_j}_{s_j}', 0., 1.) for s_i, s_j in product(range(n), range(n))))
```
you are assuming you will be summing each variable individually. That's not how you're supposed to do it if you want to do it efficiently. There are pulp functions (namely, `LpSum`) that sum the elements in a list without having to make copies of them.

Check the examples in the docs to see how to use it.

**Comment by 0b11001111** [comment]
Thanks for the clarification!

> Also, you should not be creating variables and using them once in your model (I guess it's just a toy example?). Check the examples in the docs to see how to use it.

Those snippets are just examples and the actual code looks quite different though.

> If you have a specific example with your model, feel free to post the pulp code for the actual model in the discussions page of github so we can give specific advice for modeling efficiently.

I may get back on that offer once I publish that project, thanks! :)
