### ISSUE TITLE
Crash in toDict() (called from model.to_json)

### ISSUE THREAD

**Issue by yoid2000** [coin-or/pulp#373]
Details for the issue
--------------------

#### What did you do?
Called model.to_json().

Roughly speaking, the following sequence:
```
prob = pulp.LpProblem("Attack-Problem")
...
# Add decision variables
self.choices = pulp.LpVariable.dicts("Choice", (aids, allCounts.keys()), cat='Binary')
...
# add constraints
prob += pulp.lpSum([self.choices[aid][bkt] for aid in aids]) == allCounts[bkt]
...
# try to export
prob.to_json(path)
```

#### What did you expect to see?
An exported file  ;)

#### What did you see instead?
The code crashed:

```
Traceback (most recent call last):
  File "lrAttack.py", line 258, in <module>
    lra.storeProblem(prob)
  File "lrAttack.py", line 235, in storeProblem
    prob.to_json(path)
  File "C:\Users\francis\Miniconda3\lib\site-packages\pulp\pulp.py", line 1354, in toJson
    json.dump(self.toDict(), f, *args, **kwargs)
  File "C:\Users\francis\Miniconda3\lib\site-packages\pulp\pulp.py", line 1287, in toDict
    objective=dict(name=self.objective.name, coefficients=self.objective.toDict()),
AttributeError: 'NoneType' object has no attribute 'name'
```

As a work around, I found that if I create a dummy objective function, then the export/import works fine:

```
        prob = pulp.LpProblem("Attack-Problem",pulp.LpMinimize)
        # The following dummy objecting is a work-around for a bug in the
        # to_json call.
        dummy=pulp.LpVariable("dummy",0,0,pulp.LpInteger)
        prob += 0.0*dummy
        ...
```

I'm happy to provide my code if you might find it helpful. I did generate a `.lp` file immediately prior to the crashing `to_json()` call, which I've loaded here:

https://gist.github.com/yoid2000/5ef6943c6b08a2bea70a8aa0ec1059ed

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

More specifically:
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎8/‎3/‎2020
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.7

More specifically:
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

More specifically:
Requirement already satisfied: pulp in c:\users\francis\miniconda3\lib\site-packages (2.3.1)
Requirement already satisfied: amply>=0.1.2 in c:\users\francis\miniconda3\lib\site-packages (from pulp) (0.1.4)
Requirement already satisfied: pyparsing in c:\users\francis\miniconda3\lib\site-packages (from amply>=0.1.2->pulp) (2.4.7)
Requirement already satisfied: docutils>=0.3 in c:\users\francis\miniconda3\lib\site-packages (from amply>=0.1.2->pulp) (0.16)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
(No, but I did make sure the latest version from pypi was used)
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Interesting. Indeed we assume there is an objective function in the model when exporting it. We should not assume one.

In the meantime, a workaround is just to create some objective function (anyone, even a constant one) and then export it.

**Comment by yoid2000** [comment]
> Indeed we assume there is an objective function in the model when exporting it. We should not assume one.

I'm not sure this is 100% the case. For instance, I tried running to_dict() in the Sudoku1.py example, which does not have an objective function, but that export worked fine.
