### ISSUE TITLE
On CBC api, the default options are not being overwridden for new ones

### ISSUE THREAD

**Issue by guifcoelho** [coin-or/pulp#376]
The default CBC solver options defined in coin_api.py (presolve on, gomory on, knapsack on, and probing on) are not overwridden when I add new conflicting ones.

For example, the default is "probing on". If I include the option "probing strongRoot", the resulting output is:

```
Problem MODEL has 179973 rows, 40910 columns and 525002 elements
Coin0008I MODEL read with 0 errors
seconds was changed from 1e+100 to 7200
Option for probingCuts changed from on to strongRoot
Option for gomoryCuts changed from ifmove to on
Option for knapsackCuts changed from ifmove to on
Option for probingCuts changed from strongRoot to on
```

I believe changing line `options = self.options + self.getOptions()`, in "solve_CBC" method of "COIN_CMD" class, to `options = self.getOptions() + self.options` will fix the problem.

**Details for the issue**
--------------------

#### What did you do?
Tried to change CBC solver options

#### What did you expect to see?
The options defined in `getOptions` method of `COIN_CMD` class should have been overwridden.

#### What did you see instead?
The new options are called before the default ones, therefore they end up being replaced and never used.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.7.9

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github
- [ ] Other: ___

#### Did you also

- [x] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Hello,

Thanks for the report. In fact, this is caused by there being more than one way to pass options to CBC. Can you provide an minimal working example of how you're passing the options to the solver?

**Comment by guifcoelho** [comment]
Hello!

I use the COIN_CMD class constructor to pass other options to CBC solver:

```python
import pulp

m = pulp.LpProblem(sense=pulp.LpMinimize)

solver = pulp.COIN_CMD(
            path=path_to_cbc,
            msg=True,
            cuts=True,
            presolve=True,
            gapRel=0.05,
            timeLimit=7200,
            keepFiles=False,
            warmStart=False,
            options=[
                'probing strongRoot'
            ]
        )

m.solve(solver)
```

**Comment by pchtsp** [comment]
Your issue is that you're giving the `cuts=True` argument which already sets `gomory on knapsack on probing on` with CBC. If you don't want this, you should set `cuts=False` and manually give the options you require with the `options` argument. For example, by doing something like:  `options=['probing strongRoot', 'gomory on', 'knapsack on'].

Let me know if that works!

**Comment by guifcoelho** [comment]
Hello Franco, thank you for the response. That works just fine. 

I always saw this 'options' argument in COIN_CMD as a way to change the 'default' settings of the solver api.
