### ISSUE TITLE
Bad image errors

### ISSUE THREAD

**Issue by Mark531** [coin-or/pulp#380]
Hello,

When running pulp with CBC, I ran into a PulpSolverError, so I generated the mps file and ran CBC on it to investigate further. I get many errors like this one:
`Bad image at line 16883 <     myvar_10928320.0_10916269.0  OBJ        inf >`

What does it mean? Is infinite symbol unrecognized by CBC?

Cheers,
Mark

**Comment by pchtsp** [comment]
Hello!
Definitively not, sorry.
"inf" is a numpy term, nothing to do with pulp and CBC. In any case, you can open an issue in CBC: https://github.com/coin-or/Cbc
