### ISSUE TITLE
Switch docs theme to sphinx_rtd_theme

### ISSUE THREAD

**Issue by venaturum** [coin-or/pulp#387]
Describe the new feature
--------------------------
At the moment the docs for PuLP are built using sphinx_glpi_theme.

This theme is an extension of sphinx_rtd_theme, to include some features such as a fancybox JS script (for displaying images) as well as some minor aesthetic changes (such as prev/next buttons at top of page in addition to bottom of page).

Reasons to switch to sphinx_rtd_theme:

- sphinx_glpi_theme is relatively obscure.   It has been downloaded ~38K times whereas sphinx_rtd_theme has ~32M downloads.
- sphinx_rtd_theme is actively maintained, whereas sphinx_glpi_theme is not
- since sphinx_glpi_theme is based on sphinx_rtd_theme, they have almost identical aesthetics and functionality
- the main difference between the two - the fancybox JS script - does not look like it is used by PuLP docs

I'm happy to submit pull request if the decision is made to switch

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by pchtsp** [comment]
go ahead with the PR and I'll approve it once I check that the docs remain the same.
