### ISSUE TITLE
Add a developer guide to sphinx docs

### ISSUE THREAD

**Issue by venaturum** [coin-or/pulp#388]
Describe the new feature
--------------------------

This would include moving (or duplicating) existing contributions document and history document.

In addition, include instructions on how to build the sphinx docs (and the package requirements needed to do so)

Potentially virtual environment setup (eg https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#creating-a-python-environment)

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by pchtsp** [comment]
Sounds good.

Ideally, we should map the contributing file to the sphinx docs so as to only modify it once (this is already done for the README file, for instance, which is imported to the sphinx docs). Of course, the contributing file can be expanded (with references to a virtual environment as you mention). We also want to add a developers' guide on "how to add a new solver". 

For more missing pulp functionality / docs, see the github project: https://github.com/coin-or/pulp/projects/1
