### ISSUE TITLE
Update to installation docs

### ISSUE THREAD

**Issue by venaturum** [coin-or/pulp#389]
Describe the new feature
--------------------------

pip install ... commands are better off as
`python -m pip install ...`

as per https://docs.python.org/3/installing/index.html

More info here: https://snarky.ca/why-you-should-use-python-m-pip/

Also pulp is available on conda forge but is not mentioned here (as far as I can tell)
https://anaconda.org/conda-forge/pulp

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by pchtsp** [comment]
About the installation commands, I really have no preference. Feel free to propose the changes and I'll check them.

The conda-forge repo is not on our control so it has been historically not-updated. I'm not sure which version they have now.
Not sure if it's a good idea to put it in the README if we cannot guarantee it will be up to date.

**Comment by venaturum** [comment]
It's not currently up to date.  The last update was in late October. 

Conda forge has a bot which is supposed to recognise changes in PyPI and setup a recipe change for conda forge so that the recipe maintainers just have to approve a pull request.  So it should be a simple process, but the bot seems to be struggling lately.  Even without the bot, updating the conda forge recipe manually is straightforward though.

Do you want me to see if I can get you added as a maintainer?

**Comment by pchtsp** [comment]
I'm not looking for yet another project to maintain : )
But I encourage you to become the maintainer yourself!
Maybe adding a github action to run the pulp tests at each PR created by the bot can simplify deployment there.

**Comment by pchtsp** [comment]
I've added the automatic deployment of the docs with each push to the master. I've also edited the README with the changes you proposed (python -m pip install). Do tell me if there are other changes you think we should do!

**Comment by venaturum** [comment]
Great stuff Franco, I'm going to close this issue.

I tried several times to get a response from the maintainers of the pulp conda-forge feedstock but did not get anywhere.  I may have to try other avenues...
