### ISSUE TITLE
possibility to avoid calling writeMPS, avoid writing to files

### ISSUE THREAD

**Issue by thehamzam** [coin-or/pulp#396]
### Details for the issue

Hello, 

Is it possible to avoid calling writeMPS function here on line 107,
https://github.com/coin-or/pulp/blob/master/pulp/apis/coin_api.py
def solve_CBC(self, lp, use_mps=True): -- 
**how can I set use_mps=False**, so that line 113 (if use_mps:) is False and does not execute the proceeding statements.

As I am trying to deploy this application containing pulp on a serverless architecture,
I don't have write permissions (i.e. no "with open(...) as f" is allowed), so I am trying to avoid
writing in this manner.

Thanks!

#### I'm opening this issue because:

- [ ] PuLP has a bug
- [x] PuLP needs a feature
- [ ] PuLP has another problem

#### I'm using PuLP on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [x] 3.6
- [ ] Other: ___

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github (pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Sorry but if you're not using mps then you use lp which is another data format. If you don't have write access I'm not sure you will have rights to execute the CBC executable that's inside pulp. Also: I'm not sure you can feed CBC with anything that's not a file...

I don't see how this is possible. If you have any ideas, do share them!

**Comment by tkralphs** [comment]
DipPy is a Python interface to [Dip](https://github.com/coin-or/Dip) that is built on top of PuLP and has a C extension that includes Cbc. It is not really designed to be used as a way to call Cbc (it is a decomposition-based solver that uses Cbc as a sub-solver), but it could be modified to call Cbc directly without too much trouble. If that sounds interesting, I could provide more details. There is also [python-mip](https://github.com/coin-or/python-mip), which calls the Cbc library directly.

**Comment by thehamzam** [comment]
thank you both! I actually realized my problem could be framed as a 0/1 Knapsack problem, so I decided to use that approach instead of linear programming -- will consider using LP for future projects.
