### ISSUE TITLE
Search in the documenation is broken

### ISSUE THREAD

**Issue by lovasoa** [coin-or/pulp#397]
Trying to make a search in the online documentation (https://coin-or.github.io/pulp/) gives invalid links in the results.
For instance, the first link in : 

https://coin-or.github.io/pulp/search.html?q=lpSum&check_keywords=yes&area=default

is : 

[`https://coin-or.github.io/pulp/technical/pulp`**`undefined`**`?highlight=lpsum#pulp.lpSum`](https://coin-or.github.io/pulp/technical/pulpundefined?highlight=lpsum#pulp.lpSum)

I think the link was supposed to be 

https://coin-or.github.io/pulp/technical/pulp?highlight=lpsum#pulp.lpSum

**Comment by pchtsp** [comment]
this seems to be working with the automatic deployment of the docs (can't really explain why, though). I'm closing the issue.
