### ISSUE TITLE
include support for xarray

### ISSUE THREAD

**Issue by Joeperdefloep** [coin-or/pulp#398]
Describe the new feature
--------------------------
When working with many (named) variables in xarray, it may be useful to also add a variable to an xarray. This allows for easier declaration of equations if you are already working with data in xarray format. or when reading data from excel or NetCDF.
proposed implementation almost identical to [this SO thread](https://stackoverflow.com/questions/44834583/output-of-pulp-to-numpy-arrays).
```
import pulp
import numpy as np
import pandas as pd
import xarray as xr

#the following is an implementation to get an LpVariable in an xarray
def add_lpvar_to_dataset(dataset,var_name,dim_names,named_index=True,low_bound=0,up_bound=None,cat='Continuous'):
    #convert to iterable if string
    dim_names = (dim_names,) if isinstance(dim_names,str) else dim_names
    #create a tuple with dimensions
    dims = tuple( dataset.dims[key] for key in dim_names )
    
    def _get_index_names(index):
        if named_index:
            #iterate over the index, and get the appropriate 
            #dataset.coords is a dict with arrays of index.
            #So we get the array of it using dim_names[i] 
            #then, index it and get the data (the value instead of array)
            return tuple(dataset.coords[dim_names[i]][index[i]].data for i in range(len(index)) )
        else:
            return index
    
    def _define_variable(*index):
        descr = '_'.join(map(str,(var_name, *_get_index_names(index))))
        return pulp.LpVariable(descr ,low_bound,up_bound, cat)
    
    def _build_variables_array():
        f = np.vectorize(_define_variable)
        return np.fromfunction(f, dims, dtype="int")
    
    variables = _build_variables_array()
    dataset[var_name] = xr.DataArray(dims=dim_names,data=variables)
    
    return variables
```
given two datasets `crop` and `animal`, we can define a problem.
apologies for not actually having the variables ready here. I implemented this as an open source alternative to GAMS in a course about linear optimisation, and am waiting for answers to whether I can make the course data public or have to invent my own.
Then LPvariables can be added as:
```
add_lpvar_to_dataset(dataset=<dataset>,var_name='Area',dim_names=('CROP','TECH'),low_bound=0,up_bound=200)
```
and objective/constraints added as:
```
#define the problem
problem =pulp.LpProblem('problem',pulp.LpMaximize)

#define the profit function:
problem += (
    +np.sum((crop.Sold*crop.PRICE).data) 
    -np.sum((crop.COSTS*crop.Area).data)
    +np.sum((animal.SoldProd*animal.PRICE).data)
    -np.sum((animal.Held*animal.COSTS).data)
)

#labour requirement
labArr = (crop.R_LAB*crop.Area).sum(dim=('CROP','TECH')) + animal.R_LAB*animal.Held
for s in crop.coords['SEAS']:
    problem += pulp.LpConstraint(np.sum(labArr.loc[s].data),1,rhs=np.sum(crop.A_LAB.loc[s].data),name='_'.join(('Lab',str(s.data))))
```
here, there are some quirks though: 
when summing over all axes of a variable, using `np.sum(DataArray.data)` works well,
otherwise `DataArray.sum(dims=('dim1','dim2'))` can be used.
however, this returns an ndArray even for a single value, 
so use `np.sum` again when iterating
`problem += np.sum((crop.Area*crop.N_LEACH).data)`

Then solve the problem
```
status = problem.solve()
print(pulp.LpStatus[status])
value = np.vectorize(pulp.value)
print('areas: ',(value(crop.Area)))
```
This is my first time contributing to any project, so please tell me if this is welcomed here, or whether it should be something like a separate module, since it requires xarray, which not all users of PuLP will be using.\
cheers!

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
no

#### Does this feature exist in another product or project? Please provide a link.
I think it is very similar to the way variables are handled in [GAMS](https://www.gams.com/download/). I wrote this as an alternative for that: being able to add equations with ease, and also having automatically named equations for each named index.

**Comment by pchtsp** [comment]
Yeah, I think this could potentially be a separate module (because of the numpy, xarray dependencies). Have you looked at this issue https://github.com/coin-or/pulp/issues/285 ? I'm not sure if this is a similar tool or at least compatible to the project they shared: https://github.com/qdbp/pulp-lparray

If you end up making a separate package, you can add it to the plugins part of the docs: https://coin-or.github.io/pulp/plugins/index.html

**Comment by Joeperdefloep** [comment]
wow, it would've been so useful to have known that package before...
there is a difference though: xarray can have _named_ dimensions, which makes debugging easier. I will look further into it, thanks!

**Comment by pchtsp** [comment]
I'm going to close this issue. As I said, feel free to make a PR to add your plugin to the docs. I've just added the lparray plugin to the docs.
