### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#4]
```
Perhaps the name space should be changed to look something like this.

import pulp as lp

prob = lp.Problem()

instead of 

from pulp import *

prob = LpProblem()


```

Original issue reported on code.google.com by `stuvagas@gmail.com` on 28 Apr 2008 at 11:11

**Comment by pchtsp** [comment]
I think I'm going to close this issue... It's already too late to change naming.
