### ISSUE TITLE
PuLP  PulpSolverError("Pulp: Error while executing "+self.path) 

### ISSUE THREAD

**Issue by xy109109** [coin-or/pulp#410]
hello! 
i am trying to formulate a relatively simple LP program but is encountering the following errors when i run prob.solve:  

PulpSolverErrorTraceback (most recent call last)
<ipython-input-122-c693b1d1167d> in <module>
     22     prob+=solar[a]-ch[a]>=0
     23 
---> 24 prob.solve()
     25 rev=value(prob.objective)
     26 

/opt/conda/lib/python3.7/site-packages/pulp/pulp.py in solve(self, solver, **kwargs)
   1735         #time it
   1736         self.solutionTime = -clock()
-> 1737         status = solver.actualSolve(self, **kwargs)
   1738         self.solutionTime += clock()
   1739         self.restoreObjective(wasNone, dummyVar)

/opt/conda/lib/python3.7/site-packages/pulp/apis/coin_api.py in actualSolve(self, lp, **kwargs)
     99     def actualSolve(self, lp, **kwargs):
    100         """Solve a well formulated lp problem"""
--> 101         return self.solve_CBC(lp, **kwargs)
    102 
    103     def available(self):

/opt/conda/lib/python3.7/site-packages/pulp/apis/coin_api.py in solve_CBC(self, lp, use_mps)
    157             pipe.close()
    158         if not os.path.exists(tmpSol):
--> 159             raise PulpSolverError("Pulp: Error while executing "+self.path)
    160         status, values, reducedCosts, shadowPrices, slacks, sol_status = \
    161             self.readsol_MPS(tmpSol, lp, vs, variablesNames, constraintsNames)

PulpSolverError: Pulp: Error while executing cbc

i am running the script on a virtual machine... very new to this, any help is appreciated!

**Comment by xy109109** [comment]
the only available solver is COIN_CMD

**Comment by pchtsp** [comment]
have you tried the steps mentioned here: https://coin-or.github.io/pulp/guides/how_to_debug.html?

**Comment by xy109109** [comment]
yes. same error when i did _prob.solve(COIN_CMD(msg=1))_  (not surnot sure if this is the correct way to include msg=1, but COIN_CMD is the only available solver

**Comment by xy109109** [comment]
<img width="422" alt="Screen Shot 2021-03-08 at 15 04 12" src="https://user-images.githubusercontent.com/64550393/110375197-a4abdc00-801f-11eb-9d9c-e787ac49fe62.png">
this is my formulation... maybe it's something with the variable coefficients?

**Comment by pchtsp** [comment]
Hello again! Well, there're several steps in that site that you have probably not tried so I'm going to take the liberty to paste them here:

1. Always submit a minimum reproducible example (how to here).
1. Check this video on how to ask questions. Although aimed to another programming language, the message and recommendations are very good.

Now, specifically to PuLP:

1. If possible, share an export version of the model. Check here how to export one.
1. Alternatively, share a mps version of your model. To produce one, use writeMPS().

Other information that is also useful:

1. Version of pulp.
1. How did you install pulp (via pypi, or from github).
1. What operating system was used.


To which I add: are you running this from a jupyter notebook? Do you have write access to the place where pulp is installed? You should have the `PULP_CBC_CMD` solver available too.

**Comment by xy109109** [comment]
i am running from a notebook!  how can i write access to the place where pulp is installed?
