### ISSUE TITLE
Repo does not follow flake8/isort/black standards

### ISSUE THREAD

**Issue by rimaddo** [coin-or/pulp#423]
Describe the new feature
--------------------------
These days formatting repos with flake8/isort (for python 3.5 and earlier) and black (for 3.6 and later) is standard for python repos.

However the pulp codebase does not match with these standards.

I would be interested in making this change, and could add a pre-commit-hook or similar so that this could be maintained in the future, but I wanted to understand if this was of interest to the maintainers / community beforehand, since I understand that it is quite a large change.

It would also be good to consider doing it in several steps perhaps, e.g. flake8 then isort then black perhaps.

**Comment by pchtsp** [comment]
Hello, thanks for the suggestion.

Although I do think it's a good idea, I'm not 100% aware of what the changes would imply to be honest. Is it the variable naming convention? Or only spaces, commas, etc.?

The ideal would be pass the project through an automated tool (if available) and show the changes via a PR. And, as you say, eventually maybe have a hook or something.

If it's not too much of a hassle (i.e., automatic tool) to come up with a PR, I'll give it a look.

Thanks again.

**Comment by rimaddo** [comment]
Okay thanks, I started with making a black pr as commented just above. This is the easiest change to make and also makes a big bulk of the changes. Then flake8 and isort could be made afterwards depending on thoughts.

Most of the changes from black in it as mentioned are around spaces, commas, quotes, line breaks etc.

Isort would impose rules on your import ordering / formatting etc.

Flake8 more generally on python standards eg should not import from `*`, use bare exceptions, etc.

You mentioned variable naming, that is something that is breaking pep8, since there are lots of variables and functions which are camel case as opposed to snake case. However, flake8 doesn't correct that as standard, you need to use something like `pep8-naming` to get linting corrections for this. I can understand though that this might be the most undesirable change to make, since the other linting changes described above will only impact your codebase, but renaming functions and variables to comply with pep8 naming will impact how people interact with your package as users will reference the current camelcase format.

**Comment by pchtsp** [comment]
I'll close this issue as I think it was solved by the PR you did. Feel free to re-open it or open a new one if that's not the case!
