### ISSUE TITLE
choco solver is not found if pulp is installed in path with whitespace

### ISSUE THREAD

**Issue by behrisch** [coin-or/pulp#432]
Details for the issue
--------------------

#### What did you do?
I installed Pulp 2.4 on windows and ran the test suite

#### What did you expect to see?
Successful tests

#### What did you see instead?
```
ERROR: test_pulp_121 (pulp.tests.test_pulp.PuLPTest)
Test the ability to use Elastic constraints
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\pulp\tests\test_pulp.py", line 607, in test_pulp_121
    pulpTestCheck(prob, self.solver, [const.LpStatusOptimal],
  File "C:\Program Files\Python38\lib\site-packages\pulp\tests\test_pulp.py", line 944, in pulpTestCheck
    status = prob.solve(solver, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pulp\pulp.py", line 1737, in solve
    status = solver.actualSolve(self, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pulp\apis\choco_api.py", line 92, in actualSolve
    raise PulpSolverError("PuLP: Error while trying to execute "+self.path)
pulp.apis.core.PulpSolverError: PuLP: Error while trying to execute C:\Program Files\Python38\lib\site-packages\pulp\apis\../solverdir/choco/choco-parsers-with-dependencies.jar
```

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.8

#### I installed PuLP via:

- [x] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

The problem can probably be fixed in choco_api.py by adding double quotes around the classpath in https://github.com/coin-or/pulp/blob/master/pulp/apis/choco_api.py#L73 and using shlex.split instead of split in https://github.com/coin-or/pulp/blob/master/pulp/apis/choco_api.py#L89

**Comment by pchtsp** [comment]
Could you provide a PR? I'll happily review it and accept it.

**Comment by behrisch** [comment]
see #438

**Comment by pchtsp** [comment]
thanks!

**Comment by pchtsp** [comment]
it fails in github actions: https://github.com/coin-or/pulp/runs/2494971174?check_suite_focus=true

**Comment by behrisch** [comment]
Sorry about that, I thought the PR would already run the tests. I can propose another solution.

**Comment by behrisch** [comment]
the new pr is #439

**Comment by pchtsp** [comment]
cool, thanks! I did not know we could test PRs. Thanks for that also.
