### ISSUE TITLE
python3.8 aarch64 linux platform LpProblem.solve has error OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by owen510754** [coin-or/pulp#433]
Details for the issue
--------------------

#### What did you do?
In my program I called
prob=LpProblem("binPack", 1)
prob += some constraints
prob.solve(PULP_CBC_CMD(maxSeconds=tmlim, fracGap=mipgap, msg=1, keepFiles=0))

#### What did you expect to see?
normally execute

#### What did you see instead?
![image](https://user-images.githubusercontent.com/81287955/115827567-0b098400-a43f-11eb-9217-44b00e611bd1.png)

Useful extra information
it work on x86 platform
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x ] Other: 3.8___

#### I installed PuLP via:

- [x ] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [x ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x ] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Hello!
Try to check this page for ways to debug and found the root cause: https://coin-or.github.io/pulp/guides/how_to_debug.html

Specially, try to see if you have the rights to execute cbc from that environment:

```
PATH_TO_PULP/solverdir/cbc/linux/64/cbc
```

**Comment by owen510754** [comment]
> Hello!
> Try to check this page for ways to debug and found the root cause: https://coin-or.github.io/pulp/guides/how_to_debug.html
> 
> Specially, try to see if you have the rights to execute cbc from that environment:
> 
> ```
> PATH_TO_PULP/solverdir/cbc/linux/64/cbc
> ```

Hi, I haved checked the file PATH_TO_PULP/solverdir/cbc/linux/64/cbc, it is in x_86-64 format, so it cannot be run. But here still have a problem, is pulp supported to install on aarch64 platform? Because I pip install it on a aarch64 machine but got a x86 cbc file.

**Comment by pchtsp** [comment]
I had no idea what the aarch64 platform is. Googling leads to ARM architecture. The binaries that come with PuLP are most probably *not* suited for that (they are pre-compiled executables). PuLP itself works but you have to look for your own solver binaries (cbc or any other).
