### ISSUE TITLE
Please add the setting of turning off printout to the function LpProblem.solve()

### ISSUE THREAD

**Issue by cognaclee** [coin-or/pulp#442]
Describe the new feature
--------------------------
In the process of algorithm optimization, the printout function of the function LpProblem.solve() takes up a lot of computing resources, which greatly reduces the speed of the algorithm, especially in the algorithm that needs to call LpProblem.solve() frequently. Please add the setting of turning off printout to the function LpProblem.solve(). If the output of the LpProblem.solve() can be turned off, this problem will be solved well

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by pchtsp** [comment]
Hello!

I'm not sure what you mean by the "printout function" inside the LpProblem.solve(). Could you please share the lines of code we should edit / are causing the problem? Or the result of your profiler?

Another option is for you to share your code and / or your model (see [here](https://coin-or.github.io/pulp/guides/how_to_export_models.html) for info on doing that).

**Comment by cognaclee** [comment]
after call LpProblem.solve(), it will print the following information:
At line 2 NAME          MODEL
At line 3 ROWS
At line 10005 COLUMNS
At line 30206 RHS
At line 40207 BOUNDS
At line 40408 ENDATA
Problem MODEL has 10000 rows, 200 columns and 20000 elements
Coin0008I MODEL read with 0 errors
Presolve 0 (-10000) rows, 0 (-200) columns and 0 (-20000) elements
Empty problem - 0 rows, 0 columns and 0 elements
Optimal - objective value 1
After Postsolve, objective 1, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective 1 - 0 iterations time 0.002, Presolve 0.00
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.02   (Wallclock seconds):       0.03


I think it will be helpful to disable these output.

**Comment by pchtsp** [comment]
Check
https://coin-or.github.io/pulp/technical/solvers.html#pulp.apis.COIN_CMD

The msg=False argument is what you're looking for.

**Comment by cognaclee** [comment]
Thank you very much for your patient guidance！
Follow  your advice,  I modify the code like this : 
      prob = LpProblem("H_Star_Solution", LpMaximize)
      prob.solve(msg =False)

But I got an Error of : solve_CBC() got an unexpected keyword argument 'msg'

**Comment by pchtsp** [comment]
The argument goes when initializing the solver. You should do:
try:
```
prob.solve(PULP_CBC_CMD(msg =False))
```

**Comment by cognaclee** [comment]
The problem has been solved. thanks a lot!
Sincere thanks and respect！
