### ISSUE TITLE
Cbc Status code seems wrong

### ISSUE THREAD

**Issue by ebongo1** [coin-or/pulp#447]
What is your question
-----------------------
I'm wondering why the cbc status in the coin_api.py seem wrong. I attached a screen shot of the code I'm referring to. 
Why is the "Integer" cbcStatus the same constant as the infeasible status? 
![image](https://user-images.githubusercontent.com/83773112/119397359-033e3900-bca4-11eb-841d-0dcef2998672.png)

**Comment by stumitchell** [comment]
https://github.com/coin-or/pulp/blob/df9d41dd07d7fd65851db7e4cf13a75f540c982c/pulp/apis/coin_api.py#L299

is because CBC reports "Integer Infeasible" as 2 words but I do think this needs a comment
