### ISSUE TITLE
Using scipy.stats.gamma.pdf() in pulp objective function

### ISSUE THREAD

**Issue by LingkaiYang** [coin-or/pulp#449]
I am trying to use pulp for fitting a special gamma distribution, i.e., the Erlang distribution with the shape parameter to be an integer. So I first defined two decision variables (the shape and scale parameter in a gamma distribution) and then call the scipy.stats.gamma.pdf() function as the objective function. 

Part of the code is attached below, which is failed to running with the error information as

prob = LpProblem("MaxValue", LpMaximize)
shape = LpVariable('shape', lowBound=1, upBound=None, cat='Integer')
scale = LpVariable('scale', lowBound=0.01, upBound=None, cat='Continuous')

prob += lpSum(scipy.stats.gamma.pdf([1,2,3], a = shape, scale = scale))
prob.solve()

TypeError                                 Traceback (most recent call last)
<ipython-input-42-d8df8085991d> in <module>()
     25 # prob += lpSum([mixings[i]*scipy.stats.gamma.pdf([1,2,3], a = shapes[i], scale = scales[i]) for i in np.arange(N)])
---> 26 prob += lpSum(scipy.stats.gamma.pdf([1], a = shape, scale = scale))
     27 
     28 # scipy.stats.norm.pdf(aa)

~\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py in pdf(self, x, *args, **kwds)
   1758         args = tuple(map(asarray, args))
   1759         dtyp = np.find_common_type([x.dtype, np.float64], [])
-> 1760         x = np.asarray((x - loc)/scale, dtype=dtyp)
   1761         cond0 = self._argcheck(*args) & (scale > 0)
   1762         cond1 = self._support_mask(x, *args) & (scale > 0)

TypeError: unsupported operand type(s) for /: 'int' and 'LpVariable'

Many thanks if someone can help with the issue. Really appreciated.

**Comment by stumitchell** [comment]
Sorry due to the limits of linear programming methods it is impossible for pulp to build a model with a function call in the objective.

It needs a linear function.

Probably other libraries in scipy would be able to help.

Stu
