### ISSUE TITLE
Latest versions of cbc executables

### ISSUE THREAD

**Issue by aaron-parsons** [coin-or/pulp#454]
Hi,

Nice work on  this package.

We are currently looking to run pulp using the cbc solver on linux 64 bit. Unfortunately the platform we use currently only supports pip.

Your latest pip release (2.4) contains the older version of the solvers. I noticed that you updated them on master at 216d1e678a63f1da4208e4a525f8d0bea9437566 .

Pip constrains us to a version number, or pointing to a tag/version on the git repo.

Would you consider making a dot release for a stable version that uses these latest executables that we can point to?  

Thanks

Aaron

**Comment by pchtsp** [comment]
I just published version 2.5.0 with, among other changes, the new version of cbc.

**Comment by aaron-parsons** [comment]
Thanks @pchtsp
