### ISSUE TITLE
Including HiGHS solver

### ISSUE THREAD

**Issue by samiit** [coin-or/pulp#458]
Describe the new feature
--------------------------
Can we have support for the new, but promising [HiGHS](https://github.com/ERGO-Code/HiGHS) solver?

Additional info
---------------
#### Does this feature exist in another product or project? Please provide a link.
Julia language supports using HiGHS from within JuMP modelling language.

Thanks,
Sam

**Comment by pchtsp** [comment]
We could, definitely. If you by chance are interested in doing it, we recently published a guide to add a new solver: 
https://coin-or.github.io/pulp/develop/add_solver.html
I saw HiGHS uses an mps file as input so the provided example in the guide (that connects MIPCL) should be very similar.

**Comment by samiit** [comment]
Thank you @pchtsp for your guidance. I am on it and hopefully will soon give a pull request to review what I have done! It would be helpful for many, since I see that it outperforms Cbc in many of the instances I have encountered.

**Comment by Bouncner** [comment]
Isn't that issue resolved?

**Comment by samiit** [comment]
Yes.

**Comment by odow** [comment]
This could be reopened in light of https://github.com/coin-or/pulp/pull/477#issuecomment-1013267276

There are binaries you can try here (hot off the press. Let me know if there are issues):
https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/tag/HiGHSstatic-v1.2.0%2B0

Adding CI testing would avoid https://github.com/coin-or/pulp/pull/522

**Comment by samiit** [comment]
Hi @odow 

I tried downloading different linux versions (e.g., [this](https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.0%2B0/HiGHSstatic.v1.2.0.aarch64-linux-gnu-cxx03.tar.gz) and [this](https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.0%2B0/HiGHSstatic.v1.2.0.aarch64-linux-gnu-cxx11.tar.gz)) for Ubuntu 20 OS on my laptop, but the executable in the `bin` directory does not work. Any idea what I am missing?

Thanks,
Sam

**Comment by fgenoese** [comment]
You might want to check whether x86_64 builds work for your system

**Comment by odow** [comment]
How about the ones linked in this issue: https://github.com/ERGO-Code/HiGHS/issues/746

**Comment by samiit** [comment]
Great, these work out of the box on Ubuntu. I'll check them on Windows later in the day.
