### ISSUE TITLE
listing available solver versions?

### ISSUE THREAD

**Issue by jGaboardi** [coin-or/pulp#471]
What is your question
-----------------------

I am wondering if there is a way to also retrieve the *versions* of available solvers, like how we can get the name of the available solvers with `pulp.listSolvers(onlyAvailable=True)`? I searched the Discussions, Forum, and Issues but could find that this had been asked yet.

**Comment by pchtsp** [comment]
In theory it's up to the user to make the solvers available (install them,
connect them to Pulp). So the user should know the versions that are
installed in the machine.

**Comment by jGaboardi** [comment]
True, it would be a convenience function. I was thinking it would be helpful to have something like that when benchmarking and testing all available solvers in an automated process. Anyway, it's definitely not a high priority item. I'll go ahead and close for now.
