### ISSUE TITLE
Issue with difference between pip package and source code with CBC

### ISSUE THREAD

**Issue by tomaszG247** [coin-or/pulp#474]
Details for the issue
--------------------

#### What did you do?
Solved the same problem with the source code of Pulp and through pip install pulp

#### What did you expect to see?
The same results

#### What did you see instead?
The solver log output seem identical but the call to pu.value[prob.objective] is giving a different value for the objective function. The solution extracted is also different (and completely wrong with the source code). this happened only to me for a problem where the solver does not reach the required gap so the exit solution status is integerFeasible, but with a gap of only 1% so it is not that he found a wild solution

I realize its not great info to reproduce the issue but my problem construction code is huge. Any difference between the pip version and latest source for CBC?

**Comment by pchtsp** [comment]
there's a new version of CBC in the codebase. But this version is both in the source code and in pypy. So I'm not sure why you see this difference. Do you have a reproducible example we can test_

**Comment by tomaszG247** [comment]
same as #476
