### ISSUE TITLE
indexs vs indexes

### ISSUE THREAD

**Issue by bburns632** [coin-or/pulp#488]
Hi, this issue is around a seemingly misspelled parameter ([indexs](https://github.com/coin-or/pulp/blob/449e4b2950367f1d21d38a6afb07baf0dbc18f17/pulp/pulp.py#L348)), so it's not a bug in the sense that is blocks functionality.  However, it may complicate development for [pulp](https://github.com/coin-or/pulp) developers/users as they have to remember the correct incorrect spelling of the word is they want to provide that parameter explicitly within their code (a common best practice). 

If I could correct this parameter name in a non-breaking way with a deprecation warning, would you be open to that PR?  If so, I'd love to contribute. 

Details for the issue
--------------------

#### What did you do?
Assigned variables via `LpVariable.dicts()` method.  Had to look at [the docs](https://www.coin-or.org/PuLP/pulp.html) to confirm the correct variable name. 

#### What did you expect to see?
`LpVariable.dicts(indexs=)`

#### What did you see instead?
`LpVariable.dicts(indexes=)` 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x ] Mac OS: (  Catalina version: 10.15.7)
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [x ] 3.6
- [ ] Other: ___

#### I installed PuLP via:

- [x ] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x ] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Actually, wouldn't it be `indices` the correct wording?
As per doing the change, as long as it does not break previous things and doesn't require a ton of rework: yeah I'd be open to a PR.

**Comment by bburns632** [comment]
Great.  I'll submit a PR within the next few days.  I think either `indexes` or `indices` are legitimate within certain contexts.  

Could you confirm you would like the parameter name to be `indices` before I start the PR?

**Comment by stumitchell** [comment]
Gurobi uses indices so I guess we go with that
https://www.gurobi.com/documentation/9.1/refman/py_model_addvars.html

Still wait for Franco's call

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by bburns632** [comment]
Created the PR above assuming consensus around `indices`.

**Comment by pchtsp** [comment]
Thanks Stu, I was going to check what other libraries did, indeed.

Let's go with indices, then.

Franco
