### ISSUE TITLE
Optimize a looping script

### ISSUE THREAD

**Issue by lo-ve-ly** [coin-or/pulp#493]
Hi,
I have a large script which basically loops through a list of all CSV in a directory - constructs data frames on them - collects the results in another data frame - analyzes it and sums all up in a single numerical result(objective). This script employs a few linear integer variables which I wish to optimize. I wonder if your script can be used for this? Can I call your module form this script to make it try the variables - each time running the loop and collecting the objective? Do you think external optimisers (like Cplex)can handle such setup?
Thanks a lot!

**Comment by lo-ve-ly** [comment]
any pro users can please help?

**Comment by stumitchell** [comment]
Ask your issue lacks any specific detail I can't help you in specifics

But in general
Yes 
and Yes

As this is not an issue I am closing

**Comment by lo-ve-ly** [comment]
thanks - do you have any tutorial on this?

**Comment by stumitchell** [comment]
https://coin-or.github.io/pulp/

**Comment by lo-ve-ly** [comment]
thanks I mean a tutorial on how to optimize a script with a loop which calculates the objective function?
