### ISSUE TITLE
Tag v2.5.1 on GitHub as well

### ISSUE THREAD

**Issue by Aniket-Pradhan** [coin-or/pulp#500]
Hey!

I checked out PyPi and there seem to be some differences in the latest stable release between the two: On GitHub, the latest release is 2.5.0 and on PyPi it is 2.5.1.

I was updating the python-pulp package in Fedora and wanted to include the docs in it as well. If you could also tag the same latest stable release on GitHub as well that would be amazing.

**Comment by pchtsp** [comment]
just did, thanks for letting me know!
