### ISSUE TITLE
Amply import in pip docs

### ISSUE THREAD

**Issue by bbrewington** [coin-or/pulp#501]
Details for the issue
--------------------

#### What did you do?
Visited https://coin-or.github.io/pulp/main/amply.html as I was getting started with PulP

#### What did you expect to see?
No errors as I was following the instructions.  Specific code in question that caused the error: `from pulp import Amply`

#### What did you see instead?
Got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Amply' from 'pulp' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulp/__init__.py)
```

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 12.0.1 )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other:3.7

#### I installed PuLP via:

- [x] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
  - didn't do this, but I did search the documentation in the repo here, and confirmed the docs seem wrong: https://github.com/coin-or/pulp/blob/master/doc/source/main/amply.rst
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
amply has been moved to its own pacakge now: https://github.com/willu47/amply I will close the issue when I've updated the documentation.

**Comment by pchtsp** [comment]
fixed, the docs should update automatically soon.
