### ISSUE TITLE
Issue using XPRESS solver

### ISSUE THREAD

**Issue by nicolaslhuillier** [coin-or/pulp#505]
I have an issue using PULP with XPRESS.
XPRESS (v8.5) is correctly installed and works.
PULP correctly sees XPRESS as available solver.
When I try to solve a problem (ex sudoku) with XPRESS I see a log indicating the solver is initialized, but it never returns any solution.
It just seems to hang.
I have tried the "keepFiles" option without  additional luck.
Does it actually work ?

FYI : I am using PULP 2.5.0 with Python 3.8 on Windows 10 (x64)

**Comment by pchtsp** [comment]
have you tried using any other solver to see if the issue is with the solver or the mathematical problem? Can you share a reproducible example? we cannot run automatic tests with commercial solvers, unfortunately.

**Comment by nicolaslhuillier** [comment]
I reproduced it with the Sudoku example that is part of the online documentation (https://coin-or.github.io/pulp/CaseStudies/a_sudoku_problem.html)
It works with COIN or GLPK but hangs with XPRESS.

**Comment by artelysdufour** [comment]
Sounds like an issue at the pulp xpress interface level. It seems problem independant (and Xpress version independant as well, tried with a much more recent version on my side). Whenever you start pulp with Xpress, the process seems to get stuck line 148 of the xpress_api file. Looking at the output, it sounds like pulp starts the Xpress command line but does not pass it the lp file to solve.

**Comment by nicolaslhuillier** [comment]
It seems there is an Xpress community licence (http://content.fico.com/xpress-optimization-community-license) which is free though limited in terms of variables and constraints, but should allow investigating the problem.

**Comment by fgenoese** [comment]
A community license is included in the official xpress package that can be installed with: `pip install xpress`

Wonder if we could use it to build sn automatic test?

See: https://pypi.org/project/xpress/

**Comment by pchtsp** [comment]
I think that might just work. I just installed the library and apparently it comes with the necessary binaries. I'll try to add it to the testing in github actions once I'm able to connect PuLP to the pypi packaged installation of xpress.

**Comment by pchtsp** [comment]
wait, no, False alarm. The python package comes with .dll libraries, not the .exe:
![image](https://user-images.githubusercontent.com/5459187/144726239-1411848d-fe7c-4a12-b1e2-cc7ecf9a2cbb.png)

Unless someone implements a new pulp-xpress API that connects to their python package (as we have with CPLEX/ GUROBI / MOSEK), it's not going to be able to test with that unfortunately :  (

**Comment by fgenoese** [comment]
Gentle ping to @octachrome @susanneheipcke (the two members of the @fico-xpress group):
Do you see an easy fix to the existing source code of pulp or a possibility to bundle a solver executable (clearly with limitations) within the pypi xpress package to enable automatic testing?

**Comment by octachrome** [comment]
FICO is developing a PuLP API which uses the Xpress Python module, which will be made available soon. Until then, you can obtain the optimizer executable under the community license, although this is a single-user license only and does not permit the executable to be redistributed: https://content.fico.com/xpress-optimization-community-license.

**Comment by octachrome** [comment]
The reason that Xpress hangs is that the PuLP interface does not flush the commands through to the solver executable. There is a missing call to `stdin.flush()` after sending the commands. I will open a PR to fix this.
