### ISSUE TITLE
PulpSolverError: PULP_CBC_CMD: Not Available 

### ISSUE THREAD

**Issue by RobertMercieca** [coin-or/pulp#506]
As the title says I am getting that error, I am using conda with python 3.8.12 and pulp 2.5.1 and getting the above error on mac m1 pro.

Using base profile python 3.9.7 works perfectly, is this a conda error, a python error or a pulp error not working well with python 3.8.12.

Thanks

**Comment by pchtsp** [comment]
Have you tried using the pip version of pulp? We do not have visibility about the conda package, unfortunately. We actually do run automatic tests with python 3.8 in windows in github actions and they run correctly, e.g. : https://github.com/coin-or/pulp/runs/4143588412?check_suite_focus=true

**Comment by RobertMercieca** [comment]
Hi, yes I did try using pip, also pulp 2.5 and even below. Seems to be a conda issue then, maybe I will open one there

**Comment by mlisovyi** [comment]
I guess this is the same or at least relates to conda-forge/pulp-feedstock#22

**Comment by pchtsp** [comment]
closing as relates to conda, not pulp
