### ISSUE TITLE
pulp fails to locate collected cbc executable on MacOS generated by PyInstaller

### ISSUE THREAD

**Issue by LBeghini** [coin-or/pulp#513]
Details for the issue
--------------------

#### What did you do?
I tried to execute a simpleeval function that calls the pulp lib underneath it, that validates an expression

#### What did you expect to see?
The expression being validated

#### What did you see instead?
An exception:
```error
'NoneType' object has no attribute 'actualSolve'
```

#### Useful extra information
I have a [bug in my project](https://github.com/GraphFilter/GraphFilter/issues/116) and at first the error was with  a corner case of PyInstaller. I was testing on Windows, and then when it was solved, I tried to replicate the solution on Mac. However, on MacOS I was having the same problem, and I thought it was an error with PyInstaller again, then I described the behaviour in [this issue](https://github.com/pyinstaller/pyinstaller/issues/6427). 

One insight a user told me in order to fix the bug is that, on [this line](https://github.com/coin-or/pulp/blob/0cf902579b8ca52cca09d66df5619095f8062f99/pulp/apis/core.py#L186) change:

```python
config_filename = os.path.join(DIRNAME, "..", PULPCFGFILE)
```
to

```python
config_filename = os.path.normpath(os.path.join(DIRNAME, "..", PULPCFGFILE)) 
```

because PuLP is failing to find the config file in spite of it being collected. That's because `DIRNAME = os.path.dirname(__file__)` points to a directory that does not exist in the frozen bundle (`sys._MEIPASS/pulp/apis)` because all of its content ends up in PYZ archive. But the config file, `sys._MEIPASS/pulp/apis/../pulp.cfg.osx = sys._MEIPASS/pulp/pulp.cfg.osx` does exist.

> As described [here](https://github.com/pyinstaller/pyinstaller/issues/6427#issuecomment-991961299)

-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( version: 10.13.6 )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.9

#### I installed PuLP via:

- [x] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [ ] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
I do not understand 100% why that would fix your issue. But I don't see the harm on adding the change you mention. Can you do a PR with the change?

thanks

**Comment by LBeghini** [comment]
So, I got errors with the pull request, but I believe they're not related with the changes I've made.
