### ISSUE TITLE
Pulp is flashing empty log windows

### ISSUE THREAD

**Issue by filtermap** [coin-or/pulp#516]
#### What did you do?

I'm using `PULP_CBC_CMD` solver (`COIN_CMD` internally) for [my project (developing an scheduling app, it has GUI)](https://github.com/filtermap/pulp-scheduling/tree/a5688d8709ba59da37ad5cde69049871c66fbe69).

#### What did you expect to see?

Pulp shows no window on a GUI app when `msg=False` was passed to `PULP_CBC_CMD`.

```py
problem.solve(pulp.PULP_CBC_CMD(msg=False))
```

#### What did you see instead?

On Windows, Pulp is flashing empty log windows even when `msg=False` was passed to it.  
Such windows scared GUI app users.

According to [this discussion](https://groups.google.com/g/pulp-or-discuss/c/TKBBGF3vOo4/m/03tXAG-JAgAJ) and [a pull request](#116) below, just for `GLPK`, this problem was solved.

[Suppressing window popping up](https://groups.google.com/g/pulp-or-discuss/c/TKBBGF3vOo4/m/03tXAG-JAgAJ)

[Prevent flashing windows on Windows by oprypin · Pull Request #116 · coin-or/pulp](https://github.com/coin-or/pulp/pull/116)

But flashing windows problem still alives in `PULP_CBC_CMD` (and `COIN_CMD`).

### Useful extra information

I fixed the problem with this patch for my project.

[Comparing coin-or:master...filtermap:master · coin-or/pulp](https://github.com/coin-or/pulp/compare/master...filtermap:master)

I referred the pull request #116.

#### I'm opening this issue because:

- [x] PuLP has a bug
- [ ] PuLP needs a feature
- [ ] PuLP has another problem

#### I'm using PuLP on:

- [x] Windows: ( _version:_ 10 Pro )
- [ ] Linux: ( _distro:_ \_\_\_ )
- [ ] Mac OS: ( _version:_ \_\_\_ )
- [ ] Other: \_\_\_

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.9.9

#### I installed PuLP via:

- [x] pypi (pip install pulp)
- [ ] github (pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: \_\_\_

#### I have also:

- [x] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

[Suppressing window popping up](https://groups.google.com/g/pulp-or-discuss/c/TKBBGF3vOo4/m/03tXAG-JAgAJ)

I have found one discussion and one pull request #116.
But this pull request is just for GLPK, not for COIN.

**Comment by filtermap** [comment]
Could I make a pull request?

**Comment by pchtsp** [comment]
Yes, feel free to do a PR
