### ISSUE TITLE
Modernize tests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#52]
```
Currently the tests are mostly in a test module in the form of a collection of 
functions, but they also exist as doctests and little scripts at the end of 
files, plus some examples in a separate package that doesn't get installed on 
users' systems.

My proposal is to modernize the tests using Python's unittest library. This 
will allow all the tests -- including the examples and 
end-of-module-little-test-scripts to all by run simply with `python -m unittest 
pulp.tests`, even on installed systems, without resorting to adding a script to 
the user's /usr/local/bin (which just contributes to the cruft problem). 
Moreover, since this project is a library, not an application, it will be 
helpful to separate the tests and the library code.

Since the purpose is to modernize, I think that issue #40 (to add Python 3 
support) should happen first. Once that's done, I can start working on a patch.
```

Original issue reported on code.google.com by `wkschwa...@gmail.com` on 30 Oct 2013 at 2:16

**Comment by dassouki** [comment]
Have a look at [this code](http://pastie.org/private/peytoxgtjqeerkiadzbeda) that I worked on the last few days as a unit-test implementation. If this looks good to you, I can finish the whole refactoring soon. Note that I only have access to GLPK.

**Comment by stumitchell** [comment]
Looks ok,
please don't 
    import unit_tests as ut

I would prefer
    from unit_tests import solver

also it seems that this will only test one solver as the unit_tests.solver() function will just return the first one

**Comment by dassouki** [comment]
@stumitchell noted on the import.

I'm still figuring out how to loop over the available solvers without generating errors. 

I'll spend the next week or so refactoring the tests into unittests

**Comment by dassouki** [comment]
So I converted all the tests to unit_test and everything seems to work fine (except for two tests). I have a question: are you ok with using [pyest](http://pytest.org/) to do the passing of multiple solvers to the test functions?

**Comment by pchtsp** [comment]
I'll close this since the tests have been recently changed to unittests since 0803cb0fd27bf80661d3b1c4d7b2a9fdc75ec04a
