### ISSUE TITLE
Remove redundant combinatorics functions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#53]
```
permutations and combinations are already provided by Python's itertools 
standard library module 
(http://docs.python.org/2.7/library/itertools.html#itertools.permutations). 
Pulp's versions of these should be removed and the name aliased to the standard 
library versions. This will reduce the amount of code needing testing, since 
the standard library's versions are already heavily tested and used. By keeping 
the names as aliases to the std lib, we would avoid breaking backward 
compatibility.
```

Original issue reported on code.google.com by `wkschwa...@gmail.com` on 30 Oct 2013 at 6:35

**Comment by pchtsp** [comment]
From what I can see in the code, it already uses `itertools.combination` and `itertools.permutation`. On the other side, and at least in python 3.5, itertools only has `combinations` and `permutations`. With an `s`. Not sure what this means, though. Should we do an import compatible with python 3? should we take out the old code and only work with itertools from python 2 or python 3? @stumitchell

**Comment by pchtsp** [comment]
Ok, I've done these changes too in the latest commit. Closing the issue.
