### ISSUE TITLE
PULP_CBC_CMD PulpSolverError: Not Available check permissions

### ISSUE THREAD

**Issue by RafalKucharskiPK** [coin-or/pulp#533]
Details for the issue
--------------------

#### What did you do?

I run the 'PuLP' solver on my OSx and after some conda updates it stopped recognizing the solver.

I call:

```
solver = pulp.get_solver('PULP_CBC_CMD')
prob.solve(solver)
```

#### What did you expect to see?

Recently (on the same machine with the same code) everything was running fine.

#### What did you see instead?

I think after some conda updates lately I receive this issue:

`pulp.apis.core.PulpSolverError: PULP_CBC_CMD: Not Available (check permissions on /opt/anaconda3/envs/my_env/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc)`

Useful extra information
-------------------------

When I asked for a path I got:

```
pl.pulp_cbc_path
Out[9]: '/opt/anaconda3/envs/ExMAS/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc
```

Maybe interestingly, my conda env is for python 3.9 and my PuLP is in3.8 folder

My PuLP is 2.6.0

#### What operating system are you using?

- [X] Mac OS: ( _version:12.01 M1 )

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [X] Other: 3.9

#### I installed PuLP via:

- [ ] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [X] Other: conda

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [X] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

PS 1. This is the structure of my pulp installation ![image](https://user-images.githubusercontent.com/20555451/158819106-f1769e73-37cf-4d95-9b02-4d59155d82ea.png)

PS2. PS. My 'conda list'

packages in environment at /opt/anaconda3/envs/ExMAS:

Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
amply                     0.1.4                      py_0    conda-forge
anyio                     3.5.0            py38h50d1736_0    conda-forge
appnope                   0.1.2            py38h50d1736_2    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h96a0964_1    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
blas                      2.113                  openblas    conda-forge
blas-devel                3.9.0           13_osx64_openblas    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               he49afe7_0    conda-forge
boost-cpp                 1.74.0               hdbf7018_7    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py38h96a0964_1003    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cairo                     1.16.0            h9e0e54b_1010    conda-forge
certifi                   2021.10.8        py38h50d1736_1    conda-forge
cffi                      1.15.0           py38h1a44b6c_0    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4            py38h50d1736_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
coin-or-cbc               2.10.7               hada2c85_0    conda-forge
coin-or-cgl               0.60.3               h1c2bb20_2    conda-forge
coin-or-clp               1.17.6               h79c0eca_3    conda-forge
coin-or-osi               0.108.6              h009c923_2    conda-forge
coin-or-utils             2.11.6               h07ff368_0    conda-forge
coincbc                   2.10.7            0_metapackage    conda-forge
cryptography              36.0.1           py38h56c4533_0    conda-forge
curl                      7.82.0               h9f20792_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h811a1a6_3    conda-forge
debugpy                   1.5.1            py38ha048514_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docutils                  0.18.1           py38h50d1736_0    conda-forge
dotmap                    1.3.26                   pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.7                h96cf925_0    conda-forge
fiona                     1.8.21           py38h2077077_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.96              h676cef8_2    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.30.0           py38hed1de0f_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h0d85af4_0    conda-forge
gdal                      3.4.2            py38h0b97839_0    conda-forge
geopandas                 0.10.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.10.2             pyha770c72_1    conda-forge
geos                      3.10.2               he49afe7_0    conda-forge
geotiff                   1.7.1                had63758_0    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.12.1          nompi_ha60fbc9_104    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py38h50d1736_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.9.2            py38h60dac5d_0    conda-forge
ipython                   8.1.1            py38h50d1736_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.0              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1           py38h50d1736_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py38h50d1736_7    conda-forge
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.3              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py38h50d1736_0    conda-forge
jupyter_server            1.15.6             pyhd8ed1ab_0    conda-forge
jupyterlab                3.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.11.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.0              pyhd8ed1ab_0    conda-forge
kealib                    1.4.14               ha22a8b1_3    conda-forge
kiwisolver                1.4.0            py38h8b7791e_0    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libclang                  13.0.1          default_he082bbe_0    conda-forge
libcurl                   7.82.0               h9f20792_0    conda-forge
libcxx                    13.0.1               hc203e6f_0    conda-forge
libdap4                   3.20.6               h3e144a0_2    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgdal                   3.4.2                h52a0caa_0    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8fd9edb_1014    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
liblapacke                3.9.0           13_osx64_openblas    conda-forge
libllvm13                 13.0.1               h64f94b2_2    conda-forge
libnetcdf                 4.8.1           nompi_h6609ca0_101    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     14.2                 hea3049e_0    conda-forge
librttopo                 1.1.0                hec60dd8_9    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libspatialindex           1.9.3                he49afe7_4    conda-forge
libspatialite             5.0.1               hadde3e2_15    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libzip                    1.8.0                h8b0c345_1    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py38hed1de0f_0    conda-forge
matplotlib                3.5.1            py38h50d1736_0    conda-forge
matplotlib-base           3.5.1            py38hc7d2367_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h96a0964_1005    conda-forge
mkl                       2022.0.0           h89fa619_782    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.28               h694c41f_0    conda-forge
mysql-libs                8.0.28               h115446f_0    conda-forge
nbclassic                 0.3.7              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.13             pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.4            py38h50d1736_0    conda-forge
nbformat                  5.2.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
ninja                     1.10.2               h940c156_1    conda-forge
nomkl                     3.0                           0  
notebook                  6.4.10             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.74                 h31e2bf1_0    conda-forge
numexpr                   2.8.0            py38ha53d530_1    conda-forge
numpy                     1.22.2           py38h9d72dae_0    conda-forge
openblas                  0.3.18          openmp_h12da7db_0    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
osmnx                     1.1.2              pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py38ha53d530_0    conda-forge
pandoc                    2.17.1.1             h694c41f_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.0.1            py38h7207f37_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   22.01.0              h39497b0_1    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 he8fe76e_0    conda-forge
proj                      9.0.0                h2364a93_1    conda-forge
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
prompt_toolkit            3.0.27               hd8ed1ab_0    conda-forge
psutil                    5.9.0            py38h96a0964_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulp                      2.6.0            py38h50d1736_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0            py38h29c3664_2    conda-forge
pyqt                      5.12.3           py38h50d1736_8    conda-forge
pyqt-impl                 5.12.3           py38hb240fba_8    conda-forge
pyqt5-sip                 4.19.18          py38h1d3b384_8    conda-forge
pyqtchart                 5.12             py38hb240fba_8    conda-forge
pyqtwebengine             5.12.1           py38hb240fba_8    conda-forge
pyrsistent                0.18.1           py38h96a0964_0    conda-forge
pysocks                   1.7.1            py38h50d1736_4    conda-forge
python                    3.8.12          h17280f6_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.4.0                   py3.8_0    pytorch
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyzmq                     22.3.0           py38hd3b92b6_1    conda-forge
qt                        5.12.9               h2a607e2_5    conda-forge
qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge
qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
rasterio                  1.2.10           py38hdae6004_5    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py38hc59ffc2_3    conda-forge
scikit-learn              1.0.2            py38h37f3bb3_0    conda-forge
scipy                     1.8.0            py38hd329d04_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                60.10.0          py38h50d1736_0    conda-forge
shapely                   1.8.0            py38hf980569_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0            py38h50d1736_2    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.1               hb516253_0    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.2           py38hbe852b5_0    conda-forge
tbb                       2021.5.0             h940c156_0    conda-forge
terminado                 0.13.3           py38h50d1736_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.7.1                h190f7ed_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.1              py38h96a0964_2    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
tzcode                    2022a                h5eb16cf_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py38h96a0964_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.3.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.0            py38h50d1736_0    conda-forge
xerces-c                  3.2.3                h6564042_4    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xyzservices               2022.3.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge

**Comment by RafalKucharskiPK** [comment]
Ok, seems fixed. 

when I unistalled `pulp` - both from `conda` and `pip` (I think by default my conda pulp was used) and then installed them again (only with `pip` now)

it seems to be solved. maybe this was issue with conda installation and pip installation was fine...?

**Comment by omendezmorales** [comment]
Any idea what to do if instead I installed in xubuntu using APT?  I was just trying to run an example of [linear programming](https://slama.dev/youtube/linear-programming-in-python/#introduction). Thanks,
