### ISSUE TITLE
Code documentation links broken

### ISSUE THREAD

**Issue by tgrrr** [coin-or/pulp#537]
Details for the issue
--------------------

#### What did you do?

Clicked the link in https://coin-or.github.io/pulp/CaseStudies/a_transportation_problem.html#storage-and-buying-in

#### What did you expect to see?

Code to: https://github.com/coin-or/pulp/blob/master/examples/BeerDistributionProblemWarehouseExtension.py

#### What did you see instead?

Navigated to: https://projects.coin-or.org/PuLP/browser/trunk/examples/BeerDistributionProblemWarehouseExtension.py?format=txt

Error message displayed:

```
No node trunk/examples/BeerDistributionProblemWarehouseExtension.py at revision 361
```

**Comment by pchtsp** [comment]
Thanks! Could you do a PR with the correct link?

F.
