### ISSUE TITLE
Getting modulenotfounderror even though I have installed it

### ISSUE THREAD

**Issue by samir744** [coin-or/pulp#547]
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/49587006/171866592-0e04fd7e-2bd9-4be5-8a17-569c9eedee97.png">

As you can see i have already installed PuLP but still getting a ModuleNotFoundError, not sure what am I doing wrong. If it matters I am using a Macbook Pro M1 on Monterey and using Python 3.9

**Comment by tkralphs** [comment]
Capitalization matters and the package name is `pulp`, not `PuLP`. It's pretty strange that `pip` seems to be happy with `PuLP`.

**Comment by samir744** [comment]
Thanks, 'pulp' worked. The blog on which I learnt about pulp spelled it like PuLP in their code
