### ISSUE TITLE
Is there a need for checkLengthVars for HiGHS?

### ISSUE THREAD

**Issue by berkorbay** [coin-or/pulp#548]
Hi, 

I just came across a problem with my variable names because they were "too long". Root of this problem is given below.

https://github.com/coin-or/pulp/blob/9db89a7c2702cc210330ca7498e1e8d5e7c263a7/pulp/apis/highs_api.py#L100

I must disagree with this choice because of the following.

- This method creates an .mps file not an .lp file and mps can handle long variable names.
- HiGHS can handle long variable names. I just exported my model to an mps file (> 250MB as a result) and fed it to HiGHS from Terminal. It worked well.

Is there a specific reason for it to stay? Perhaps, just to play safe, a kwargs parameter to circumvent the requirement (e.g. varlength_check with default as True)?

**Comment by jajhall** [comment]
pulp/pulp/apis/highs_api.py is rather out-of-date. If nothing else, HiGHS can now solve MIPs - better (in general) than any other open-source MIP solver. I don't know why the limit of 52 was ever there: maybe it related to a HiGHS limit that existed when highs_api.py was written 2+ years ago.

**Comment by berkorbay** [comment]
@jajhall HiGHS actually works quite well with PuLP without the character limit. If I remember correctly that limit actually is needed for .lp files but not .mps files. Probably it is just a copy-paste issue. HiGHS is a great solver btw!

**Comment by jajhall** [comment]
The .lp file reader has developed a lot in the past 12 months, so I don't imagine that there is a limit any longer

Great to heat that you appreciate HiGHS

**Comment by berkorbay** [comment]
Added a pull request with the changes: https://github.com/coin-or/pulp/pull/554
