### ISSUE TITLE
Variable hash isn't consistent between different instances of the same variable

### ISSUE THREAD

**Issue by ldeluigi** [coin-or/pulp#558]
Details for the issue
--------------------

#### What did you do?
Same as https://github.com/coin-or/pulp/issues/395

#### What did you expect to see?
No errors at all

#### What did you see instead?
CBC complaining of having duplicate variables

Useful extra information
-------------------------
I understood that the issue comes from the fact that the hash of a variable, which is used to check if it's already present inside the problem in addVariable(..), is implemented with python id(self) function, which is unique for every instance of LpVariable

instead, it should implemente based on the NAME of the variable, or better it should use the name instead of the hash in the first place, so that different instances of LpVariables with the same names are the same variable

**Comment by ldeluigi** [comment]
My monkeypatch:
```py
class LpVariable(lp.LpVariable):
    def __init__(self, name, lowBound=None, upBound=None, cat=lp.LpContinuous, e=None):
        super().__init__(name, lowBound, upBound, cat, e)
        self.hash = hash(name)
```

**Comment by pchtsp** [comment]
I understand what you mean, but we have been using the hash based on the `id` for a while and I fear it would break things if we change it to use the name of the variable. 

Is there a reason you want to use the name of the variable? Because if you're duplicating variable names inside your model, you probably have some other issue in the model building itself... You shouldn't be trying to create more than one variable with the same name in any case.

**Comment by ldeluigi** [comment]
The idea is to avoid fetching up the original every time. I have functions in my code that take a LpProblem as input and add constraints to it. I'd like to express my constraints in a simple way, without having to look through already added variables in the LpProblem in order to fetch the needed ones, and create them only if they don't exist. It's cumbersome and slow. Instead, with my patch, I'm simply adding new constraints by creating LpVariable instances on the fly, and everything worked fine so far.

In the addConstraint method, if the LpVariable hash is already present inside the LpProblem, the addition of a duplicate is skipped, so I don't think there would be bug unless someone explicity uses hash(variable) knowing it returns the id(self) of it...

**Comment by ldeluigi** [comment]
Another way to have the result I'm looking for is to keep a dict of variable names -> variable instances inside the problem so that I can do like problem.vars[name] to get the variable instance with name name in constant time

**Comment by ldeluigi** [comment]
but that would still require me something like problem.vars[name] if name in problem.vars else LpVariable(name, ...)

**Comment by ldeluigi** [comment]
After further testing it seems that the monkeypatch causes in fact issues. I created my own data structure for efficient variable retrieval based on the name as a solution.
