### ISSUE TITLE
Constraint names shouldn't begin with a number

### ISSUE THREAD

**Issue by ldeluigi** [coin-or/pulp#561]
Here:
https://github.com/coin-or/pulp/blob/18f96a0cd5f0ea4ba9f732ed39d46c84aa9432fe/pulp/pulp.py#L1968-L1970
you are naming a constraint like "0_..." which is not permitted for .lp files, according to
https://www.ibm.com/docs/en/icos/12.8.0.0?topic=representation-constraints-in-lp-file-format :

> Constraint names must adhere to the same guidelines as variable names.

https://www.ibm.com/docs/en/icos/12.8.0.0?topic=representation-variable-names-in-lp-file-format :

> A variable name can not begin with a number or a period.

Please fix it, as it throws a "missing constraint sense" CPLEX LP file processing error with glpsol

**Comment by pchtsp** [comment]
Hello and thanks for reporting.

If you make a PR, I'd be happy to review it.

I guess we could put the number at the end of the name, instead of the
beginning. I also guess we could check if there's already a constraint
that's called like that. Just in case...

F.

**Comment by ldeluigi** [comment]
I made a PR. Should be #562 

Happy to help!
