### ISSUE TITLE
Getting -1s and 2s for binary variables :/

### ISSUE THREAD

**Issue by asross** [coin-or/pulp#569]
Details for the issue
--------------------

#### What did you do?

I created a linear program with binary variables, which I tried implementing in a couple different ways, e.g.:

```python
pl.LpVariable(name, 0, 1, cat='Integer')
pl.LpVariable(name, cat='Binary')
pl.LpVariable(name, lowBound=0, upBound=1, cat='Integer')
```

Then I included it in a particular problem and solved it.

#### What did you expect to see?

I expected that the solution would have these variables either equal to 0 or 1.

#### What did you see instead?

I found a few cases where the variables came back as -1 or 2.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Mac OS: ( _version:_ 12.4 )

#### I'm using python version:

- [x] Other: 3.9

#### I installed PuLP via:

- [x] pypi (python -m pip install pulp)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by stumitchell** [comment]
Did you check the Solution Status before you checked the variable values.

Some solvers return variable values even when the status is infeasible.

**Comment by asross** [comment]
Ergh, that was my problem! Not a bug in the library then :)
