### ISSUE TITLE
Problems with slacks in CoinMP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#57]
```
Hi,

When one wants to use cplex through a binding, two choices are
available: CPLEX_DLL and CPLEX_PY.
- the _DLL loads cplex dynamic library through ctypes, but AFAIK, it
does not work for recent versions
- the _PY loads cplex through the official binding, and only works for
recent versions.

Curently it is not clear how pulp should be configured to use the _PY
cplex binding. I believe it would be more handy if it was handled the
same way gurobi is handled: we take care of appending the path to
their library to the python path. This should be user-specified in
pulp.cfg with a variable.

What name should be used? GUROBI specifies this path through the
variable GurobiPath, so CplexPath would be a logical choice. However,
it is already taken and used by CPLEX_DLL to specify the path to the
dynamic library.

Cheers,
Tof
```

Original issue reported on code.google.com by `s...@stuartmitchell.com` on 31 Oct 2013 at 9:51

Attachments:
- [coinmp-slack.patch](https://storage.googleapis.com/google-code-attachments/pulp-or/issue-57/comment-0/coinmp-slack.patch)

**Comment by tkorvola** [comment]
Something appears to have gone wrong with the issue export: the comment above is unrelated to the heading and the patch. The patch can be pulled from https://github.com/tkorvola/pulp.git, branch coin-bug.

**Comment by pchtsp** [comment]
I'm going to close this issue because of both the problem in the text and age. If you think this issue is not solved, please add a new one. Thanks!
