### ISSUE TITLE
Gurobi: If status not optimal, solution cannot be retrieved

### ISSUE THREAD

**Issue by torressa** [coin-or/pulp#586]
Details for the issue
--------------------

#### What did you do?

```python
_, prob = LpProblem.fromMPS(
    "/path/to/large/model.mps"
)
solver = GUROBI(msg=True, TimeLimit=10)
prob.solve(solver)
for v in prob.variables():
    assert v.varValue is not None
```

#### What did you expect to see?

Solution values are being retrieved.

#### What did you see instead?

All variables have value `None`

**Comment by torressa** [comment]
Workaround is to use `GUROBI_CMD` instead

**Comment by CMueller12** [comment]
That is true but GUROBI_CMD is much slower :(

**Comment by ronaldvdv** [comment]
Problem is [here](https://github.com/coin-or/pulp/blob/006753076be18ee857339d333a5db11e599f21a2/pulp/apis/gurobi_api.py#L122) ; it seems PuLP does not differentiate between "not solved / no solution available" and "solution available but optimality not proven yet" and therefore considers "TIME_LIMIT" status as "no solution available".
