### ISSUE TITLE
Problem status is 2(optimal) but seems to ignore some constraints

### ISSUE THREAD

**Issue by LuoXiaoxi-cxq** [coin-or/pulp#592]
I'm trying to use Gurobi solver in pulp to solve a big linear programming problem. The status Gurobi returned is 2, which means that an optimal solution is available, but the solution doesn't meet my expectations. Here is the part where problem occurs:

```
    MyProblem = pulp.LpProblem("MyProblem",LpMinimize)    # define the problem

    # define variable
    var_shengmu = {i: LpVariable(name=f"var_shengmu{i}", lowBound=0, upBound=100,cat=LpInteger) for i in range(N)}    
    var_qiuyi_shengmu={i:{j:LpVariable(name=f"var_qiuyi_shengmu{i}{j}",cat=LpBinary)for j in range(i+1,N)} for i in range(N)}    

    # add constraint
    inf=10**6
    eps=10**(-5)
    for i in range(N):
        for j in range(i+1,N):
            if some_condition:   # if var_shengmu[i] and var_shengmu[j] should be different
                #constraint (a)
                MyProblem+=(var_shengmu[i]-var_shengmu[j])<=-eps+inf*var_qiuyi_shengmu[i][j]    
                #constraint (b)                
                MyProblem+=(var_shengmu[j]-var_shengmu[i])>=eps-inf*(1-var_qiuyi_shengmu[i][j])

```
The last two lines above is an inequality constraint, I want to make var_shengmu[i] and var_shengmu[j] different. The idea is that if `var_shengmu[j]==var_shengmu[i]`, whatever `var_qiuyi_shengmu[i][j]` is, constraint(a) and (b) cannot be satisfied together.

However, the variables `var_shengmu` are all 0(from `var_shengmu[0]` to `var_shengmu[N]`) in the solution.

I followed [this answer][1] to print the constraints, and I surprisingly found that for all `i` and `j`, the constraint (b) I listed above are not satisfied. Some of my outputs are here:

    -1000000*var_qiuyi_shengmu25472548 - var_shengmu17040 + var_shengmu17046 <= -1e-05
    is satisfied
    -1000000*var_qiuyi_shengmu25472548 - var_shengmu17040 + var_shengmu17046 >= -999999.99999
    not satisfied

I'm extremely bewildered why the status is optimal but some constraints are ignored. Did I make something wrong? Thank in advance for your help!

By the way, you maywonder why don't I have an objective function. It's because the code I list here is only a small part of my problem, and in other parts, the objective function is defined.
  
[1]: https://stackoverflow.com/questions/69019758/finding-which-constraints-are-not-true-when-pulp-optimization-does-not-solve-in

**Comment by stumitchell** [comment]
The solvers that pulp use solve matrix equations with floating point arithmetic with certain tolerances.
This means that ensuring 2 floating point variables are exactly the same or in this case a little different will have problems solving.

If you increase eps you should get a better solution.

**Comment by LuoXiaoxi-cxq** [comment]
@stumitchell I tried your suggestion, and it works! Thank you very much!! Have a nice day!
