### ISSUE TITLE
Add CI tests for pull requests

### ISSUE THREAD

**Issue by siwy** [coin-or/pulp#605]
Describe the new feature
--------------------------

While working on https://github.com/coin-or/pulp/pull/604 , I've noticed that this project is lacking a CI pipeline.
* There's no way to run tests automatically (and therefore, the maintainers will probably need to manually check the tests for my PR)
* There's no automated code-standards test (eg. a check to see if we've ran black on all files that are committed).

Is there appetite to add this? We might be able to add such tests with github actions for free

Additional info
---------------

#### Is your feature request related to an issue? Please include the issue number.

No

#### Does this feature exist in another product or project? Please provide a link.

Many open-source projects have similar pipelines set up. I'm happy to look for examples

**Comment by pchtsp** [comment]
I'm not sure what you mean. But if you want to add the new solver to the github action tests, please check https://github.com/coin-or/pulp/blob/master/.github/workflows/pythonpackage.yml

**Comment by siwy** [comment]
Ah! That's great! I missed this, please ignore this issue. I'm going to add the solver to the github actions!
