### ISSUE TITLE
Give an obvious wrong result for a very simple problem

### ISSUE THREAD

**Issue by kmeng** [coin-or/pulp#686]
Details for the issue
--------------------

#### What did you do?
Write a very simple program for learning:

def solve_by_pulp():
    model = pulp.LpProblem('Sample3_1', LpMaximize)

    # define decision variables
    x1 = pulp.LpVariable('x1', lowBound=0)
    x2 = pulp.LpVariable('x2', lowBound=0)
    x3 = pulp.LpVariable('x3', lowBound=0)

    # set objective
    model += 2*x1 + 3*x2 - 5+x3

    # set constraint
    model += x1 + x2 + x3 == 7
    # 下面的两个约束条件没有起作用
    model += 2*x1 - 5*x2 + x3 >= 10
    model += x1 + 3*x2 + x3 >= 12

    model.solve()

    print('x1 = {}'.format(x1.varValue))
    print('x2 = {}'.format(x2.varValue))
    print('x3 = {}'.format(x3.varValue))
    print('max z= ', value(model.objective))

#### What did you expect to see?

It should be no result.

#### What did you see instead?

  x1 = 6.4285714
  x2 = 0.57142857
  x3 = 0.0
  max z=  9.57142851

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.11

#### I installed PuLP via:

- [ ] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [x] Other: ___ (pycharm)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [ ] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by kmeng** [comment]
if the third constraint is changed to:

 model += x1 + 3*x2 + x3 <= 12

The objective value was wrong either.  it should be 9.57142851

**Comment by stumitchell** [comment]
Did you check the solution status?

I answered this on my phone. Please excuse any typos and brevity

**Comment by kmeng** [comment]
Thanks. 
It seems I got a wrong sample
