### ISSUE TITLE
Test suite returns non-zero when running under Python3.12

### ISSUE THREAD

**Issue by tillea** [coin-or/pulp#709]
Details for the issue
--------------------

A bug was [reported](https://bugs.debian.org/1056493) to the Debian packaged version of pulp which states the test suite does not return zero exit code and thus triggers a failure in our CI.

#### What did you do?

The bug report links to a [full test log](https://autopkgtest.ubuntu.com/results/autopkgtest-noble/noble/amd64/p/python-pulp/20231118_184757_b46d3@/log.gz) on some Ubuntu machine.  You can also find the [code of the test script](https://salsa.debian.org/math-team/python-pulp/-/blob/master/debian/tests/run-unit-test) inside the packaging Git.

#### What did you expect to see?

Since I can't see any failure inside the log I would expect a zero exit code.  But maybe your inside to the test suite is better than mine (I'm not a user of pulp, just a random Debian maintainer of a package depending from pulp) and you might see some issue.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Linux: Debian unstable / Ubuntu

#### I'm using python version:

- [x] 3.12

#### I installed PuLP via:

Tried to build the Debian package, running its CI test

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Hello. Thanks for letting us know. We were not testing with python 3.12 in CI. It seems that some of the solvers we test (highspy and xpress) do not have a 3.12 python version. I've taken them out from the github tests for now. Without those solvers, the package runs fine. Can you confirm?

**Comment by tillea** [comment]
Nilesh Patra has found some solution to fix the tests in Debian which is basically

    --- a/debian/tests/run-unit-test
    +++ b/debian/tests/run-unit-test
    @@ -16,5 +16,5 @@ cd "$AUTOPKGTEST_TMP"
     pys="$(py3versions -s 2> /dev/null)"
     for py in $pys; do
            echo "=== $py ==="
    -       $py -m unittest discover -v
    +       $py -m unittest discover -v pulp/tests
     done
