### ISSUE TITLE
Pickle an LP problem

### ISSUE THREAD

**Issue by stumitchell** [coin-or/pulp#71]
Everybody,

It seems to be a bug that an LP problem cannot be pickled and re-loaded.

The problem is described here:
http://stackoverflow.com/questions/22849208/pickle-not-playing-nice-with-pulp

The variables are duplicated.

This seems to still be an issue with PuLP 1.5.6.

reported by Jesper Kristensen jespertoftkristensen@gmail.com

**Comment by pchtsp** [comment]
for now, I'm offering the following alternative:

https://coin-or.github.io/pulp/guides/how_to_export_models.html
