### ISSUE TITLE
COPT interface on master fails CI tests

### ISSUE THREAD

**Issue by aphi** [coin-or/pulp#714]
The COPT interface on master is breaking on `test_pulp_023`. i.e. if we retriggered the tests on master now they would fail with this error below - I've confirmed that on my fork.

Presently this blocks PRs #713  and #710  which make unrelated changes but both hit this error.

```ERROR: test_pulp_023 (pulp.tests.test_pulp.COPTTest) ---------------------------------------------------------------------- Traceback (most recent call last): File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pulp/tests/test_pulp.py", line 473, in test_pulp_023 pulpTestCheck(prob, self.solver, [const.LpStatusOptimal], solution) File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pulp/tests/test_pulp.py", line 1616, in pulpTestCheck [const.LpStatus[s] for s in okstatus], pulp.constants.PulpError: Tests failed for solver <pulp.apis.copt_api.COPT object at 0x1061f9810>: status == 0 not in [1] status == Not Solved not in ['Optimal']```

@wujianjack @pchtsp

**Comment by wujianjack** [comment]
@aphi Thanks for reporting this issue! We have reproduced and identified the bug, it's about incorrect final MIP status when our MIP start routine determine that the start solution is indeed optimal. The fix will be included in our next patch release.

Thanks again!

**Comment by wujianjack** [comment]
@aphi Sorry for the delay, we just released 7.0.5 and fixed the issue. Thanks again!

**Comment by aphi** [comment]
@wujianjack Nice one - thanks. Verified to be working in my PR as well, so will close this issue.
