### ISSUE TITLE
encoding of cplex_cmds in class CPLEX_CMD in solvers.py does not work for Python 3

### ISSUE THREAD

**Issue by timnon** [coin-or/pulp#73]
A simple fix is to add the line:

cplex_cmds = cplex_cmds.encode('UTF-8')

just before line:

cplex.communicate(cplex_cmds)

This has been tested with Python 2 and 3

**Comment by stumitchell** [comment]
I have done this with the same branch https://github.com/coin-or/pulp-or/tree/feature/cplex_cmd-timelimit can you please check that it works with cplex?

Stu

**Comment by timnon** [comment]
it works with Python 2.7.5.6 and 3.4.1.0

**Comment by stumitchell** [comment]
closed with https://github.com/coin-or/pulp/pull/81
