### ISSUE TITLE
HiGHS solver doesn't seem to respect msg=False

### ISSUE THREAD

**Issue by WPettersson** [coin-or/pulp#735]
Details for the issue
--------------------

#### What did you do?

Solved a problem with `solver=pulp.HiGHS(msg=False)`.

#### What did you expect to see?

Very little output from the solver

#### What did you see instead?

Information from the solver

Useful extra information
-------------------------

I've uploaded a sample test script to https://gist.github.com/WPettersson/414dbd0655382ed8e0f84040d2739368 for testing - obviously you need to pip install both pulp and highspy. It runs both PULP_CBC_CMD and HiGHS from pulp as solvers with msg=False - the CBC output is indeed empty but HiGHS does output some text. The code also directly calls code from highspy after that, which has no output. This highspy code also has the line `h.setOptionValue("output_flag", False)`. If I change this to True, then there is output from highspy between the "Start highspy" and "End highspy" lines. I think this suggests that pulp should possibly call `lp.solverModel.setOptionValue("output_flag", False)` if `msg == False` to fix this. 

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro: Debian )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 3.7
- [ ] 3.8
- [ ] 3.9
- [ ] 3.10
- [X] 3.11
- [ ] Other: ___

#### I installed PuLP via:

- [X] pypi (python -m pip install pulp)
- [X] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [X] Tried out the latest github version: https://github.com/coin-or/pulp
- [X] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
Thanks, it should be fixed with https://github.com/coin-or/pulp/pull/736
