### ISSUE TITLE
why is there no time limit for CPLEX_CMD?

### ISSUE THREAD

**Issue by timnon** [coin-or/pulp#74]
CPLEX offers the option to set the time limit when using class CPLEX_CMD, is there a reason why this is not supported? Maybe because other *_CMD classes do not offer this as well?

Add line (for ten seconds):

cplex_cmds += "set timelimit 10\n"

after line:

cplex_cmds = "read "+tmpLp+"\n"

**Comment by stumitchell** [comment]
Hi I have put a code change in https://github.com/coin-or/pulp-or/tree/feature/cplex_cmd-timelimit

as I don't have cplex can you please check that it works

prob.solve(CPLEX_CMD(timelimit=10)

Stu

**Comment by timnon** [comment]
there is a typo and the conversion of self.timelimit to string is missing, the following line fixes this:

cplex_cmds += "set timelimit " + str(self.timelimit) + "\n"

but then it works,
Tim
