### ISSUE TITLE
PulpSolverError on Infeasible solution with Highs

### ISSUE THREAD

**Issue by edwin6** [coin-or/pulp#761]
Details for the issue
--------------------

#### What did you do?

I tried to solve an infeasible problem using highs:

> m = pulp.LpProblem(sense=pulp.LpMaximize)
> x = pulp.LpVariable('x', cat=pulp.LpInteger, lowBound=0)
> y = pulp.LpVariable('y', cat=pulp.LpInteger, lowBound=0)
> m += 3*x + y
> m += 2*x + y <= 3.5
> m += x + y >= 4
> solver = pulp.HiGHS_CMD(msg=True, path=PATH_TO_HiGHS)
> m.solve(solver)

#### What did you expect to see?

I expected this to:
- Run without raising an error
- Return a solution status code constants.LpSolutionInfeasible
- Perhaps the variable values in the PuLP model object would not be updated, or updated to infeasible values

#### What did you see instead?

I got:
`PulpSolverError: Cannot read HiGHS solver output` on line 253 of highs_api.py

This occurs because we call `values = self.readsol(tmpSol)` on line 209. Perhaps:
- readsol needs to be able to read an empty solution file without raising an error, in the case the problem was Infeasible; or
- We should skip trying to read the solution when infeasible

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 3.7
- [ ] 3.8
- [x] 3.9
- [ ] 3.10
- [ ] 3.11
- [ ] Other: ___

#### I installed PuLP via:

- [x] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [x] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by edwin6** [comment]
Ah, I was using 2.8.0

Apologies, I thought I had the latest version but I really should have checked more carefully

**Comment by pchtsp** [comment]
no problem. We just released the version 2.9.0 a couple days ago
