### ISSUE TITLE
The key column gets duplicated after creating lp variable 

### ISSUE THREAD

**Issue by reshmastadas** [coin-or/pulp#768]
I tried to create lpVariable with the help of unique string column. I expected to see the LPVariable created to be unique, however, I found that the variables are duplicated (The string column has all unique values before creating the variable column as you can see in the below screenshot). The string column is a composite key column created by concatenating multiple columns to create unique key. The strange thing is the code runs perfectly fine on some days and creates duplicate variables on some other days. The length of the key column is dynamic in nature and depends on the values that flow in other columns that makes the composite key. 

#### What operating system are you using?

- [x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 3.7
- [ ] 3.8
- [ ] 3.9
- [ ] 3.10
- [ ] 3.11
- [x] Other: 3.11.7

#### I installed PuLP via:

- [x] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [ ] Other: ___ (conda?)

#### Did you also

- [ ] Tried out the latest github version: https://github.com/coin-or/pulp
- [x
![Capture](https://github.com/user-attachments/assets/0610ee50-3d97-4d78-a321-be5efc956d65)
] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pchtsp** [comment]
I'm not very familiar with the LpVariable.matrix method. But I do know that we have forbidden characters for the name of a variable because of our interfaces with solvers. These forbidden characters we replace for _ or something similar. So you may have names that, once cleaned, they are duplicated.
For example you can see here which characters we remove:

https://github.com/coin-or/pulp/blob/7286f40dbe99d1847979ee289d1bd820436520ad/pulp/pulp.py#L143-L170

**Comment by reshmastadas** [comment]
That does'nt seems to be the problem @pchtsp, thanks for responding though. I will try from my end as well and let you know if I figure out something :)
![Capture](https://github.com/user-attachments/assets/c5333fce-93d7-4ec6-8aa7-4472de4942e1)

**Comment by reshmastadas** [comment]
Hi I ran the code, this issue is not impacting anything and the code is running without any issues. I will close this now. Thanks for all the help :)
