### ISSUE TITLE
Can't get threads to work

### ISSUE THREAD

**Issue by IanMoroney** [coin-or/pulp#774]
What is your question
-----------------------

When trying to use PULP_CBC_CMD from pulp, i'm unable to use threads:

```
from pulp import PULP_CBC_CMD
solver = PULP_CBC_CMD(threads=10)
```

```
No match for threads - ? for list of commands
No match for 10 - ? for list of commands
```

in requirements.txt:
PuLP==2.9.0

I saw that other people using this python package don't seem to have this issue, so i wasn't sure what I was doing wrong.

**Comment by Ch00k** [comment]
@IanMoroney have you ever figured this out? I see the same with PuLP 3.0.
