### ISSUE TITLE
COINMP_DLL reports errors duing pulpTestAll

### ISSUE THREAD

**Issue by ferranmc** [coin-or/pulp#80]
Hi,

   I'm trying to run pulp together with coinmp_dll. For that I've downloaded and compiled the latest stable version of CoinMP which includes also CBC. When I run the tests both cbc (the one I compiled and the one bundled with pulp) pass the tests, but the coinmp_dll reports some failures. Are these failures expected and due to CoinMP code or pulp is not defining the problems in the same way for the external CBC than for the lib?

   Does this mean using libCoinMP.so is not reliable and that the best option is to use standalone CBC?

    Solver pulp.solvers.CPLEX_PY unavailable
         Testing zero subtraction
         Testing inconsistant lp solution
         Testing continuous LP solution
         Testing maximize continuous LP solution
         Testing unbounded continuous LP solution
         Testing Long Names
         Testing repeated Names
         Testing zero constraint
         Testing zero objective
         Testing LpVariable (not LpAffineExpression) objective
         Testing Long lines in LP
         Testing LpAffineExpression divide
         Testing MIP solution
         Testing MIP relaxation
         Testing feasibility problem (no objective)
         Testing an infeasible problem
         Testing an integer infeasible problem
         Testing column based modelling
         Testing fractional constraints
         Testing elastic constraints (no change)
         Testing elastic constraints (freebound)
         Testing elastic constraints (penalty unchanged)
         Testing elastic constraints (penalty unbounded)
    Solver pulp.solvers.COIN_CMD passed.

         Testing zero subtraction
         Testing inconsistant lp solution
         Testing continuous LP solution
         Testing maximize continuous LP solution
         Testing unbounded continuous LP solution
                 Error in CoinMP it reports Optimal
         Testing Long Names
         Testing repeated Names
         Testing zero constraint
         Testing zero objective
         Testing LpVariable (not LpAffineExpression) objective
         Testing LpAffineExpression divide
         Testing MIP solution
         Testing MIP relaxation
         Testing feasibility problem (no objective)
         Testing an infeasible problem
         Testing an integer infeasible problem
                 Error in CoinMP to be fixed, reports Optimal
         Testing column based modelling
         Testing column based modelling with empty constraints
         Testing dual variables and slacks reporting
    ('Test failed: constraint.slack', 'c3', '==', 7.0, '!=', 0)
    ('Test failed: constraint.slack', 'c2', '==', 10.0, '!=', 0)
    ('Test failed: constraint.slack', 'c1', '==', 3.0, '!=', 2)
         Testing resolve of problem
         Testing Sequential Solves
         Testing fractional constraints
         Testing elastic constraints (no change)
         Testing elastic constraints (freebound)
         Testing elastic constraints (penalty unchanged)
         Testing elastic constraints (penalty unbounded)
    Solver pulp.solvers.COINMP_DLL passed.

NOTE: I've commented out the exception raising to be able to check all failures.

Thanks in advance

**Comment by ferranmc** [comment]
Hi,

   I've seen issue 57 actually provides a patch that solves the slack failures. However there is no feedback on that patch. Is it the correct solution and will be added on the code or I should not use such patch?

Thanks

**Comment by stumitchell** [comment]
I would use cbc I don't think the overhead is too much.
I'm not sure if CoinMP is using the latest cbc version and I have given up waiting for the patch to be applied
