### ISSUE TITLE
Raise exception when using illegal LpVariable names

### ISSUE THREAD

**Issue by levis501** [coin-or/pulp#87]
There are several LpVariable name characters which are silently converted to underscores:
`# illegalChars = "-+[] ->/"`

Creating two variables which contain these characters in the name can inadvertently become duplicate variables.  e.g. variables named "x+" and "x-" are both mapped to "x_".   Duplicate variable names are not handled well by all the solvers, and sometimes fail without any clear error reporting.

I suggest that illegal variable names throw an exception instead of converting to underscores.

The following code fails:

```
problem = LpProblem("fail", LpMinimize)
variableNames = ['x+','x-']
vars = [LpVariable(name) for name in variableNames]
problem += lpSum(vars)
problem += vars[0] >= 0
problem += vars[1] >= 0
problem.solve()
```

with the exception

```
/usr/local/lib/python3.4/site-packages/pulp/solvers.py in solve_CBC(self, lp, use_mps)
   1344                                     self.path)
   1345         if not os.path.exists(tmpSol):
-> 1346             raise PulpSolverError("Pulp: Error while executing "+self.path)
```

The same code succeeds as expected if
`variableNames = ['x+','y-']`

Setting the following flag improves the error message somewhat, although the cause is still unclear
`LpSolverDefault.msg = 1`

results in 

```
Coin0008I MODEL read with 4 errors
There were 4 errors on input
** Current model not valid
```

A workaround for the user is to escape the variable names before creating the LpVariables with something like:

```
def escape(s):
    # illegalChars = "-+[] ->/"
    s = s.replace("-","(hyphen)")
    s = s.replace("+","(plus)")
    s = s.replace("[","(leftBracket)")
    s = s.replace("]","(rightBracket)")
    s = s.replace(" ","(space)")
    s = s.replace(">","(greaterThan)")
    s = s.replace("/","(slash)")
    return s
```

**Comment by stumitchell** [comment]
Hmm Will have a think about it.
You are right an exception is probably the best way to deal with it.
Maybe I'll put in a depreciation warning first.

Stu
