### ISSUE TITLE
PULP, mac Yosemite and Python 2.7

### ISSUE THREAD

**Issue by TeslaGeek** [coin-or/pulp#88]
Hi - I have installed PuLP 1.4.8 using "sudo python setup.py install" command and it seems the installation has gone through OK but when I run testpulp I receive this error "ImportError: No module named amply".

The same issue happens in Python interpreter if I use import pulp . Any thoughts? 

Thanks

**Comment by dassouki** [comment]
Curious, is there a reason you installed 1.4.8 instead of 1.6.0 (latest release). Also, why aren't you installing it from pip / easy_install?

**Comment by TeslaGeek** [comment]
I tried to install setuptools but I received permission error 

/Users/XXXX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/easy-install.pth: Permission denied

so I had to use sudo command. I have also been unable to upgrade PuLP 1.4.8 to PuLP 1.6 running the same sudo command. I downloaded the gz file for PuLP1.6, unzipped and went to the folder to run the similar command but for some reasons it did not install in the same path as 1.4.8. Thanks for the thought.

**Comment by tkralphs** [comment]
Python is a bit of a pain on OS X, but you can reduce the pain a lot by doing a few things. With Apple's Python, you will save yourself a lot of trouble if you use a virtual environment and avoid using sudo. Better yet, if you're going to be using Python a lot, it's worth the trouble to switch to using the Homebrew version, where a lot of packages can be installed more easily. Another option is to install Anaconda, which comes with most of the important scientific packages pre-installed (and I think it comes with pip and easy_install). If you take one of these approaches, I think PuLP will install without problems.

**Comment by TeslaGeek** [comment]
Thank you tkralphs. I looked briefly at Anaconda. It looks very promising. If I make any progress with it Ill post here. Many thanks.

**Comment by TeslaGeek** [comment]
I found a solution to install PuLP.
I had to sort out the PIP installation first as it was causing some issues such as 
/Users/XXXX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/easy-install.pth: Permission denied

What I did was installing pip using the following command:
 $ sudo easy_install pip

Then I ran 
$ pip install pulp 

and this installed PuLP with no problems.

Running $ sudo pulptest returned or in python running 

import pulp
pulp.pulpTestAll()

Returned following outputs. All good so far.
         Testing zero subtraction
         Testing inconsistant lp solution
         Testing continuous LP solution
         Testing maximize continuous LP solution
         Testing unbounded continuous LP solution
         Testing Long Names
         Testing repeated Names
         Testing zero constraint
         Testing zero objective
         Testing LpVariable (not LpAffineExpression) objective
         Testing Long lines in LP
         Testing LpAffineExpression divide
         Testing MIP solution
         Testing MIP solution with floats in objective
         Testing MIP relaxation
         Testing feasibility problem (no objective)
         Testing an infeasible problem
         Testing an integer infeasible problem
         Testing column based modelling
         Testing dual variables and slacks reporting
         Testing fractional constraints
         Testing elastic constraints (no change)
         Testing elastic constraints (freebound)
         Testing elastic constraints (penalty unchanged)
         Testing elastic constraints (penalty unbounded)
* Solver pulp.solvers.PULP_CBC_CMD passed.
Solver pulp.solvers.CPLEX_DLL unavailable
Solver pulp.solvers.CPLEX_CMD unavailable
Solver pulp.solvers.CPLEX_PY unavailable
Solver pulp.solvers.COIN_CMD unavailable
Solver pulp.solvers.COINMP_DLL unavailable
         Testing zero subtraction
         Testing inconsistant lp solution
         Testing continuous LP solution
         Testing maximize continuous LP solution
         Testing unbounded continuous LP solution
         Testing Long Names
         Testing repeated Names
         Testing zero constraint
         Testing zero objective
         Testing LpVariable (not LpAffineExpression) objective
         Testing LpAffineExpression divide
         Testing MIP solution
         Testing MIP solution with floats in objective
         Testing MIP relaxation
         Testing feasibility problem (no objective)
         Testing an infeasible problem
         Testing an integer infeasible problem
         Testing column based modelling
         Testing fractional constraints
         Testing elastic constraints (no change)
         Testing elastic constraints (freebound)
         Testing elastic constraints (penalty unchanged)
         Testing elastic constraints (penalty unbounded)
* Solver pulp.solvers.GLPK_CMD passed.
Solver pulp.solvers.XPRESS unavailable
Solver pulp.solvers.GUROBI unavailable
Solver pulp.solvers.GUROBI_CMD unavailable
Solver pulp.solvers.PYGLPK unavailable
Solver pulp.solvers.YAPOSIB unavailable
