### ISSUE TITLE
LpVariables initialized with only lower bound do not appear with lower bound in "print LpProblem" statement

### ISSUE THREAD

**Issue by slgsoccer** [coin-or/pulp#92]
I was attempting to debug a MILP in which I needed a continuous variable to be initialized with full range and then set bounds on it later. I mistakenly initialized it to be only positive, but this did not show up when I printed the problem (It just says the variable is "continuous" as opposed to "free continuous"). It'd be helpful to have that lower bound appear explicitly when the problem specification is printed.

![image](https://cloud.githubusercontent.com/assets/8855648/10112510/bba4b7e4-6390-11e5-9c8c-6fcb4d7e7a45.png)

z_0 was initialized as follows:

![image](https://cloud.githubusercontent.com/assets/8855648/10112527/d2847c56-6390-11e5-962a-d4689685f642.png)

**Comment by stumitchell** [comment]
I'm sorry but the variables are by default considered non-negative. But I can see how it can be confusing.
