### ISSUE TITLE
Non-free file within the project, licensing issue.

### ISSUE THREAD

**Issue by thomasgoirand** [coin-or/pulp#94]
Hi,

I tried to upload pulp in Debian, but the package has been rejected by the FTP masters, because of a non-free file. Here's the REJECT message from the FTP masters:

"Also it is rather bad that according to:
 python-pulp-1.6.0+dfsg1/doc/source/CaseStudies/a_set_partitioning_problem.rst
the license of wedding_seating.jpg seems to be CC BY-NC-ND 2.0,"

The CC BY-NC-ND is a non-free license, as it prevents redistribution.

Could you please get rid of this file, or get it re-licensed?

Also, from the Debian FTP masters, they wrote this:
"on a short glimpse I found the following licenses that should be 
mentioned in your debian/copyright:
 Zope
 CC Attribution-Share Alike 3.0 New Zealand License
 Perl Artistic License
 LaTeX Project Public License
 setup.py says the project is under BSD"

This is a lot of licenses. Wouldn't it be possible to have a better (unified) licensing in the project?

**Comment by pablooliveira** [comment]
I would also like to have pulp in Debian, it is a very nice project and having a package would facilitate its adoption. Is there any news on this issue ? Can I help resolving it ?

**Comment by pchtsp** [comment]
We have taken out the image, does it solve the problem?

**Comment by pchtsp** [comment]
Well... given the age of the issue and the fact nobody answered, I'm closing it.
